# Notebook A: Data Cleaning and Validation of Publicly Available Clinical Trial Data
## This notebook aims to clean, standardize, and validate the publicly available clinical trial dataset "The systemic responses to oral hyaluronic acid" before statistical analysis.

**Data source:** Zenodo  
**Dataset DOI:** 10.5281/zenodo.20930953

## 1. Library Imports

Let's import the necessary Python libraries for data cleaning and validation.

In [144]:
import pandas as pd
import numpy as np
import re

## 2. Clinical Trial Dataset Import
Let's import the Excel dataset.

The dataset is stored in an Excel file and contains the clinical trial measurements that we will clean and validate in preparation for statistical analysis.

In [145]:
df = pd.read_excel("Data.xlsx")

In [146]:
df.head()

,Treatment,ID,Time,Group,Gender,Phototype,Age,Tape striping on forearm,Tape striping on forearm.1,Tape striping on forearm.2,...,Metabolomics.127,Metabolomics.128,Metabolomics.129,Metabolomics.130,Metabolomics.131,Metabolomics.132,Metabolomics.133,Metabolomics.134,Metabolomics.135,Metabolomics.136
0,Treatment,ID,Time,Group,Gender,Phototype,Age,Alanin,Arginine,Asparagine,...,Ser-Leu-Tyr,Succinic acid,Tetradecanedioic acid,Theophylline,UKOUEEGEHXWHHO-MOFOKWOHSA-N,Undecylenic acid,Uric acid,Uridine,Xanthine,β-Muricholic acid
1,P,101,0,P,1,2,57,294.324357,162.804972,123.093471,...,39668.056,35937221.63,2158096.887,10442046.75,1104819.478,2640774.704,1576279536,9482303.441,7189051.084,69097.41478
2,P,106,0,P,1,2,57,NaN,NaN,NaN,...,34841.32158,28258247.52,9611555.013,22247055.68,1215212.136,2463671.736,1347189090,8784609.248,5360869.54,108788.7305
3,P,111,0,P,1,2,55,420.792795,176.925428,135.474507,...,196565.0648,15589087.99,7125148.718,76887477.94,1321071.949,5008210.167,1419687963,8324165.623,7294962.786,249733.6906
4,P,112,0,P,0,2,34,123.192424,101.040074,78.653531,...,33642.60599,16529940.14,5404199.556,7911626.084,1264210.53,1733370.449,1273509008,6601074.128,4368368.466,319054.0253

## 3. Excel Header Structure
Because the Excel file has a special two-row header, we will use the following code to remove the first header row.

In [147]:
# Import the Excel file without assigning a header
df_raw = pd.read_excel("Data.xlsx", header=None)

# Keep the second row as the actual variable names
column_names = df_raw.iloc[1].astype(str).str.strip()

# Remove both header rows and keep participant data
df = df_raw.iloc[2:].copy()

# Assign the actual variable names
df.columns = column_names

# Reset the index
df.reset_index(drop=True, inplace=True)

In [148]:
df

1,Treatment,ID,Time,Group,Gender,Phototype,Age,Alanin,Arginine,Asparagine,...,Ser-Leu-Tyr,Succinic acid,Tetradecanedioic acid,Theophylline,UKOUEEGEHXWHHO-MOFOKWOHSA-N,Undecylenic acid,Uric acid,Uridine,Xanthine,β-Muricholic acid
0,P,101,0,P,1,2,57,294.324357,162.804972,123.093471,...,39668.056,35937221.63,2158096.887,10442046.75,1104819.478,2640774.704,1576279536,9482303.441,7189051.084,69097.41478
1,P,106,0,P,1,2,57,NaN,NaN,NaN,...,34841.32158,28258247.52,9611555.013,22247055.68,1215212.136,2463671.736,1347189090,8784609.248,5360869.54,108788.7305
2,P,111,0,P,1,2,55,420.792795,176.925428,135.474507,...,196565.0648,15589087.99,7125148.718,76887477.94,1321071.949,5008210.167,1419687963,8324165.623,7294962.786,249733.6906
3,P,112,0,P,0,2,34,123.192424,101.040074,78.653531,...,33642.60599,16529940.14,5404199.556,7911626.084,1264210.53,1733370.449,1273509008,6601074.128,4368368.466,319054.0253
4,P,115,0,P,1,2,55,746.432357,296.462256,135.077298,...,36618.51639,21320749.14,10014310.77,10241510.62,1171966.148,2094599.986,1417415339,10460547.49,5089322.633,59313.78452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,SH60,086,3,SH60,1,2,40,974.120029,664.074258,138.375816,...,35638.6771,22193594.8,9197246.836,32680226.06,1314132.068,2244328.694,1493969075,8578520.07,7155655.166,110894.7083
292,SH60,087,3,SH60,1,2,58,757.310033,403.814963,162.393462,...,44968.0063,17369847.28,12691319.45,19640040.01,1110520.467,2667572.029,1371017431,10474332.88,6225830.879,34839.68278
293,SH60,092,3,SH60,1,2,37,290.541669,118.091931,136.974283,...,32455.35633,25104410.89,10101684.01,14397096.13,1078254.466,1946506.172,1162166310,9071441.04,5456207.725,28487.80866
294,SH60,095,3,SH60,1,2,41,739.514726,599.760443,152.682426,...,34747.50491,27410119.47,12104849.26,24180209.48,41616.50814,1264598.774,1411163519,10043576.74,6790084.64,16382.93961
295,SH60,098,3,SH60,1,2,33,637.875669,384.868463,120.289279,...,35429.57373,19930332.84,9151256.954,30786105.74,1252594.878,1356415.869,1276561754,7585431.397,5623646.283,239134.6562

## 3. Data Cleaning: Preparation and Recoding

The clinical trial dataset was provided as an already cleaned dataset from the source.

No changes were made to the original clinical measurements or participant data.

Only a few minor recoding and formatting modifications were performed to improve readability and facilitate the statistical analysis:

- `P` was recoded to `Placebo` in the Treatment and Group variables.
- Gender coding was converted from `0` = Male and `1` = Female to descriptive labels.
- The Excel header structure was adjusted so that the appropriate variable names could be used in Python.

In [149]:
df["Treatment"] = df["Treatment"].replace("P", "Placebo")
df["Group"] = df["Group"].replace("P", "Placebo")
df["Gender"] = df["Gender"].replace({
    0: "Male",
    1: "Female"
})

Let's check that the recoding worked

In [150]:
print("Treatment groups:")
print(df["Treatment"].value_counts())

print("Groups:")
print(df["Group"].value_counts())

print("\nGender groups:")
print(df["Gender"].value_counts())

Treatment groups:
Treatment
Placebo    100
SH120      100
SH60        96
Name: count, dtype: int64
Groups:
Group
Placebo    100
SH120      100
SH60        96
Name: count, dtype: int64

Gender groups:
Gender
Female    190
Male      106
Name: count, dtype: int64

# The dataset contains two variables, Treatment and Group, which represent the treatment-group information.

After reviewing the variables, Treatment was selected as the main treatment variable because its labels provide a clearer description of the clinical trial groups:

- Placebo
- SH60
- SH120
  
The "Group" column is removed from the analysis dataframe to avoid duplicate information and make the dataset easier to work with.

In [151]:
df = df.drop(columns=["Group"])

In [152]:
df.head()

1,Treatment,ID,Time,Gender,Phototype,Age,Alanin,Arginine,Asparagine,Citruline,...,Ser-Leu-Tyr,Succinic acid,Tetradecanedioic acid,Theophylline,UKOUEEGEHXWHHO-MOFOKWOHSA-N,Undecylenic acid,Uric acid,Uridine,Xanthine,β-Muricholic acid
0,Placebo,101,0,Female,2,57,294.324357,162.804972,123.093471,381.268324,...,39668.056,35937221.63,2158096.887,10442046.75,1104819.478,2640774.704,1576279536,9482303.441,7189051.084,69097.41478
1,Placebo,106,0,Female,2,57,NaN,NaN,NaN,NaN,...,34841.32158,28258247.52,9611555.013,22247055.68,1215212.136,2463671.736,1347189090,8784609.248,5360869.54,108788.7305
2,Placebo,111,0,Female,2,55,420.792795,176.925428,135.474507,704.724983,...,196565.0648,15589087.99,7125148.718,76887477.94,1321071.949,5008210.167,1419687963,8324165.623,7294962.786,249733.6906
3,Placebo,112,0,Male,2,34,123.192424,101.040074,78.653531,163.563132,...,33642.60599,16529940.14,5404199.556,7911626.084,1264210.53,1733370.449,1273509008,6601074.128,4368368.466,319054.0253
4,Placebo,115,0,Female,2,55,746.432357,296.462256,135.077298,823.266482,...,36618.51639,21320749.14,10014310.77,10241510.62,1171966.148,2094599.986,1417415339,10460547.49,5089322.633,59313.78452

### Let's inspect column names.

In [153]:
print(", ".join(df.columns))

Treatment, ID, Time, Gender, Phototype, Age, Alanin, Arginine, Asparagine, Citruline, Fenylalanin, Glutamic acid, glutamin, Glycine, histidin, Isoleucine, kys. asparagova, Leucine, lysin, Methionine, Ornithine, Proline, Pyrrolidone carboxylic acid, Serine, Threonine, Tryptofan, tyrosine, Urea, valin, NMF, Total urocanic acid, trans-Urocanic acid, Hydratation-forehead, Hydratation-cheek, Hydratation-forearm, TEWL-forehead, TEWL-Cheek, Sebum-forehead, Sebum-cheek, Wrinkle, Red-Area-forehead, Red-Area-cheek, Pores-Area-forehead, Pores-Area-cheek, GLOSS-forehead, GLOSS-Cheek, GLOSS-DCS-forehead, GLOSS-DCS-cheek, MEXA Melanin-forehead, MEXA Melanin-cheek, MEXA Erythema-forehead, MEXA Erythema-cheek, ITA-forehead, ITA-cheek, a value-forehead, a value-cheek, b value-forehead, b value-cheek, Elasticity R0-forehead, Elasticity R0-cheek, Elasticity R1-forehead, Elasticity R1-cheek, Elasticity R2-forehead, Elasticity R2-cheek, Elasticity R3-forehead, Elasticity R3-cheek, Elasticity R4 - forehead, Elasticity R4 - cheek, Elasticity R5 - forehead, Elasticity R5 - cheek, Elasticity R6 - forehead, Elasticity R6 -cheek, Elasticity R7-forehead, Elasticity R7-cheek, Elasticity R8 - forehead, Elasticity R8 -cheek, Elasticity R9-forehead, Elasticity R9-cheek, Elasticity F0-forehead, Elasticity F0-cheek, Elasticity F1-forehead, Elasticity F1-cheek, Elasticity R1 R4-forehead, Elasticity R1 R4-cheek, Elasticity R3 R9-forehead, Elasticity R3 R9-cheek, Epidermal thickness, Dermal density, CAR 12:0, CAR 12:1, CAR 12:2, CAR 13:0, CAR 14:1, CAR 14:2, CAR 14:3, CAR 16:0, CAR 16:1, CAR 16:2, CAR 16:3, CAR 18:1, CAR 18:2, CAR 18:3, CAR 20:1, CAR 20:2, CAR 22:0, CAR 24:1, CAR 26:0, CE 16:1, CE 17:0, CE 18:1, CE 18:2, CE 18:3, CE 20:3, CE 20:4, CE 20:5, CE 22:6, Cer 34:1 NS - neg, Cer 38:1 ;2O, Cer 38:1 NS - neg, Cer 40:0 ;2O, Cer 40:0 ;2O -neg, Cer 40:1 ;2O, Cer 40:1 NS - neg, Cer 40:2 ;2O, Cer 40:2 NS - neg, Cer 41:0 ;2O, Cer 41:1 ;2O, Cer 41:1 NS - neg, Cer 41:2 ;2O, Cer 42:0 ;2O, Cer 42:0 ;2O - neg, Cer 42:1 ;2O - neg, Cer 42:1 ;2O (1), Cer 42:1 ;2O (2), Cer 42:2 ;2O, Cer 42:2 NS - neg, Cer 42:3 ;2O, Cer 42:3 ;2O - neg, Cer 43:1 ;2O, Cer 43:1 ;2O - neg, Cer 43:2 ;2O, Cer 44:1 ;2O - neg, DG 36:2, FA 14:0, FA 14:1, FA 16:0, FA 16:1, FA 16:3, FA 18:1, FA 18:2, FA 18:3, FA 19:1, FA 20:1, FA 20:2, FA 20:3, FA 20:4, FA 20:5, FA 22:1, FA 22:2, FA 22:3, FA 22:4, FA 22:5, FA 22:6, FA 24:1, FA 24:2, FA 24:4, FA 24:5, FA 26:3, FA 34:0, FAHFA 24:3, FAHFA 36:1, FAHFA 38:2, FAHFA 38:4, FAHFA 40:3, FAHFA 40:4, FC, GM3 32:1 ;2O - neg, GM3 40:1 ;2O - neg, GM3 42:1 ;2O - neg, GM3 42:2 ;2O - neg, Hex2Cer 34:1 ;2O - neg, Hex3Cer 34:1 ;2O, Hex3Cer 40:1 ;2O, HexCer 34:0 ;3O;(2OH) - neg, HexCer 34:1 ;2O  - neg, HexCer 36:1 ;2O  - neg, HexCer 38:1 ;2O  - neg, HexCer 40:1 ;2O, HexCer 40:1 ;2O  - neg, HexCer 40:2 ;2O  - neg, HexCer 41:1 ;2O  - neg, HexCer 41:2 ;2O  - neg, HexCer 42:1 ;2O, HexCer 42:1 ;2O  - neg, HexCer 42:2 ;2O  - neg, HexCer 42:3 ;2O  - neg, LNAPE 36:4, LPC 12:0, LPC 14:1, LPC 16:1, LPC 16:2, LPC 17:0, LPC 17:1, LPC 18:0, LPC 18:1, LPC 18:2, LPC 19:0, LPC 19:1, LPC 20:0, LPC 20:1, LPC 20:2, LPC 20:3, LPC 20:4, LPC 22:0, LPC 22:1, LPC 22:3, LPC 22:5, LPC 22:6, LPC 24:0, LPC 24:5, LPC 26:1, LPC-O 16:0, LPC-O 16:1, LPC-O 17:0, LPC-O 18:1, LPC-O 20:0, LPC-O 22:1, LPC-O 26:2, LPE 16:0, LPE 18:0, LPE 18:1, LPE 20:3, LPE 20:5, LPE 22:5, LPE 22:6, LPE-O 16:1, LPE-O 18:2, LPI 18:0, LPI 18:2, LPI 20:3, LPI 20:4, PC 24:0, PC 26:0, PC 28:0, PC 28:1, PC 30:0, PC 30:1, PC 31:1, PC 31:2, PC 32:0, PC 32:1, PC 32:2, PC 32:3, PC 33:0, PC 33:1, PC 33:2, PC 33:4, PC 34:2, PC 34:3, PC 34:4, PC 34:5, PC 35:0, PC 35:1, PC 35:2, PC 35:3, PC 35:4, PC 35:5, PC 36:0, PC 36:1, PC 36:2, PC 36:3, PC 36:4, PC 36:5, PC 36:6, PC 36:7, PC 37:2, PC 37:4, PC 37:5, PC 37:6, PC 37:7, PC 38:1, PC 38:2, PC 38:3, PC 38:5, PC 38:6, PC 38:7, PC 38:8, PC 38:9, PC 39:1, PC 39:3, PC 39:5, PC 39:6, PC 39:7, PC 40:1, PC 40:2, PC 40:3, PC 40:4, PC 40:5, PC 40:6, PC 40:7, PC 40:8, PC 40:9, PC 42:10, PC 42:5, PC 42:7, PC 44:4, PC 44:5, PC-O 30:0, PC-O 31:1, PC-O 32:0, PC-O 32:1, PC-O 33:2, PC-O 34:0, PC-O 34:1, PC-O 34:2, PC-O 34:3, PC-O 34:4, PC-O 35:4, PC-O 35:6, PC-O 35:7, PC-O 36:0, PC-O 36:2, PC-O 36:3, PC-O 36:4, PC-O 36:5, PC-O 36:6, PC-O 37:6, PC-O 37:7, PC-O 38:0, PC-O 38:4, PC-O 38:5, PC-O 38:6, PC-O 38:7, PC-O 39:6, PC-O 40:2, PC-O 40:3, PC-O 40:5, PC-O 40:6, PC-O 40:7, PC-O 42:1, PC-O 42:2, PC-O 42:3, PC-O 42:4, PC-O 42:5, PC-O 42:6, PC-O 44:5, PC-O 44:6, PC-O 44:7, PC-O 46:5, PC-O 46:6, PC-O 46:7, PC-O 46:8, PE 32:1, PE 34:1, PE 34:2, PE 34:3, PE 36:1, PE 36:2, PE 36:3, PE 36:4, PE 38:4, PE 38:6, PE-O 34:2, PE-O 34:3, PE-O 36:2, PE-O 36:3, PE-O 36:4, PE-O 36:5, PE-O 36:6, PE-O 36:7, PE-O 37:5, PE-O 37:6, PE-O 38:2, PE-O 38:3, PE-O 38:4, PE-O 38:5, PE-O 38:6, PE-O 38:7, PE-O 39:6, PE-O 39:7, PE-O 40:7, PE-O 40:8, PE-O 40:9, PE-O 42:7, PE-O 42:8, PG 34:2, PG 36:2, PI 32:1, PI 34:1, PI 36:1, PI 36:2, PI 36:4, PI 37:4, PI 38:2, PI 38:3, PI 38:4, PI 40:5, PI 40:6, SM 29:1 ;2O, SM 30:0 ;2O, SM 30:1 ;2O (1), SM 30:1 ;2O (2), SM 31:1 ;2O, SM 32:0 ;2O, SM 32:1 ;2O, SM 32:2 ;2O (1), SM 32:2 ;2O (2), SM 33:1 ;2O (1), SM 33:1 ;2O (2), SM 33:2 ;2O, SM 34:0 ;2O, SM 34:1 ;2O (1), SM 34:1 ;3O (2), SM 34:2 ;2O (1), SM 34:2 ;2O (2), SM 34:3 ;2O, SM 35:1 ;2O, SM 36:0 ;2O, SM 36:2 ;2O, SM 36:3 ;2O, SM 37:1 ;2O, SM 38:0 ;2O, SM 38:1 ;2O (1), SM 38:1 ;2O (2), SM 38:2 ;2O, SM 38:3 ;2O, SM 38:4 ;2O, SM 39:0 ;2O, SM 39:1 ;2O (1), SM 39:1 ;2O (2), SM 39:1 ;2O (3), SM 39:2 ;2O, SM 40:0 ;2O, SM 40:1 ;2O (1), SM 40:1 ;2O (2), SM 40:2 ;2O (1), SM 40:2 ;2O (2), SM 40:3 ;2O, SM 41:0 ;2O, SM 41:1 ;2O (1), SM 41:1 ;2O (2), SM 41:1 ;2O (3), SM 41:2 ;2O (1), SM 41:2 ;2O (2), SM 42:1 ;2O (1), SM 42:1 ;2O (2), SM 42:2 ;2O (1), SM 42:2 ;2O (2), SM 42:2 ;2O (3), SM 42:3 ;2O, SM 42:4 ;2O, SM 42:5 ;2O, SM 43:1 ;2O (1), SM 43:1 ;2O (2), SM 43:2 ;2O (1), SM 43:2 ;2O (2), SM 43:2 ;2O (3), SM 43:3 ;2O, SM 44:1 ;2O, SM 44:2 ;2O, SM 44:3 ;2O, TG 34:0, TG 36:0, TG 40:0, TG 42:0, TG 42:1, TG 42:2 (1), TG 42:2 (2), TG 44:0, TG 44:1 (1), TG 44:1 (2), TG 44:2 (1), TG 44:2 (2), TG 44:3, TG 45:1, TG 45:2, TG 46:0, TG 46:1, TG 46:2, TG 46:3 (1), TG 46:3 (2), TG 46:3 (3), TG 47:1, TG 47:2, TG 47:3, TG 48:1, TG 48:2, TG 48:3 (1), TG 48:3 (2), TG 48:3 (3), TG 48:4, TG 48:5, TG 49:0, TG 49:1, TG 49:2, TG 49:3, TG 49:4, TG 49:5, TG 50:0, TG 50:1, TG 50:1, TG 50:2, TG 50:3, TG 50:4 (1), TG 50:4 (2), TG 50:5, TG 50:6, TG 51:0, TG 51:1, TG 51:2, TG 51:3, TG 51:4, TG 52:1, TG 52:2, TG 52:3, TG 52:4 (1), TG 52:4 (2), TG 52:5 (1), TG 52:5 (2), TG 52:6 (1), TG 52:6 (2), TG 52:7, TG 53:1, TG 53:2, TG 53:3 (1), TG 53:3 (2), TG 53:4, TG 53:5, TG 54:1, TG 54:2 (1), TG 54:2 (2), TG 54:3, TG 54:4, TG 54:5, TG 54:6, TG 54:7, TG 54:8, TG 55:2 (1), TG 55:2 (2), TG 55:3, TG 55:4, TG 55:6, TG 55:7, TG 56:1 (1), TG 56:1 (2), TG 56:10, TG 56:2 (1), TG 56:2 (2), TG 56:3 (1), TG 56:3 (2), TG 56:4 (1), TG 56:4 (2), TG 56:5 (1), TG 56:5 (2), TG 56:6, TG 56:7, TG 56:8, TG 56:9 (1), TG 56:9 (2), TG 57:11, TG 57:2, TG 57:3, TG 57:4, TG 57:6, TG 57:8, TG 58:1, TG 58:10, TG 58:11, TG 58:12, TG 58:2, TG 58:3, TG 58:4, TG 58:5, TG 58:6, TG 58:7, TG 58:8, TG 58:9 (1), TG 58:9 (2), TG 59:11, TG 59:12, TG 59:2, TG 59:3, TG 60:1, TG 60:10, TG 60:11, TG 60:12, TG 60:13, TG 60:2, TG 60:3 (1), TG 60:3 (2), TG 60:4, TG 60:5, TG 60:6, TG 60:7, TG 60:8, TG 60:9, TG 61:1, TG 61:2, TG 61:3, TG 61:4, TG 62:1, TG 62:11, TG 62:12, TG 62:13 (1), TG 62:13 (2), TG 62:14, TG 62:2, TG 62:3, TG 62:4 (1), TG 62:4 (2), TG 62:5, TG 63:2, TG 64:1, TG 64:2, TG 64:4, TG 66:3, TG-O 50:1, TG-O 52:1, TG-O 52:2, TG-O 58:3, MDA, 12,13-diHOME, 13-HODE, 9-HODE, 5-HETE, EPA, DHA, Arachidonic acid, CRP, fetuin A, adipsin, GLP1 total, glucagon, TNFa, EGF, FGF2, IFNg, IL1b, IL1RA, IL10, IL17A, C peptide, IL6, leptin, MCP1, (+/-)14(15)-DiHET, (4E,6E)-2,7-dimethyl-8-[(2R,3R,4S,5S,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxyocta-4,6-dienoic acid, (4E,7E)-dodeca-4,7-dienedioic acid, (E)-6-hydroxyoctadec-4-enoic acid, (Z)-3-hydroxydodec-5-enoic acid, 1,16-Hexadecanedioic acid, 1,3-Dimethyluric acid, 1,7-Dimethyluric acid, 10-HDA, 16-Hydroxyhexadecanoic acid, 1-Methyluric acid, 1-Methylxanthine, 2-(4-Hydroxyphenyl)propanoic acid, 2-(ALPHA-D-MANNOPYRANOSYL)-L-TRYPTOPHAN, 2,4-Dinitrophenol, 2,5-Dihydroxybenzenesulfonic Acid, 2,6-Dihydroxybenzoic acid, 2-Furoic acid, 2-Furoylglycine, 2-Hydroxyhippuric acid, 2-Hydroxyisobutyric acid, 2-Hydroxyisobutyric acid, 2-Methyl-4,6-dinitrophenol, 3-(1-Pyrazolyl)-alanine, 3-Allyl-2-hydroxybenzoic acid, 3-FUROIC ACID, 3-Hydroxybutyric acid, 3-Hydroxydecanoic acid, 3-Indoxyl sulphate, 3-Indoxyl sulphate, 3-Methoxysalicylic acid, 3-Methoxytyrosine, 3-Methyl-2-oxovaleric acid calcium salt, 3-Methylxanthine, 3-Phenyllactic acid, 4-Acetamidobutanoic acid, 4-Hydroxy-3- methoxyphenylglycol sulfate, 4-Hydroxy-3-oxo-4-propan-2-ylcyclohexene-1-carboxylic acid, 4-Hydroxyhippuric acid sulfate, 4-Chlorophenoxyacetic acid, 4-Methoxymelilotic acid, 4-Methylphenol, 4-Oxoproline, 4-Phenolsulfonic acid, 4-Pyridoxic acid, 5-Aminolevulinic acid, Acetaminophen glucuronide, Adenosine 3'5'-cyclic monophosphate, Adenosine 5'-monophosphate, beta-D-N-Acetylmannosamine, Catechol, Citric acid, Citrulline, CMPF, CMPF, D-(-)-Glutamine, D-(+)-Tryptophan, Decanoic acid, Deoxycholic acid, D-Glucose, DL-4-Hydroxyphenyllactic acid, DL-Arginine, DL-Lactic Acid, Dodecanedioic acid, D-Panthenol, D-Pantothenic acid, D-Threonine, Epinephrine, Erdosteine, Gluconic acid, Glu-Leu, Glu-Leu-Ser, Glu-Phe, Glu-Pro, Glu-Tyr, Glu-Val, Glycine, Glycochenodeoxycholic acid, Glycochenodeoxycholic acid, Glycochenodeoxycholic acid, Glycocholic acid, Hippuric acid, His-His, Hydrocortisone, Hypoxanthine, Cholic Acid, Ibuprofen metabolite B, Ile-Glu, Indole-3-acrylic acid, Indole-3-lactic acid, Indole-3-lactic acid, Inosine, isocitric acid, Kynurenic acid, L-(-)-Malic acid, L-(+)-Lactic acid, L-Ascorbic acid 2-sulfate, L-Histidine, L-isoleucine, L-Ornithine, LPE 16:0, LPE 18:1, LPE 22:6, L-Tyrosine, Met-Glu, methyl 4-cyano-3-[2-(1-cyano-2-ethoxy-2-oxoethylidene)hydrazino]thiophene-2-carboxylate, N4-Acetylcytidine, N6-Succinyladenosine; LC-tDDA; CE20, N-Acetyl carnosine, N-Acetylalanine, N-Acetyl-L-aspartic acid, N-Acetyl-L-methionine, N-Acetyl-L-phenylalanine, N-Acetyl-threonine; LC-tDDA; CE10, N-Formylmethionine, Nimesulide, N-Isovalerylglycine, Perfluoro-1-butanesulfonic acid (PFBS), Phe-Lys-Tyr, Phenol, Phenylacetylglutamine, P-hydroxybenzoic acid, p-Hydroxyphenylacetic acid, Pyruvic acid, Saccharin, Salicyluric acid, Ser-Glu, Ser-Leu-Tyr, Succinic acid, Tetradecanedioic acid, Theophylline, UKOUEEGEHXWHHO-MOFOKWOHSA-N, Undecylenic acid, Uric acid, Uridine, Xanthine, β-Muricholic acid


#### The dataset contains a large number of variables that need to be standardized to improve readability and ensure compatibility with SQL and Python conventions. This includes removing unnecessary spaces and special characters and using consistent naming conventions. Let's start with:

- Start column names with a capital letter.
- Replace spaces with _.
- Rename ID → Participant_ID.
- Rename Time → Measurement_Time.
- Rename Kys. Asparagova → Aspartic_Acid.

In [154]:
# Replace spaces with underscores
df.columns = df.columns.str.replace(" ", "_")

# Rename selected columns
df = df.rename(columns={
    "ID": "Participant_ID",
    "Time": "Measurement_Time",
    "kys._asparagova": "Aspartic_Acid"
})

# Start column names with an uppercase letter
df.columns = [col[0].upper() + col[1:] for col in df.columns]

In [155]:
print(", ".join(df.columns))

Treatment, Participant_ID, Measurement_Time, Gender, Phototype, Age, Alanin, Arginine, Asparagine, Citruline, Fenylalanin, Glutamic_acid, Glutamin, Glycine, Histidin, Isoleucine, Aspartic_Acid, Leucine, Lysin, Methionine, Ornithine, Proline, Pyrrolidone_carboxylic_acid, Serine, Threonine, Tryptofan, Tyrosine, Urea, Valin, NMF, Total_urocanic_acid, Trans-Urocanic_acid, Hydratation-forehead, Hydratation-cheek, Hydratation-forearm, TEWL-forehead, TEWL-Cheek, Sebum-forehead, Sebum-cheek, Wrinkle, Red-Area-forehead, Red-Area-cheek, Pores-Area-forehead, Pores-Area-cheek, GLOSS-forehead, GLOSS-Cheek, GLOSS-DCS-forehead, GLOSS-DCS-cheek, MEXA_Melanin-forehead, MEXA_Melanin-cheek, MEXA_Erythema-forehead, MEXA_Erythema-cheek, ITA-forehead, ITA-cheek, A_value-forehead, A_value-cheek, B_value-forehead, B_value-cheek, Elasticity_R0-forehead, Elasticity_R0-cheek, Elasticity_R1-forehead, Elasticity_R1-cheek, Elasticity_R2-forehead, Elasticity_R2-cheek, Elasticity_R3-forehead, Elasticity_R3-cheek, Elasticity_R4_-_forehead, Elasticity_R4_-_cheek, Elasticity_R5_-_forehead, Elasticity_R5_-_cheek, Elasticity_R6_-_forehead, Elasticity_R6_-cheek, Elasticity_R7-forehead, Elasticity_R7-cheek, Elasticity_R8_-_forehead, Elasticity_R8_-cheek, Elasticity_R9-forehead, Elasticity_R9-cheek, Elasticity_F0-forehead, Elasticity_F0-cheek, Elasticity_F1-forehead, Elasticity_F1-cheek, Elasticity_R1_R4-forehead, Elasticity_R1_R4-cheek, Elasticity_R3_R9-forehead, Elasticity_R3_R9-cheek, Epidermal_thickness, Dermal_density, CAR_12:0, CAR_12:1, CAR_12:2, CAR_13:0, CAR_14:1, CAR_14:2, CAR_14:3, CAR_16:0, CAR_16:1, CAR_16:2, CAR_16:3, CAR_18:1, CAR_18:2, CAR_18:3, CAR_20:1, CAR_20:2, CAR_22:0, CAR_24:1, CAR_26:0, CE_16:1, CE_17:0, CE_18:1, CE_18:2, CE_18:3, CE_20:3, CE_20:4, CE_20:5, CE_22:6, Cer_34:1_NS_-_neg, Cer_38:1_;2O, Cer_38:1_NS_-_neg, Cer_40:0_;2O, Cer_40:0_;2O_-neg, Cer_40:1_;2O, Cer_40:1_NS_-_neg, Cer_40:2_;2O, Cer_40:2_NS_-_neg, Cer_41:0_;2O, Cer_41:1_;2O, Cer_41:1_NS_-_neg, Cer_41:2_;2O, Cer_42:0_;2O, Cer_42:0_;2O_-_neg, Cer_42:1_;2O_-_neg, Cer_42:1_;2O_(1), Cer_42:1_;2O_(2), Cer_42:2_;2O, Cer_42:2_NS_-_neg, Cer_42:3_;2O, Cer_42:3_;2O_-_neg, Cer_43:1_;2O, Cer_43:1_;2O_-_neg, Cer_43:2_;2O, Cer_44:1_;2O_-_neg, DG_36:2, FA_14:0, FA_14:1, FA_16:0, FA_16:1, FA_16:3, FA_18:1, FA_18:2, FA_18:3, FA_19:1, FA_20:1, FA_20:2, FA_20:3, FA_20:4, FA_20:5, FA_22:1, FA_22:2, FA_22:3, FA_22:4, FA_22:5, FA_22:6, FA_24:1, FA_24:2, FA_24:4, FA_24:5, FA_26:3, FA_34:0, FAHFA_24:3, FAHFA_36:1, FAHFA_38:2, FAHFA_38:4, FAHFA_40:3, FAHFA_40:4, FC, GM3_32:1_;2O_-_neg, GM3_40:1_;2O_-_neg, GM3_42:1_;2O_-_neg, GM3_42:2_;2O_-_neg, Hex2Cer_34:1_;2O_-_neg, Hex3Cer_34:1_;2O, Hex3Cer_40:1_;2O, HexCer_34:0_;3O;(2OH)_-_neg, HexCer_34:1_;2O__-_neg, HexCer_36:1_;2O__-_neg, HexCer_38:1_;2O__-_neg, HexCer_40:1_;2O, HexCer_40:1_;2O__-_neg, HexCer_40:2_;2O__-_neg, HexCer_41:1_;2O__-_neg, HexCer_41:2_;2O__-_neg, HexCer_42:1_;2O, HexCer_42:1_;2O__-_neg, HexCer_42:2_;2O__-_neg, HexCer_42:3_;2O__-_neg, LNAPE_36:4, LPC_12:0, LPC_14:1, LPC_16:1, LPC_16:2, LPC_17:0, LPC_17:1, LPC_18:0, LPC_18:1, LPC_18:2, LPC_19:0, LPC_19:1, LPC_20:0, LPC_20:1, LPC_20:2, LPC_20:3, LPC_20:4, LPC_22:0, LPC_22:1, LPC_22:3, LPC_22:5, LPC_22:6, LPC_24:0, LPC_24:5, LPC_26:1, LPC-O_16:0, LPC-O_16:1, LPC-O_17:0, LPC-O_18:1, LPC-O_20:0, LPC-O_22:1, LPC-O_26:2, LPE_16:0, LPE_18:0, LPE_18:1, LPE_20:3, LPE_20:5, LPE_22:5, LPE_22:6, LPE-O_16:1, LPE-O_18:2, LPI_18:0, LPI_18:2, LPI_20:3, LPI_20:4, PC_24:0, PC_26:0, PC_28:0, PC_28:1, PC_30:0, PC_30:1, PC_31:1, PC_31:2, PC_32:0, PC_32:1, PC_32:2, PC_32:3, PC_33:0, PC_33:1, PC_33:2, PC_33:4, PC_34:2, PC_34:3, PC_34:4, PC_34:5, PC_35:0, PC_35:1, PC_35:2, PC_35:3, PC_35:4, PC_35:5, PC_36:0, PC_36:1, PC_36:2, PC_36:3, PC_36:4, PC_36:5, PC_36:6, PC_36:7, PC_37:2, PC_37:4, PC_37:5, PC_37:6, PC_37:7, PC_38:1, PC_38:2, PC_38:3, PC_38:5, PC_38:6, PC_38:7, PC_38:8, PC_38:9, PC_39:1, PC_39:3, PC_39:5, PC_39:6, PC_39:7, PC_40:1, PC_40:2, PC_40:3, PC_40:4, PC_40:5, PC_40:6, PC_40:7, PC_40:8, PC_40:9, PC_42:10, PC_42:5, PC_42:7, PC_44:4, PC_44:5, PC-O_30:0, PC-O_31:1, PC-O_32:0, PC-O_32:1, PC-O_33:2, PC-O_34:0, PC-O_34:1, PC-O_34:2, PC-O_34:3, PC-O_34:4, PC-O_35:4, PC-O_35:6, PC-O_35:7, PC-O_36:0, PC-O_36:2, PC-O_36:3, PC-O_36:4, PC-O_36:5, PC-O_36:6, PC-O_37:6, PC-O_37:7, PC-O_38:0, PC-O_38:4, PC-O_38:5, PC-O_38:6, PC-O_38:7, PC-O_39:6, PC-O_40:2, PC-O_40:3, PC-O_40:5, PC-O_40:6, PC-O_40:7, PC-O_42:1, PC-O_42:2, PC-O_42:3, PC-O_42:4, PC-O_42:5, PC-O_42:6, PC-O_44:5, PC-O_44:6, PC-O_44:7, PC-O_46:5, PC-O_46:6, PC-O_46:7, PC-O_46:8, PE_32:1, PE_34:1, PE_34:2, PE_34:3, PE_36:1, PE_36:2, PE_36:3, PE_36:4, PE_38:4, PE_38:6, PE-O_34:2, PE-O_34:3, PE-O_36:2, PE-O_36:3, PE-O_36:4, PE-O_36:5, PE-O_36:6, PE-O_36:7, PE-O_37:5, PE-O_37:6, PE-O_38:2, PE-O_38:3, PE-O_38:4, PE-O_38:5, PE-O_38:6, PE-O_38:7, PE-O_39:6, PE-O_39:7, PE-O_40:7, PE-O_40:8, PE-O_40:9, PE-O_42:7, PE-O_42:8, PG_34:2, PG_36:2, PI_32:1, PI_34:1, PI_36:1, PI_36:2, PI_36:4, PI_37:4, PI_38:2, PI_38:3, PI_38:4, PI_40:5, PI_40:6, SM_29:1_;2O, SM_30:0_;2O, SM_30:1_;2O_(1), SM_30:1_;2O_(2), SM_31:1_;2O, SM_32:0_;2O, SM_32:1_;2O, SM_32:2_;2O_(1), SM_32:2_;2O_(2), SM_33:1_;2O_(1), SM_33:1_;2O_(2), SM_33:2_;2O, SM_34:0_;2O, SM_34:1_;2O_(1), SM_34:1_;3O_(2), SM_34:2_;2O_(1), SM_34:2_;2O_(2), SM_34:3_;2O, SM_35:1_;2O, SM_36:0_;2O, SM_36:2_;2O, SM_36:3_;2O, SM_37:1_;2O, SM_38:0_;2O, SM_38:1_;2O_(1), SM_38:1_;2O_(2), SM_38:2_;2O, SM_38:3_;2O, SM_38:4_;2O, SM_39:0_;2O, SM_39:1_;2O_(1), SM_39:1_;2O_(2), SM_39:1_;2O_(3), SM_39:2_;2O, SM_40:0_;2O, SM_40:1_;2O_(1), SM_40:1_;2O_(2), SM_40:2_;2O_(1), SM_40:2_;2O_(2), SM_40:3_;2O, SM_41:0_;2O, SM_41:1_;2O_(1), SM_41:1_;2O_(2), SM_41:1_;2O_(3), SM_41:2_;2O_(1), SM_41:2_;2O_(2), SM_42:1_;2O_(1), SM_42:1_;2O_(2), SM_42:2_;2O_(1), SM_42:2_;2O_(2), SM_42:2_;2O_(3), SM_42:3_;2O, SM_42:4_;2O, SM_42:5_;2O, SM_43:1_;2O_(1), SM_43:1_;2O_(2), SM_43:2_;2O_(1), SM_43:2_;2O_(2), SM_43:2_;2O_(3), SM_43:3_;2O, SM_44:1_;2O, SM_44:2_;2O, SM_44:3_;2O, TG_34:0, TG_36:0, TG_40:0, TG_42:0, TG_42:1, TG_42:2_(1), TG_42:2_(2), TG_44:0, TG_44:1_(1), TG_44:1_(2), TG_44:2_(1), TG_44:2_(2), TG_44:3, TG_45:1, TG_45:2, TG_46:0, TG_46:1, TG_46:2, TG_46:3_(1), TG_46:3_(2), TG_46:3_(3), TG_47:1, TG_47:2, TG_47:3, TG_48:1, TG_48:2, TG_48:3_(1), TG_48:3_(2), TG_48:3_(3), TG_48:4, TG_48:5, TG_49:0, TG_49:1, TG_49:2, TG_49:3, TG_49:4, TG_49:5, TG_50:0, TG_50:1, TG_50:1, TG_50:2, TG_50:3, TG_50:4_(1), TG_50:4_(2), TG_50:5, TG_50:6, TG_51:0, TG_51:1, TG_51:2, TG_51:3, TG_51:4, TG_52:1, TG_52:2, TG_52:3, TG_52:4_(1), TG_52:4_(2), TG_52:5_(1), TG_52:5_(2), TG_52:6_(1), TG_52:6_(2), TG_52:7, TG_53:1, TG_53:2, TG_53:3_(1), TG_53:3_(2), TG_53:4, TG_53:5, TG_54:1, TG_54:2_(1), TG_54:2_(2), TG_54:3, TG_54:4, TG_54:5, TG_54:6, TG_54:7, TG_54:8, TG_55:2_(1), TG_55:2_(2), TG_55:3, TG_55:4, TG_55:6, TG_55:7, TG_56:1_(1), TG_56:1_(2), TG_56:10, TG_56:2_(1), TG_56:2_(2), TG_56:3_(1), TG_56:3_(2), TG_56:4_(1), TG_56:4_(2), TG_56:5_(1), TG_56:5_(2), TG_56:6, TG_56:7, TG_56:8, TG_56:9_(1), TG_56:9_(2), TG_57:11, TG_57:2, TG_57:3, TG_57:4, TG_57:6, TG_57:8, TG_58:1, TG_58:10, TG_58:11, TG_58:12, TG_58:2, TG_58:3, TG_58:4, TG_58:5, TG_58:6, TG_58:7, TG_58:8, TG_58:9_(1), TG_58:9_(2), TG_59:11, TG_59:12, TG_59:2, TG_59:3, TG_60:1, TG_60:10, TG_60:11, TG_60:12, TG_60:13, TG_60:2, TG_60:3_(1), TG_60:3_(2), TG_60:4, TG_60:5, TG_60:6, TG_60:7, TG_60:8, TG_60:9, TG_61:1, TG_61:2, TG_61:3, TG_61:4, TG_62:1, TG_62:11, TG_62:12, TG_62:13_(1), TG_62:13_(2), TG_62:14, TG_62:2, TG_62:3, TG_62:4_(1), TG_62:4_(2), TG_62:5, TG_63:2, TG_64:1, TG_64:2, TG_64:4, TG_66:3, TG-O_50:1, TG-O_52:1, TG-O_52:2, TG-O_58:3, MDA, 12,13-diHOME, 13-HODE, 9-HODE, 5-HETE, EPA, DHA, Arachidonic_acid, CRP, Fetuin_A, Adipsin, GLP1_total, Glucagon, TNFa, EGF, FGF2, IFNg, IL1b, IL1RA, IL10, IL17A, C_peptide, IL6, Leptin, MCP1, (+/-)14(15)-DiHET, (4E,6E)-2,7-dimethyl-8-[(2R,3R,4S,5S,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxyocta-4,6-dienoic_acid, (4E,7E)-dodeca-4,7-dienedioic_acid, (E)-6-hydroxyoctadec-4-enoic_acid, (Z)-3-hydroxydodec-5-enoic_acid, 1,16-Hexadecanedioic_acid, 1,3-Dimethyluric_acid, 1,7-Dimethyluric_acid, 10-HDA, 16-Hydroxyhexadecanoic_acid, 1-Methyluric_acid, 1-Methylxanthine, 2-(4-Hydroxyphenyl)propanoic_acid, 2-(ALPHA-D-MANNOPYRANOSYL)-L-TRYPTOPHAN, 2,4-Dinitrophenol, 2,5-Dihydroxybenzenesulfonic_Acid, 2,6-Dihydroxybenzoic_acid, 2-Furoic_acid, 2-Furoylglycine, 2-Hydroxyhippuric_acid, 2-Hydroxyisobutyric_acid, 2-Hydroxyisobutyric_acid, 2-Methyl-4,6-dinitrophenol, 3-(1-Pyrazolyl)-alanine, 3-Allyl-2-hydroxybenzoic_acid, 3-FUROIC_ACID, 3-Hydroxybutyric_acid, 3-Hydroxydecanoic_acid, 3-Indoxyl_sulphate, 3-Indoxyl_sulphate, 3-Methoxysalicylic_acid, 3-Methoxytyrosine, 3-Methyl-2-oxovaleric_acid_calcium_salt, 3-Methylxanthine, 3-Phenyllactic_acid, 4-Acetamidobutanoic_acid, 4-Hydroxy-3-_methoxyphenylglycol_sulfate, 4-Hydroxy-3-oxo-4-propan-2-ylcyclohexene-1-carboxylic_acid, 4-Hydroxyhippuric_acid_sulfate, 4-Chlorophenoxyacetic_acid, 4-Methoxymelilotic_acid, 4-Methylphenol, 4-Oxoproline, 4-Phenolsulfonic_acid, 4-Pyridoxic_acid, 5-Aminolevulinic_acid, Acetaminophen_glucuronide, Adenosine_3'5'-cyclic_monophosphate, Adenosine_5'-monophosphate, Beta-D-N-Acetylmannosamine, Catechol, Citric_acid, Citrulline, CMPF, CMPF, D-(-)-Glutamine, D-(+)-Tryptophan, Decanoic_acid, Deoxycholic_acid, D-Glucose, DL-4-Hydroxyphenyllactic_acid, DL-Arginine, DL-Lactic_Acid, Dodecanedioic_acid, D-Panthenol, D-Pantothenic_acid, D-Threonine, Epinephrine, Erdosteine, Gluconic_acid, Glu-Leu, Glu-Leu-Ser, Glu-Phe, Glu-Pro, Glu-Tyr, Glu-Val, Glycine, Glycochenodeoxycholic_acid, Glycochenodeoxycholic_acid, Glycochenodeoxycholic_acid, Glycocholic_acid, Hippuric_acid, His-His, Hydrocortisone, Hypoxanthine, Cholic_Acid, Ibuprofen_metabolite_B, Ile-Glu, Indole-3-acrylic_acid, Indole-3-lactic_acid, Indole-3-lactic_acid, Inosine, Isocitric_acid, Kynurenic_acid, L-(-)-Malic_acid, L-(+)-Lactic_acid, L-Ascorbic_acid_2-sulfate, L-Histidine, L-isoleucine, L-Ornithine, LPE_16:0, LPE_18:1, LPE_22:6, L-Tyrosine, Met-Glu, Methyl_4-cyano-3-[2-(1-cyano-2-ethoxy-2-oxoethylidene)hydrazino]thiophene-2-carboxylate, N4-Acetylcytidine, N6-Succinyladenosine;_LC-tDDA;_CE20, N-Acetyl_carnosine, N-Acetylalanine, N-Acetyl-L-aspartic_acid, N-Acetyl-L-methionine, N-Acetyl-L-phenylalanine, N-Acetyl-threonine;_LC-tDDA;_CE10, N-Formylmethionine, Nimesulide, N-Isovalerylglycine, Perfluoro-1-butanesulfonic_acid_(PFBS), Phe-Lys-Tyr, Phenol, Phenylacetylglutamine, P-hydroxybenzoic_acid, P-Hydroxyphenylacetic_acid, Pyruvic_acid, Saccharin, Salicyluric_acid, Ser-Glu, Ser-Leu-Tyr, Succinic_acid, Tetradecanedioic_acid, Theophylline, UKOUEEGEHXWHHO-MOFOKWOHSA-N, Undecylenic_acid, Uric_acid, Uridine, Xanthine, Β-Muricholic_acid

In [156]:
# Clinical measurement columns to standardize
clinical_columns = [
    "Trans-Urocanic_acid",
    "Hydratation-forehead", "Hydratation-cheek", "Hydratation-forearm",
    "TEWL-forehead", "TEWL-Cheek",
    "Sebum-forehead", "Sebum-cheek",
    "Red-Area-forehead", "Red-Area-cheek",
    "Pores-Area-forehead", "Pores-Area-cheek",
    "GLOSS-forehead", "GLOSS-Cheek",
    "GLOSS-DCS-forehead", "GLOSS-DCS-cheek",
    "MEXA_Melanin-forehead", "MEXA_Melanin-cheek",
    "MEXA_Erythema-forehead", "MEXA_Erythema-cheek",
    "ITA-forehead", "ITA-cheek",
    "A_value-forehead", "A_value-cheek",
    "B_value-forehead", "B_value-cheek",
    "Elasticity_R0-forehead", "Elasticity_R0-cheek",
    "Elasticity_R1-forehead", "Elasticity_R1-cheek",
    "Elasticity_R2-forehead", "Elasticity_R2-cheek",
    "Elasticity_R3-forehead", "Elasticity_R3-cheek",
    "Elasticity_R4_-_forehead", "Elasticity_R4_-_cheek",
    "Elasticity_R5_-_forehead", "Elasticity_R5_-_cheek",
    "Elasticity_R6_-_forehead", "Elasticity_R6_-cheek",
    "Elasticity_R7-forehead", "Elasticity_R7-cheek",
    "Elasticity_R8_-_forehead", "Elasticity_R8_-_cheek",
    "Elasticity_R9-forehead", "Elasticity_R9-cheek",
    "Elasticity_F0-forehead", "Elasticity_F0-cheek",
    "Elasticity_F1-forehead", "Elasticity_F1-cheek",
    "Elasticity_R1_R4-forehead", "Elasticity_R1_R4-cheek",
    "Elasticity_R3_R9-forehead", "Elasticity_R3_R9-cheek",
    "Epidermal_thickness",
]

# Create standardized names only for the selected columns
clinical_rename = {
    col: col.replace("-", "_").replace("Hydratation", "Hydration")
    for col in clinical_columns
}

# Apply the changes
df = df.rename(columns=clinical_rename)

# Start column names with an uppercase letter
df.columns = [col[0].upper() + col[1:] for col in df.columns]

In [157]:
# To verify the selected columns:
print(", ".join(clinical_rename.values()))

Trans_Urocanic_acid, Hydration_forehead, Hydration_cheek, Hydration_forearm, TEWL_forehead, TEWL_Cheek, Sebum_forehead, Sebum_cheek, Red_Area_forehead, Red_Area_cheek, Pores_Area_forehead, Pores_Area_cheek, GLOSS_forehead, GLOSS_Cheek, GLOSS_DCS_forehead, GLOSS_DCS_cheek, MEXA_Melanin_forehead, MEXA_Melanin_cheek, MEXA_Erythema_forehead, MEXA_Erythema_cheek, ITA_forehead, ITA_cheek, A_value_forehead, A_value_cheek, B_value_forehead, B_value_cheek, Elasticity_R0_forehead, Elasticity_R0_cheek, Elasticity_R1_forehead, Elasticity_R1_cheek, Elasticity_R2_forehead, Elasticity_R2_cheek, Elasticity_R3_forehead, Elasticity_R3_cheek, Elasticity_R4___forehead, Elasticity_R4___cheek, Elasticity_R5___forehead, Elasticity_R5___cheek, Elasticity_R6___forehead, Elasticity_R6__cheek, Elasticity_R7_forehead, Elasticity_R7_cheek, Elasticity_R8___forehead, Elasticity_R8___cheek, Elasticity_R9_forehead, Elasticity_R9_cheek, Elasticity_F0_forehead, Elasticity_F0_cheek, Elasticity_F1_forehead, Elasticity_F1_cheek, Elasticity_R1_R4_forehead, Elasticity_R1_R4_cheek, Elasticity_R3_R9_forehead, Elasticity_R3_R9_cheek, Epidermal_thickness

In [158]:
# Remove repeated underscores from standardized clinical column names
df.columns = [col.replace("__", "_") for col in df.columns]

In [159]:
print(", ".join(df.columns))

Treatment, Participant_ID, Measurement_Time, Gender, Phototype, Age, Alanin, Arginine, Asparagine, Citruline, Fenylalanin, Glutamic_acid, Glutamin, Glycine, Histidin, Isoleucine, Aspartic_Acid, Leucine, Lysin, Methionine, Ornithine, Proline, Pyrrolidone_carboxylic_acid, Serine, Threonine, Tryptofan, Tyrosine, Urea, Valin, NMF, Total_urocanic_acid, Trans_Urocanic_acid, Hydration_forehead, Hydration_cheek, Hydration_forearm, TEWL_forehead, TEWL_Cheek, Sebum_forehead, Sebum_cheek, Wrinkle, Red_Area_forehead, Red_Area_cheek, Pores_Area_forehead, Pores_Area_cheek, GLOSS_forehead, GLOSS_Cheek, GLOSS_DCS_forehead, GLOSS_DCS_cheek, MEXA_Melanin_forehead, MEXA_Melanin_cheek, MEXA_Erythema_forehead, MEXA_Erythema_cheek, ITA_forehead, ITA_cheek, A_value_forehead, A_value_cheek, B_value_forehead, B_value_cheek, Elasticity_R0_forehead, Elasticity_R0_cheek, Elasticity_R1_forehead, Elasticity_R1_cheek, Elasticity_R2_forehead, Elasticity_R2_cheek, Elasticity_R3_forehead, Elasticity_R3_cheek, Elasticity_R4__forehead, Elasticity_R4__cheek, Elasticity_R5__forehead, Elasticity_R5__cheek, Elasticity_R6__forehead, Elasticity_R6_cheek, Elasticity_R7_forehead, Elasticity_R7_cheek, Elasticity_R8__forehead, Elasticity_R8_-cheek, Elasticity_R9_forehead, Elasticity_R9_cheek, Elasticity_F0_forehead, Elasticity_F0_cheek, Elasticity_F1_forehead, Elasticity_F1_cheek, Elasticity_R1_R4_forehead, Elasticity_R1_R4_cheek, Elasticity_R3_R9_forehead, Elasticity_R3_R9_cheek, Epidermal_thickness, Dermal_density, CAR_12:0, CAR_12:1, CAR_12:2, CAR_13:0, CAR_14:1, CAR_14:2, CAR_14:3, CAR_16:0, CAR_16:1, CAR_16:2, CAR_16:3, CAR_18:1, CAR_18:2, CAR_18:3, CAR_20:1, CAR_20:2, CAR_22:0, CAR_24:1, CAR_26:0, CE_16:1, CE_17:0, CE_18:1, CE_18:2, CE_18:3, CE_20:3, CE_20:4, CE_20:5, CE_22:6, Cer_34:1_NS_-_neg, Cer_38:1_;2O, Cer_38:1_NS_-_neg, Cer_40:0_;2O, Cer_40:0_;2O_-neg, Cer_40:1_;2O, Cer_40:1_NS_-_neg, Cer_40:2_;2O, Cer_40:2_NS_-_neg, Cer_41:0_;2O, Cer_41:1_;2O, Cer_41:1_NS_-_neg, Cer_41:2_;2O, Cer_42:0_;2O, Cer_42:0_;2O_-_neg, Cer_42:1_;2O_-_neg, Cer_42:1_;2O_(1), Cer_42:1_;2O_(2), Cer_42:2_;2O, Cer_42:2_NS_-_neg, Cer_42:3_;2O, Cer_42:3_;2O_-_neg, Cer_43:1_;2O, Cer_43:1_;2O_-_neg, Cer_43:2_;2O, Cer_44:1_;2O_-_neg, DG_36:2, FA_14:0, FA_14:1, FA_16:0, FA_16:1, FA_16:3, FA_18:1, FA_18:2, FA_18:3, FA_19:1, FA_20:1, FA_20:2, FA_20:3, FA_20:4, FA_20:5, FA_22:1, FA_22:2, FA_22:3, FA_22:4, FA_22:5, FA_22:6, FA_24:1, FA_24:2, FA_24:4, FA_24:5, FA_26:3, FA_34:0, FAHFA_24:3, FAHFA_36:1, FAHFA_38:2, FAHFA_38:4, FAHFA_40:3, FAHFA_40:4, FC, GM3_32:1_;2O_-_neg, GM3_40:1_;2O_-_neg, GM3_42:1_;2O_-_neg, GM3_42:2_;2O_-_neg, Hex2Cer_34:1_;2O_-_neg, Hex3Cer_34:1_;2O, Hex3Cer_40:1_;2O, HexCer_34:0_;3O;(2OH)_-_neg, HexCer_34:1_;2O_-_neg, HexCer_36:1_;2O_-_neg, HexCer_38:1_;2O_-_neg, HexCer_40:1_;2O, HexCer_40:1_;2O_-_neg, HexCer_40:2_;2O_-_neg, HexCer_41:1_;2O_-_neg, HexCer_41:2_;2O_-_neg, HexCer_42:1_;2O, HexCer_42:1_;2O_-_neg, HexCer_42:2_;2O_-_neg, HexCer_42:3_;2O_-_neg, LNAPE_36:4, LPC_12:0, LPC_14:1, LPC_16:1, LPC_16:2, LPC_17:0, LPC_17:1, LPC_18:0, LPC_18:1, LPC_18:2, LPC_19:0, LPC_19:1, LPC_20:0, LPC_20:1, LPC_20:2, LPC_20:3, LPC_20:4, LPC_22:0, LPC_22:1, LPC_22:3, LPC_22:5, LPC_22:6, LPC_24:0, LPC_24:5, LPC_26:1, LPC-O_16:0, LPC-O_16:1, LPC-O_17:0, LPC-O_18:1, LPC-O_20:0, LPC-O_22:1, LPC-O_26:2, LPE_16:0, LPE_18:0, LPE_18:1, LPE_20:3, LPE_20:5, LPE_22:5, LPE_22:6, LPE-O_16:1, LPE-O_18:2, LPI_18:0, LPI_18:2, LPI_20:3, LPI_20:4, PC_24:0, PC_26:0, PC_28:0, PC_28:1, PC_30:0, PC_30:1, PC_31:1, PC_31:2, PC_32:0, PC_32:1, PC_32:2, PC_32:3, PC_33:0, PC_33:1, PC_33:2, PC_33:4, PC_34:2, PC_34:3, PC_34:4, PC_34:5, PC_35:0, PC_35:1, PC_35:2, PC_35:3, PC_35:4, PC_35:5, PC_36:0, PC_36:1, PC_36:2, PC_36:3, PC_36:4, PC_36:5, PC_36:6, PC_36:7, PC_37:2, PC_37:4, PC_37:5, PC_37:6, PC_37:7, PC_38:1, PC_38:2, PC_38:3, PC_38:5, PC_38:6, PC_38:7, PC_38:8, PC_38:9, PC_39:1, PC_39:3, PC_39:5, PC_39:6, PC_39:7, PC_40:1, PC_40:2, PC_40:3, PC_40:4, PC_40:5, PC_40:6, PC_40:7, PC_40:8, PC_40:9, PC_42:10, PC_42:5, PC_42:7, PC_44:4, PC_44:5, PC-O_30:0, PC-O_31:1, PC-O_32:0, PC-O_32:1, PC-O_33:2, PC-O_34:0, PC-O_34:1, PC-O_34:2, PC-O_34:3, PC-O_34:4, PC-O_35:4, PC-O_35:6, PC-O_35:7, PC-O_36:0, PC-O_36:2, PC-O_36:3, PC-O_36:4, PC-O_36:5, PC-O_36:6, PC-O_37:6, PC-O_37:7, PC-O_38:0, PC-O_38:4, PC-O_38:5, PC-O_38:6, PC-O_38:7, PC-O_39:6, PC-O_40:2, PC-O_40:3, PC-O_40:5, PC-O_40:6, PC-O_40:7, PC-O_42:1, PC-O_42:2, PC-O_42:3, PC-O_42:4, PC-O_42:5, PC-O_42:6, PC-O_44:5, PC-O_44:6, PC-O_44:7, PC-O_46:5, PC-O_46:6, PC-O_46:7, PC-O_46:8, PE_32:1, PE_34:1, PE_34:2, PE_34:3, PE_36:1, PE_36:2, PE_36:3, PE_36:4, PE_38:4, PE_38:6, PE-O_34:2, PE-O_34:3, PE-O_36:2, PE-O_36:3, PE-O_36:4, PE-O_36:5, PE-O_36:6, PE-O_36:7, PE-O_37:5, PE-O_37:6, PE-O_38:2, PE-O_38:3, PE-O_38:4, PE-O_38:5, PE-O_38:6, PE-O_38:7, PE-O_39:6, PE-O_39:7, PE-O_40:7, PE-O_40:8, PE-O_40:9, PE-O_42:7, PE-O_42:8, PG_34:2, PG_36:2, PI_32:1, PI_34:1, PI_36:1, PI_36:2, PI_36:4, PI_37:4, PI_38:2, PI_38:3, PI_38:4, PI_40:5, PI_40:6, SM_29:1_;2O, SM_30:0_;2O, SM_30:1_;2O_(1), SM_30:1_;2O_(2), SM_31:1_;2O, SM_32:0_;2O, SM_32:1_;2O, SM_32:2_;2O_(1), SM_32:2_;2O_(2), SM_33:1_;2O_(1), SM_33:1_;2O_(2), SM_33:2_;2O, SM_34:0_;2O, SM_34:1_;2O_(1), SM_34:1_;3O_(2), SM_34:2_;2O_(1), SM_34:2_;2O_(2), SM_34:3_;2O, SM_35:1_;2O, SM_36:0_;2O, SM_36:2_;2O, SM_36:3_;2O, SM_37:1_;2O, SM_38:0_;2O, SM_38:1_;2O_(1), SM_38:1_;2O_(2), SM_38:2_;2O, SM_38:3_;2O, SM_38:4_;2O, SM_39:0_;2O, SM_39:1_;2O_(1), SM_39:1_;2O_(2), SM_39:1_;2O_(3), SM_39:2_;2O, SM_40:0_;2O, SM_40:1_;2O_(1), SM_40:1_;2O_(2), SM_40:2_;2O_(1), SM_40:2_;2O_(2), SM_40:3_;2O, SM_41:0_;2O, SM_41:1_;2O_(1), SM_41:1_;2O_(2), SM_41:1_;2O_(3), SM_41:2_;2O_(1), SM_41:2_;2O_(2), SM_42:1_;2O_(1), SM_42:1_;2O_(2), SM_42:2_;2O_(1), SM_42:2_;2O_(2), SM_42:2_;2O_(3), SM_42:3_;2O, SM_42:4_;2O, SM_42:5_;2O, SM_43:1_;2O_(1), SM_43:1_;2O_(2), SM_43:2_;2O_(1), SM_43:2_;2O_(2), SM_43:2_;2O_(3), SM_43:3_;2O, SM_44:1_;2O, SM_44:2_;2O, SM_44:3_;2O, TG_34:0, TG_36:0, TG_40:0, TG_42:0, TG_42:1, TG_42:2_(1), TG_42:2_(2), TG_44:0, TG_44:1_(1), TG_44:1_(2), TG_44:2_(1), TG_44:2_(2), TG_44:3, TG_45:1, TG_45:2, TG_46:0, TG_46:1, TG_46:2, TG_46:3_(1), TG_46:3_(2), TG_46:3_(3), TG_47:1, TG_47:2, TG_47:3, TG_48:1, TG_48:2, TG_48:3_(1), TG_48:3_(2), TG_48:3_(3), TG_48:4, TG_48:5, TG_49:0, TG_49:1, TG_49:2, TG_49:3, TG_49:4, TG_49:5, TG_50:0, TG_50:1, TG_50:1, TG_50:2, TG_50:3, TG_50:4_(1), TG_50:4_(2), TG_50:5, TG_50:6, TG_51:0, TG_51:1, TG_51:2, TG_51:3, TG_51:4, TG_52:1, TG_52:2, TG_52:3, TG_52:4_(1), TG_52:4_(2), TG_52:5_(1), TG_52:5_(2), TG_52:6_(1), TG_52:6_(2), TG_52:7, TG_53:1, TG_53:2, TG_53:3_(1), TG_53:3_(2), TG_53:4, TG_53:5, TG_54:1, TG_54:2_(1), TG_54:2_(2), TG_54:3, TG_54:4, TG_54:5, TG_54:6, TG_54:7, TG_54:8, TG_55:2_(1), TG_55:2_(2), TG_55:3, TG_55:4, TG_55:6, TG_55:7, TG_56:1_(1), TG_56:1_(2), TG_56:10, TG_56:2_(1), TG_56:2_(2), TG_56:3_(1), TG_56:3_(2), TG_56:4_(1), TG_56:4_(2), TG_56:5_(1), TG_56:5_(2), TG_56:6, TG_56:7, TG_56:8, TG_56:9_(1), TG_56:9_(2), TG_57:11, TG_57:2, TG_57:3, TG_57:4, TG_57:6, TG_57:8, TG_58:1, TG_58:10, TG_58:11, TG_58:12, TG_58:2, TG_58:3, TG_58:4, TG_58:5, TG_58:6, TG_58:7, TG_58:8, TG_58:9_(1), TG_58:9_(2), TG_59:11, TG_59:12, TG_59:2, TG_59:3, TG_60:1, TG_60:10, TG_60:11, TG_60:12, TG_60:13, TG_60:2, TG_60:3_(1), TG_60:3_(2), TG_60:4, TG_60:5, TG_60:6, TG_60:7, TG_60:8, TG_60:9, TG_61:1, TG_61:2, TG_61:3, TG_61:4, TG_62:1, TG_62:11, TG_62:12, TG_62:13_(1), TG_62:13_(2), TG_62:14, TG_62:2, TG_62:3, TG_62:4_(1), TG_62:4_(2), TG_62:5, TG_63:2, TG_64:1, TG_64:2, TG_64:4, TG_66:3, TG-O_50:1, TG-O_52:1, TG-O_52:2, TG-O_58:3, MDA, 12,13-diHOME, 13-HODE, 9-HODE, 5-HETE, EPA, DHA, Arachidonic_acid, CRP, Fetuin_A, Adipsin, GLP1_total, Glucagon, TNFa, EGF, FGF2, IFNg, IL1b, IL1RA, IL10, IL17A, C_peptide, IL6, Leptin, MCP1, (+/-)14(15)-DiHET, (4E,6E)-2,7-dimethyl-8-[(2R,3R,4S,5S,6R)-3,4,5-trihydroxy-6-(hydroxymethyl)oxan-2-yl]oxyocta-4,6-dienoic_acid, (4E,7E)-dodeca-4,7-dienedioic_acid, (E)-6-hydroxyoctadec-4-enoic_acid, (Z)-3-hydroxydodec-5-enoic_acid, 1,16-Hexadecanedioic_acid, 1,3-Dimethyluric_acid, 1,7-Dimethyluric_acid, 10-HDA, 16-Hydroxyhexadecanoic_acid, 1-Methyluric_acid, 1-Methylxanthine, 2-(4-Hydroxyphenyl)propanoic_acid, 2-(ALPHA-D-MANNOPYRANOSYL)-L-TRYPTOPHAN, 2,4-Dinitrophenol, 2,5-Dihydroxybenzenesulfonic_Acid, 2,6-Dihydroxybenzoic_acid, 2-Furoic_acid, 2-Furoylglycine, 2-Hydroxyhippuric_acid, 2-Hydroxyisobutyric_acid, 2-Hydroxyisobutyric_acid, 2-Methyl-4,6-dinitrophenol, 3-(1-Pyrazolyl)-alanine, 3-Allyl-2-hydroxybenzoic_acid, 3-FUROIC_ACID, 3-Hydroxybutyric_acid, 3-Hydroxydecanoic_acid, 3-Indoxyl_sulphate, 3-Indoxyl_sulphate, 3-Methoxysalicylic_acid, 3-Methoxytyrosine, 3-Methyl-2-oxovaleric_acid_calcium_salt, 3-Methylxanthine, 3-Phenyllactic_acid, 4-Acetamidobutanoic_acid, 4-Hydroxy-3-_methoxyphenylglycol_sulfate, 4-Hydroxy-3-oxo-4-propan-2-ylcyclohexene-1-carboxylic_acid, 4-Hydroxyhippuric_acid_sulfate, 4-Chlorophenoxyacetic_acid, 4-Methoxymelilotic_acid, 4-Methylphenol, 4-Oxoproline, 4-Phenolsulfonic_acid, 4-Pyridoxic_acid, 5-Aminolevulinic_acid, Acetaminophen_glucuronide, Adenosine_3'5'-cyclic_monophosphate, Adenosine_5'-monophosphate, Beta-D-N-Acetylmannosamine, Catechol, Citric_acid, Citrulline, CMPF, CMPF, D-(-)-Glutamine, D-(+)-Tryptophan, Decanoic_acid, Deoxycholic_acid, D-Glucose, DL-4-Hydroxyphenyllactic_acid, DL-Arginine, DL-Lactic_Acid, Dodecanedioic_acid, D-Panthenol, D-Pantothenic_acid, D-Threonine, Epinephrine, Erdosteine, Gluconic_acid, Glu-Leu, Glu-Leu-Ser, Glu-Phe, Glu-Pro, Glu-Tyr, Glu-Val, Glycine, Glycochenodeoxycholic_acid, Glycochenodeoxycholic_acid, Glycochenodeoxycholic_acid, Glycocholic_acid, Hippuric_acid, His-His, Hydrocortisone, Hypoxanthine, Cholic_Acid, Ibuprofen_metabolite_B, Ile-Glu, Indole-3-acrylic_acid, Indole-3-lactic_acid, Indole-3-lactic_acid, Inosine, Isocitric_acid, Kynurenic_acid, L-(-)-Malic_acid, L-(+)-Lactic_acid, L-Ascorbic_acid_2-sulfate, L-Histidine, L-isoleucine, L-Ornithine, LPE_16:0, LPE_18:1, LPE_22:6, L-Tyrosine, Met-Glu, Methyl_4-cyano-3-[2-(1-cyano-2-ethoxy-2-oxoethylidene)hydrazino]thiophene-2-carboxylate, N4-Acetylcytidine, N6-Succinyladenosine;_LC-tDDA;_CE20, N-Acetyl_carnosine, N-Acetylalanine, N-Acetyl-L-aspartic_acid, N-Acetyl-L-methionine, N-Acetyl-L-phenylalanine, N-Acetyl-threonine;_LC-tDDA;_CE10, N-Formylmethionine, Nimesulide, N-Isovalerylglycine, Perfluoro-1-butanesulfonic_acid_(PFBS), Phe-Lys-Tyr, Phenol, Phenylacetylglutamine, P-hydroxybenzoic_acid, P-Hydroxyphenylacetic_acid, Pyruvic_acid, Saccharin, Salicyluric_acid, Ser-Glu, Ser-Leu-Tyr, Succinic_acid, Tetradecanedioic_acid, Theophylline, UKOUEEGEHXWHHO-MOFOKWOHSA-N, Undecylenic_acid, Uric_acid, Uridine, Xanthine, Β-Muricholic_acid

In [160]:
# Replace special characters in column names with underscores
df.columns = (
    df.columns
    .str.replace(r"[():+\-;]", "_", regex=True)
    .str.replace(r"_+", "_", regex=True)
    .str.strip("_")
)

print(", ".join(df.columns))

Treatment, Participant_ID, Measurement_Time, Gender, Phototype, Age, Alanin, Arginine, Asparagine, Citruline, Fenylalanin, Glutamic_acid, Glutamin, Glycine, Histidin, Isoleucine, Aspartic_Acid, Leucine, Lysin, Methionine, Ornithine, Proline, Pyrrolidone_carboxylic_acid, Serine, Threonine, Tryptofan, Tyrosine, Urea, Valin, NMF, Total_urocanic_acid, Trans_Urocanic_acid, Hydration_forehead, Hydration_cheek, Hydration_forearm, TEWL_forehead, TEWL_Cheek, Sebum_forehead, Sebum_cheek, Wrinkle, Red_Area_forehead, Red_Area_cheek, Pores_Area_forehead, Pores_Area_cheek, GLOSS_forehead, GLOSS_Cheek, GLOSS_DCS_forehead, GLOSS_DCS_cheek, MEXA_Melanin_forehead, MEXA_Melanin_cheek, MEXA_Erythema_forehead, MEXA_Erythema_cheek, ITA_forehead, ITA_cheek, A_value_forehead, A_value_cheek, B_value_forehead, B_value_cheek, Elasticity_R0_forehead, Elasticity_R0_cheek, Elasticity_R1_forehead, Elasticity_R1_cheek, Elasticity_R2_forehead, Elasticity_R2_cheek, Elasticity_R3_forehead, Elasticity_R3_cheek, Elasticity_R4_forehead, Elasticity_R4_cheek, Elasticity_R5_forehead, Elasticity_R5_cheek, Elasticity_R6_forehead, Elasticity_R6_cheek, Elasticity_R7_forehead, Elasticity_R7_cheek, Elasticity_R8_forehead, Elasticity_R8_cheek, Elasticity_R9_forehead, Elasticity_R9_cheek, Elasticity_F0_forehead, Elasticity_F0_cheek, Elasticity_F1_forehead, Elasticity_F1_cheek, Elasticity_R1_R4_forehead, Elasticity_R1_R4_cheek, Elasticity_R3_R9_forehead, Elasticity_R3_R9_cheek, Epidermal_thickness, Dermal_density, CAR_12_0, CAR_12_1, CAR_12_2, CAR_13_0, CAR_14_1, CAR_14_2, CAR_14_3, CAR_16_0, CAR_16_1, CAR_16_2, CAR_16_3, CAR_18_1, CAR_18_2, CAR_18_3, CAR_20_1, CAR_20_2, CAR_22_0, CAR_24_1, CAR_26_0, CE_16_1, CE_17_0, CE_18_1, CE_18_2, CE_18_3, CE_20_3, CE_20_4, CE_20_5, CE_22_6, Cer_34_1_NS_neg, Cer_38_1_2O, Cer_38_1_NS_neg, Cer_40_0_2O, Cer_40_0_2O_neg, Cer_40_1_2O, Cer_40_1_NS_neg, Cer_40_2_2O, Cer_40_2_NS_neg, Cer_41_0_2O, Cer_41_1_2O, Cer_41_1_NS_neg, Cer_41_2_2O, Cer_42_0_2O, Cer_42_0_2O_neg, Cer_42_1_2O_neg, Cer_42_1_2O_1, Cer_42_1_2O_2, Cer_42_2_2O, Cer_42_2_NS_neg, Cer_42_3_2O, Cer_42_3_2O_neg, Cer_43_1_2O, Cer_43_1_2O_neg, Cer_43_2_2O, Cer_44_1_2O_neg, DG_36_2, FA_14_0, FA_14_1, FA_16_0, FA_16_1, FA_16_3, FA_18_1, FA_18_2, FA_18_3, FA_19_1, FA_20_1, FA_20_2, FA_20_3, FA_20_4, FA_20_5, FA_22_1, FA_22_2, FA_22_3, FA_22_4, FA_22_5, FA_22_6, FA_24_1, FA_24_2, FA_24_4, FA_24_5, FA_26_3, FA_34_0, FAHFA_24_3, FAHFA_36_1, FAHFA_38_2, FAHFA_38_4, FAHFA_40_3, FAHFA_40_4, FC, GM3_32_1_2O_neg, GM3_40_1_2O_neg, GM3_42_1_2O_neg, GM3_42_2_2O_neg, Hex2Cer_34_1_2O_neg, Hex3Cer_34_1_2O, Hex3Cer_40_1_2O, HexCer_34_0_3O_2OH_neg, HexCer_34_1_2O_neg, HexCer_36_1_2O_neg, HexCer_38_1_2O_neg, HexCer_40_1_2O, HexCer_40_1_2O_neg, HexCer_40_2_2O_neg, HexCer_41_1_2O_neg, HexCer_41_2_2O_neg, HexCer_42_1_2O, HexCer_42_1_2O_neg, HexCer_42_2_2O_neg, HexCer_42_3_2O_neg, LNAPE_36_4, LPC_12_0, LPC_14_1, LPC_16_1, LPC_16_2, LPC_17_0, LPC_17_1, LPC_18_0, LPC_18_1, LPC_18_2, LPC_19_0, LPC_19_1, LPC_20_0, LPC_20_1, LPC_20_2, LPC_20_3, LPC_20_4, LPC_22_0, LPC_22_1, LPC_22_3, LPC_22_5, LPC_22_6, LPC_24_0, LPC_24_5, LPC_26_1, LPC_O_16_0, LPC_O_16_1, LPC_O_17_0, LPC_O_18_1, LPC_O_20_0, LPC_O_22_1, LPC_O_26_2, LPE_16_0, LPE_18_0, LPE_18_1, LPE_20_3, LPE_20_5, LPE_22_5, LPE_22_6, LPE_O_16_1, LPE_O_18_2, LPI_18_0, LPI_18_2, LPI_20_3, LPI_20_4, PC_24_0, PC_26_0, PC_28_0, PC_28_1, PC_30_0, PC_30_1, PC_31_1, PC_31_2, PC_32_0, PC_32_1, PC_32_2, PC_32_3, PC_33_0, PC_33_1, PC_33_2, PC_33_4, PC_34_2, PC_34_3, PC_34_4, PC_34_5, PC_35_0, PC_35_1, PC_35_2, PC_35_3, PC_35_4, PC_35_5, PC_36_0, PC_36_1, PC_36_2, PC_36_3, PC_36_4, PC_36_5, PC_36_6, PC_36_7, PC_37_2, PC_37_4, PC_37_5, PC_37_6, PC_37_7, PC_38_1, PC_38_2, PC_38_3, PC_38_5, PC_38_6, PC_38_7, PC_38_8, PC_38_9, PC_39_1, PC_39_3, PC_39_5, PC_39_6, PC_39_7, PC_40_1, PC_40_2, PC_40_3, PC_40_4, PC_40_5, PC_40_6, PC_40_7, PC_40_8, PC_40_9, PC_42_10, PC_42_5, PC_42_7, PC_44_4, PC_44_5, PC_O_30_0, PC_O_31_1, PC_O_32_0, PC_O_32_1, PC_O_33_2, PC_O_34_0, PC_O_34_1, PC_O_34_2, PC_O_34_3, PC_O_34_4, PC_O_35_4, PC_O_35_6, PC_O_35_7, PC_O_36_0, PC_O_36_2, PC_O_36_3, PC_O_36_4, PC_O_36_5, PC_O_36_6, PC_O_37_6, PC_O_37_7, PC_O_38_0, PC_O_38_4, PC_O_38_5, PC_O_38_6, PC_O_38_7, PC_O_39_6, PC_O_40_2, PC_O_40_3, PC_O_40_5, PC_O_40_6, PC_O_40_7, PC_O_42_1, PC_O_42_2, PC_O_42_3, PC_O_42_4, PC_O_42_5, PC_O_42_6, PC_O_44_5, PC_O_44_6, PC_O_44_7, PC_O_46_5, PC_O_46_6, PC_O_46_7, PC_O_46_8, PE_32_1, PE_34_1, PE_34_2, PE_34_3, PE_36_1, PE_36_2, PE_36_3, PE_36_4, PE_38_4, PE_38_6, PE_O_34_2, PE_O_34_3, PE_O_36_2, PE_O_36_3, PE_O_36_4, PE_O_36_5, PE_O_36_6, PE_O_36_7, PE_O_37_5, PE_O_37_6, PE_O_38_2, PE_O_38_3, PE_O_38_4, PE_O_38_5, PE_O_38_6, PE_O_38_7, PE_O_39_6, PE_O_39_7, PE_O_40_7, PE_O_40_8, PE_O_40_9, PE_O_42_7, PE_O_42_8, PG_34_2, PG_36_2, PI_32_1, PI_34_1, PI_36_1, PI_36_2, PI_36_4, PI_37_4, PI_38_2, PI_38_3, PI_38_4, PI_40_5, PI_40_6, SM_29_1_2O, SM_30_0_2O, SM_30_1_2O_1, SM_30_1_2O_2, SM_31_1_2O, SM_32_0_2O, SM_32_1_2O, SM_32_2_2O_1, SM_32_2_2O_2, SM_33_1_2O_1, SM_33_1_2O_2, SM_33_2_2O, SM_34_0_2O, SM_34_1_2O_1, SM_34_1_3O_2, SM_34_2_2O_1, SM_34_2_2O_2, SM_34_3_2O, SM_35_1_2O, SM_36_0_2O, SM_36_2_2O, SM_36_3_2O, SM_37_1_2O, SM_38_0_2O, SM_38_1_2O_1, SM_38_1_2O_2, SM_38_2_2O, SM_38_3_2O, SM_38_4_2O, SM_39_0_2O, SM_39_1_2O_1, SM_39_1_2O_2, SM_39_1_2O_3, SM_39_2_2O, SM_40_0_2O, SM_40_1_2O_1, SM_40_1_2O_2, SM_40_2_2O_1, SM_40_2_2O_2, SM_40_3_2O, SM_41_0_2O, SM_41_1_2O_1, SM_41_1_2O_2, SM_41_1_2O_3, SM_41_2_2O_1, SM_41_2_2O_2, SM_42_1_2O_1, SM_42_1_2O_2, SM_42_2_2O_1, SM_42_2_2O_2, SM_42_2_2O_3, SM_42_3_2O, SM_42_4_2O, SM_42_5_2O, SM_43_1_2O_1, SM_43_1_2O_2, SM_43_2_2O_1, SM_43_2_2O_2, SM_43_2_2O_3, SM_43_3_2O, SM_44_1_2O, SM_44_2_2O, SM_44_3_2O, TG_34_0, TG_36_0, TG_40_0, TG_42_0, TG_42_1, TG_42_2_1, TG_42_2_2, TG_44_0, TG_44_1_1, TG_44_1_2, TG_44_2_1, TG_44_2_2, TG_44_3, TG_45_1, TG_45_2, TG_46_0, TG_46_1, TG_46_2, TG_46_3_1, TG_46_3_2, TG_46_3_3, TG_47_1, TG_47_2, TG_47_3, TG_48_1, TG_48_2, TG_48_3_1, TG_48_3_2, TG_48_3_3, TG_48_4, TG_48_5, TG_49_0, TG_49_1, TG_49_2, TG_49_3, TG_49_4, TG_49_5, TG_50_0, TG_50_1, TG_50_1, TG_50_2, TG_50_3, TG_50_4_1, TG_50_4_2, TG_50_5, TG_50_6, TG_51_0, TG_51_1, TG_51_2, TG_51_3, TG_51_4, TG_52_1, TG_52_2, TG_52_3, TG_52_4_1, TG_52_4_2, TG_52_5_1, TG_52_5_2, TG_52_6_1, TG_52_6_2, TG_52_7, TG_53_1, TG_53_2, TG_53_3_1, TG_53_3_2, TG_53_4, TG_53_5, TG_54_1, TG_54_2_1, TG_54_2_2, TG_54_3, TG_54_4, TG_54_5, TG_54_6, TG_54_7, TG_54_8, TG_55_2_1, TG_55_2_2, TG_55_3, TG_55_4, TG_55_6, TG_55_7, TG_56_1_1, TG_56_1_2, TG_56_10, TG_56_2_1, TG_56_2_2, TG_56_3_1, TG_56_3_2, TG_56_4_1, TG_56_4_2, TG_56_5_1, TG_56_5_2, TG_56_6, TG_56_7, TG_56_8, TG_56_9_1, TG_56_9_2, TG_57_11, TG_57_2, TG_57_3, TG_57_4, TG_57_6, TG_57_8, TG_58_1, TG_58_10, TG_58_11, TG_58_12, TG_58_2, TG_58_3, TG_58_4, TG_58_5, TG_58_6, TG_58_7, TG_58_8, TG_58_9_1, TG_58_9_2, TG_59_11, TG_59_12, TG_59_2, TG_59_3, TG_60_1, TG_60_10, TG_60_11, TG_60_12, TG_60_13, TG_60_2, TG_60_3_1, TG_60_3_2, TG_60_4, TG_60_5, TG_60_6, TG_60_7, TG_60_8, TG_60_9, TG_61_1, TG_61_2, TG_61_3, TG_61_4, TG_62_1, TG_62_11, TG_62_12, TG_62_13_1, TG_62_13_2, TG_62_14, TG_62_2, TG_62_3, TG_62_4_1, TG_62_4_2, TG_62_5, TG_63_2, TG_64_1, TG_64_2, TG_64_4, TG_66_3, TG_O_50_1, TG_O_52_1, TG_O_52_2, TG_O_58_3, MDA, 12,13_diHOME, 13_HODE, 9_HODE, 5_HETE, EPA, DHA, Arachidonic_acid, CRP, Fetuin_A, Adipsin, GLP1_total, Glucagon, TNFa, EGF, FGF2, IFNg, IL1b, IL1RA, IL10, IL17A, C_peptide, IL6, Leptin, MCP1, /_14_15_DiHET, 4E,6E_2,7_dimethyl_8_[_2R,3R,4S,5S,6R_3,4,5_trihydroxy_6_hydroxymethyl_oxan_2_yl]oxyocta_4,6_dienoic_acid, 4E,7E_dodeca_4,7_dienedioic_acid, E_6_hydroxyoctadec_4_enoic_acid, Z_3_hydroxydodec_5_enoic_acid, 1,16_Hexadecanedioic_acid, 1,3_Dimethyluric_acid, 1,7_Dimethyluric_acid, 10_HDA, 16_Hydroxyhexadecanoic_acid, 1_Methyluric_acid, 1_Methylxanthine, 2_4_Hydroxyphenyl_propanoic_acid, 2_ALPHA_D_MANNOPYRANOSYL_L_TRYPTOPHAN, 2,4_Dinitrophenol, 2,5_Dihydroxybenzenesulfonic_Acid, 2,6_Dihydroxybenzoic_acid, 2_Furoic_acid, 2_Furoylglycine, 2_Hydroxyhippuric_acid, 2_Hydroxyisobutyric_acid, 2_Hydroxyisobutyric_acid, 2_Methyl_4,6_dinitrophenol, 3_1_Pyrazolyl_alanine, 3_Allyl_2_hydroxybenzoic_acid, 3_FUROIC_ACID, 3_Hydroxybutyric_acid, 3_Hydroxydecanoic_acid, 3_Indoxyl_sulphate, 3_Indoxyl_sulphate, 3_Methoxysalicylic_acid, 3_Methoxytyrosine, 3_Methyl_2_oxovaleric_acid_calcium_salt, 3_Methylxanthine, 3_Phenyllactic_acid, 4_Acetamidobutanoic_acid, 4_Hydroxy_3_methoxyphenylglycol_sulfate, 4_Hydroxy_3_oxo_4_propan_2_ylcyclohexene_1_carboxylic_acid, 4_Hydroxyhippuric_acid_sulfate, 4_Chlorophenoxyacetic_acid, 4_Methoxymelilotic_acid, 4_Methylphenol, 4_Oxoproline, 4_Phenolsulfonic_acid, 4_Pyridoxic_acid, 5_Aminolevulinic_acid, Acetaminophen_glucuronide, Adenosine_3'5'_cyclic_monophosphate, Adenosine_5'_monophosphate, Beta_D_N_Acetylmannosamine, Catechol, Citric_acid, Citrulline, CMPF, CMPF, D_Glutamine, D_Tryptophan, Decanoic_acid, Deoxycholic_acid, D_Glucose, DL_4_Hydroxyphenyllactic_acid, DL_Arginine, DL_Lactic_Acid, Dodecanedioic_acid, D_Panthenol, D_Pantothenic_acid, D_Threonine, Epinephrine, Erdosteine, Gluconic_acid, Glu_Leu, Glu_Leu_Ser, Glu_Phe, Glu_Pro, Glu_Tyr, Glu_Val, Glycine, Glycochenodeoxycholic_acid, Glycochenodeoxycholic_acid, Glycochenodeoxycholic_acid, Glycocholic_acid, Hippuric_acid, His_His, Hydrocortisone, Hypoxanthine, Cholic_Acid, Ibuprofen_metabolite_B, Ile_Glu, Indole_3_acrylic_acid, Indole_3_lactic_acid, Indole_3_lactic_acid, Inosine, Isocitric_acid, Kynurenic_acid, L_Malic_acid, L_Lactic_acid, L_Ascorbic_acid_2_sulfate, L_Histidine, L_isoleucine, L_Ornithine, LPE_16_0, LPE_18_1, LPE_22_6, L_Tyrosine, Met_Glu, Methyl_4_cyano_3_[2_1_cyano_2_ethoxy_2_oxoethylidene_hydrazino]thiophene_2_carboxylate, N4_Acetylcytidine, N6_Succinyladenosine_LC_tDDA_CE20, N_Acetyl_carnosine, N_Acetylalanine, N_Acetyl_L_aspartic_acid, N_Acetyl_L_methionine, N_Acetyl_L_phenylalanine, N_Acetyl_threonine_LC_tDDA_CE10, N_Formylmethionine, Nimesulide, N_Isovalerylglycine, Perfluoro_1_butanesulfonic_acid_PFBS, Phe_Lys_Tyr, Phenol, Phenylacetylglutamine, P_hydroxybenzoic_acid, P_Hydroxyphenylacetic_acid, Pyruvic_acid, Saccharin, Salicyluric_acid, Ser_Glu, Ser_Leu_Tyr, Succinic_acid, Tetradecanedioic_acid, Theophylline, UKOUEEGEHXWHHO_MOFOKWOHSA_N, Undecylenic_acid, Uric_acid, Uridine, Xanthine, Β_Muricholic_acid

In [161]:
# Find special characters if still present in column names
special_characters = sorted(set(
    char
    for col in df.columns
    for char in col
    if not char.isalnum() and char != "_"
))

print("Remaining special characters:")
print(special_characters)

Remaining special characters:
["'", ',', '/', '[', ']']

In [162]:
# Remove remaining special characters
# Replace remaining special characters with underscores
df.columns = [
    col.replace("'", "_")
       .replace(",", "_")
       .replace("/", "_")
       .replace("[", "_")
       .replace("]", "_")
    for col in df.columns
]

# Reduce multiple underscores to a single underscore
df.columns = [
    re.sub(r"_+", "_", col).strip("_")
    for col in df.columns
]

# Display all column names for verification
print(", ".join(df.columns))

Treatment, Participant_ID, Measurement_Time, Gender, Phototype, Age, Alanin, Arginine, Asparagine, Citruline, Fenylalanin, Glutamic_acid, Glutamin, Glycine, Histidin, Isoleucine, Aspartic_Acid, Leucine, Lysin, Methionine, Ornithine, Proline, Pyrrolidone_carboxylic_acid, Serine, Threonine, Tryptofan, Tyrosine, Urea, Valin, NMF, Total_urocanic_acid, Trans_Urocanic_acid, Hydration_forehead, Hydration_cheek, Hydration_forearm, TEWL_forehead, TEWL_Cheek, Sebum_forehead, Sebum_cheek, Wrinkle, Red_Area_forehead, Red_Area_cheek, Pores_Area_forehead, Pores_Area_cheek, GLOSS_forehead, GLOSS_Cheek, GLOSS_DCS_forehead, GLOSS_DCS_cheek, MEXA_Melanin_forehead, MEXA_Melanin_cheek, MEXA_Erythema_forehead, MEXA_Erythema_cheek, ITA_forehead, ITA_cheek, A_value_forehead, A_value_cheek, B_value_forehead, B_value_cheek, Elasticity_R0_forehead, Elasticity_R0_cheek, Elasticity_R1_forehead, Elasticity_R1_cheek, Elasticity_R2_forehead, Elasticity_R2_cheek, Elasticity_R3_forehead, Elasticity_R3_cheek, Elasticity_R4_forehead, Elasticity_R4_cheek, Elasticity_R5_forehead, Elasticity_R5_cheek, Elasticity_R6_forehead, Elasticity_R6_cheek, Elasticity_R7_forehead, Elasticity_R7_cheek, Elasticity_R8_forehead, Elasticity_R8_cheek, Elasticity_R9_forehead, Elasticity_R9_cheek, Elasticity_F0_forehead, Elasticity_F0_cheek, Elasticity_F1_forehead, Elasticity_F1_cheek, Elasticity_R1_R4_forehead, Elasticity_R1_R4_cheek, Elasticity_R3_R9_forehead, Elasticity_R3_R9_cheek, Epidermal_thickness, Dermal_density, CAR_12_0, CAR_12_1, CAR_12_2, CAR_13_0, CAR_14_1, CAR_14_2, CAR_14_3, CAR_16_0, CAR_16_1, CAR_16_2, CAR_16_3, CAR_18_1, CAR_18_2, CAR_18_3, CAR_20_1, CAR_20_2, CAR_22_0, CAR_24_1, CAR_26_0, CE_16_1, CE_17_0, CE_18_1, CE_18_2, CE_18_3, CE_20_3, CE_20_4, CE_20_5, CE_22_6, Cer_34_1_NS_neg, Cer_38_1_2O, Cer_38_1_NS_neg, Cer_40_0_2O, Cer_40_0_2O_neg, Cer_40_1_2O, Cer_40_1_NS_neg, Cer_40_2_2O, Cer_40_2_NS_neg, Cer_41_0_2O, Cer_41_1_2O, Cer_41_1_NS_neg, Cer_41_2_2O, Cer_42_0_2O, Cer_42_0_2O_neg, Cer_42_1_2O_neg, Cer_42_1_2O_1, Cer_42_1_2O_2, Cer_42_2_2O, Cer_42_2_NS_neg, Cer_42_3_2O, Cer_42_3_2O_neg, Cer_43_1_2O, Cer_43_1_2O_neg, Cer_43_2_2O, Cer_44_1_2O_neg, DG_36_2, FA_14_0, FA_14_1, FA_16_0, FA_16_1, FA_16_3, FA_18_1, FA_18_2, FA_18_3, FA_19_1, FA_20_1, FA_20_2, FA_20_3, FA_20_4, FA_20_5, FA_22_1, FA_22_2, FA_22_3, FA_22_4, FA_22_5, FA_22_6, FA_24_1, FA_24_2, FA_24_4, FA_24_5, FA_26_3, FA_34_0, FAHFA_24_3, FAHFA_36_1, FAHFA_38_2, FAHFA_38_4, FAHFA_40_3, FAHFA_40_4, FC, GM3_32_1_2O_neg, GM3_40_1_2O_neg, GM3_42_1_2O_neg, GM3_42_2_2O_neg, Hex2Cer_34_1_2O_neg, Hex3Cer_34_1_2O, Hex3Cer_40_1_2O, HexCer_34_0_3O_2OH_neg, HexCer_34_1_2O_neg, HexCer_36_1_2O_neg, HexCer_38_1_2O_neg, HexCer_40_1_2O, HexCer_40_1_2O_neg, HexCer_40_2_2O_neg, HexCer_41_1_2O_neg, HexCer_41_2_2O_neg, HexCer_42_1_2O, HexCer_42_1_2O_neg, HexCer_42_2_2O_neg, HexCer_42_3_2O_neg, LNAPE_36_4, LPC_12_0, LPC_14_1, LPC_16_1, LPC_16_2, LPC_17_0, LPC_17_1, LPC_18_0, LPC_18_1, LPC_18_2, LPC_19_0, LPC_19_1, LPC_20_0, LPC_20_1, LPC_20_2, LPC_20_3, LPC_20_4, LPC_22_0, LPC_22_1, LPC_22_3, LPC_22_5, LPC_22_6, LPC_24_0, LPC_24_5, LPC_26_1, LPC_O_16_0, LPC_O_16_1, LPC_O_17_0, LPC_O_18_1, LPC_O_20_0, LPC_O_22_1, LPC_O_26_2, LPE_16_0, LPE_18_0, LPE_18_1, LPE_20_3, LPE_20_5, LPE_22_5, LPE_22_6, LPE_O_16_1, LPE_O_18_2, LPI_18_0, LPI_18_2, LPI_20_3, LPI_20_4, PC_24_0, PC_26_0, PC_28_0, PC_28_1, PC_30_0, PC_30_1, PC_31_1, PC_31_2, PC_32_0, PC_32_1, PC_32_2, PC_32_3, PC_33_0, PC_33_1, PC_33_2, PC_33_4, PC_34_2, PC_34_3, PC_34_4, PC_34_5, PC_35_0, PC_35_1, PC_35_2, PC_35_3, PC_35_4, PC_35_5, PC_36_0, PC_36_1, PC_36_2, PC_36_3, PC_36_4, PC_36_5, PC_36_6, PC_36_7, PC_37_2, PC_37_4, PC_37_5, PC_37_6, PC_37_7, PC_38_1, PC_38_2, PC_38_3, PC_38_5, PC_38_6, PC_38_7, PC_38_8, PC_38_9, PC_39_1, PC_39_3, PC_39_5, PC_39_6, PC_39_7, PC_40_1, PC_40_2, PC_40_3, PC_40_4, PC_40_5, PC_40_6, PC_40_7, PC_40_8, PC_40_9, PC_42_10, PC_42_5, PC_42_7, PC_44_4, PC_44_5, PC_O_30_0, PC_O_31_1, PC_O_32_0, PC_O_32_1, PC_O_33_2, PC_O_34_0, PC_O_34_1, PC_O_34_2, PC_O_34_3, PC_O_34_4, PC_O_35_4, PC_O_35_6, PC_O_35_7, PC_O_36_0, PC_O_36_2, PC_O_36_3, PC_O_36_4, PC_O_36_5, PC_O_36_6, PC_O_37_6, PC_O_37_7, PC_O_38_0, PC_O_38_4, PC_O_38_5, PC_O_38_6, PC_O_38_7, PC_O_39_6, PC_O_40_2, PC_O_40_3, PC_O_40_5, PC_O_40_6, PC_O_40_7, PC_O_42_1, PC_O_42_2, PC_O_42_3, PC_O_42_4, PC_O_42_5, PC_O_42_6, PC_O_44_5, PC_O_44_6, PC_O_44_7, PC_O_46_5, PC_O_46_6, PC_O_46_7, PC_O_46_8, PE_32_1, PE_34_1, PE_34_2, PE_34_3, PE_36_1, PE_36_2, PE_36_3, PE_36_4, PE_38_4, PE_38_6, PE_O_34_2, PE_O_34_3, PE_O_36_2, PE_O_36_3, PE_O_36_4, PE_O_36_5, PE_O_36_6, PE_O_36_7, PE_O_37_5, PE_O_37_6, PE_O_38_2, PE_O_38_3, PE_O_38_4, PE_O_38_5, PE_O_38_6, PE_O_38_7, PE_O_39_6, PE_O_39_7, PE_O_40_7, PE_O_40_8, PE_O_40_9, PE_O_42_7, PE_O_42_8, PG_34_2, PG_36_2, PI_32_1, PI_34_1, PI_36_1, PI_36_2, PI_36_4, PI_37_4, PI_38_2, PI_38_3, PI_38_4, PI_40_5, PI_40_6, SM_29_1_2O, SM_30_0_2O, SM_30_1_2O_1, SM_30_1_2O_2, SM_31_1_2O, SM_32_0_2O, SM_32_1_2O, SM_32_2_2O_1, SM_32_2_2O_2, SM_33_1_2O_1, SM_33_1_2O_2, SM_33_2_2O, SM_34_0_2O, SM_34_1_2O_1, SM_34_1_3O_2, SM_34_2_2O_1, SM_34_2_2O_2, SM_34_3_2O, SM_35_1_2O, SM_36_0_2O, SM_36_2_2O, SM_36_3_2O, SM_37_1_2O, SM_38_0_2O, SM_38_1_2O_1, SM_38_1_2O_2, SM_38_2_2O, SM_38_3_2O, SM_38_4_2O, SM_39_0_2O, SM_39_1_2O_1, SM_39_1_2O_2, SM_39_1_2O_3, SM_39_2_2O, SM_40_0_2O, SM_40_1_2O_1, SM_40_1_2O_2, SM_40_2_2O_1, SM_40_2_2O_2, SM_40_3_2O, SM_41_0_2O, SM_41_1_2O_1, SM_41_1_2O_2, SM_41_1_2O_3, SM_41_2_2O_1, SM_41_2_2O_2, SM_42_1_2O_1, SM_42_1_2O_2, SM_42_2_2O_1, SM_42_2_2O_2, SM_42_2_2O_3, SM_42_3_2O, SM_42_4_2O, SM_42_5_2O, SM_43_1_2O_1, SM_43_1_2O_2, SM_43_2_2O_1, SM_43_2_2O_2, SM_43_2_2O_3, SM_43_3_2O, SM_44_1_2O, SM_44_2_2O, SM_44_3_2O, TG_34_0, TG_36_0, TG_40_0, TG_42_0, TG_42_1, TG_42_2_1, TG_42_2_2, TG_44_0, TG_44_1_1, TG_44_1_2, TG_44_2_1, TG_44_2_2, TG_44_3, TG_45_1, TG_45_2, TG_46_0, TG_46_1, TG_46_2, TG_46_3_1, TG_46_3_2, TG_46_3_3, TG_47_1, TG_47_2, TG_47_3, TG_48_1, TG_48_2, TG_48_3_1, TG_48_3_2, TG_48_3_3, TG_48_4, TG_48_5, TG_49_0, TG_49_1, TG_49_2, TG_49_3, TG_49_4, TG_49_5, TG_50_0, TG_50_1, TG_50_1, TG_50_2, TG_50_3, TG_50_4_1, TG_50_4_2, TG_50_5, TG_50_6, TG_51_0, TG_51_1, TG_51_2, TG_51_3, TG_51_4, TG_52_1, TG_52_2, TG_52_3, TG_52_4_1, TG_52_4_2, TG_52_5_1, TG_52_5_2, TG_52_6_1, TG_52_6_2, TG_52_7, TG_53_1, TG_53_2, TG_53_3_1, TG_53_3_2, TG_53_4, TG_53_5, TG_54_1, TG_54_2_1, TG_54_2_2, TG_54_3, TG_54_4, TG_54_5, TG_54_6, TG_54_7, TG_54_8, TG_55_2_1, TG_55_2_2, TG_55_3, TG_55_4, TG_55_6, TG_55_7, TG_56_1_1, TG_56_1_2, TG_56_10, TG_56_2_1, TG_56_2_2, TG_56_3_1, TG_56_3_2, TG_56_4_1, TG_56_4_2, TG_56_5_1, TG_56_5_2, TG_56_6, TG_56_7, TG_56_8, TG_56_9_1, TG_56_9_2, TG_57_11, TG_57_2, TG_57_3, TG_57_4, TG_57_6, TG_57_8, TG_58_1, TG_58_10, TG_58_11, TG_58_12, TG_58_2, TG_58_3, TG_58_4, TG_58_5, TG_58_6, TG_58_7, TG_58_8, TG_58_9_1, TG_58_9_2, TG_59_11, TG_59_12, TG_59_2, TG_59_3, TG_60_1, TG_60_10, TG_60_11, TG_60_12, TG_60_13, TG_60_2, TG_60_3_1, TG_60_3_2, TG_60_4, TG_60_5, TG_60_6, TG_60_7, TG_60_8, TG_60_9, TG_61_1, TG_61_2, TG_61_3, TG_61_4, TG_62_1, TG_62_11, TG_62_12, TG_62_13_1, TG_62_13_2, TG_62_14, TG_62_2, TG_62_3, TG_62_4_1, TG_62_4_2, TG_62_5, TG_63_2, TG_64_1, TG_64_2, TG_64_4, TG_66_3, TG_O_50_1, TG_O_52_1, TG_O_52_2, TG_O_58_3, MDA, 12_13_diHOME, 13_HODE, 9_HODE, 5_HETE, EPA, DHA, Arachidonic_acid, CRP, Fetuin_A, Adipsin, GLP1_total, Glucagon, TNFa, EGF, FGF2, IFNg, IL1b, IL1RA, IL10, IL17A, C_peptide, IL6, Leptin, MCP1, 14_15_DiHET, 4E_6E_2_7_dimethyl_8_2R_3R_4S_5S_6R_3_4_5_trihydroxy_6_hydroxymethyl_oxan_2_yl_oxyocta_4_6_dienoic_acid, 4E_7E_dodeca_4_7_dienedioic_acid, E_6_hydroxyoctadec_4_enoic_acid, Z_3_hydroxydodec_5_enoic_acid, 1_16_Hexadecanedioic_acid, 1_3_Dimethyluric_acid, 1_7_Dimethyluric_acid, 10_HDA, 16_Hydroxyhexadecanoic_acid, 1_Methyluric_acid, 1_Methylxanthine, 2_4_Hydroxyphenyl_propanoic_acid, 2_ALPHA_D_MANNOPYRANOSYL_L_TRYPTOPHAN, 2_4_Dinitrophenol, 2_5_Dihydroxybenzenesulfonic_Acid, 2_6_Dihydroxybenzoic_acid, 2_Furoic_acid, 2_Furoylglycine, 2_Hydroxyhippuric_acid, 2_Hydroxyisobutyric_acid, 2_Hydroxyisobutyric_acid, 2_Methyl_4_6_dinitrophenol, 3_1_Pyrazolyl_alanine, 3_Allyl_2_hydroxybenzoic_acid, 3_FUROIC_ACID, 3_Hydroxybutyric_acid, 3_Hydroxydecanoic_acid, 3_Indoxyl_sulphate, 3_Indoxyl_sulphate, 3_Methoxysalicylic_acid, 3_Methoxytyrosine, 3_Methyl_2_oxovaleric_acid_calcium_salt, 3_Methylxanthine, 3_Phenyllactic_acid, 4_Acetamidobutanoic_acid, 4_Hydroxy_3_methoxyphenylglycol_sulfate, 4_Hydroxy_3_oxo_4_propan_2_ylcyclohexene_1_carboxylic_acid, 4_Hydroxyhippuric_acid_sulfate, 4_Chlorophenoxyacetic_acid, 4_Methoxymelilotic_acid, 4_Methylphenol, 4_Oxoproline, 4_Phenolsulfonic_acid, 4_Pyridoxic_acid, 5_Aminolevulinic_acid, Acetaminophen_glucuronide, Adenosine_3_5_cyclic_monophosphate, Adenosine_5_monophosphate, Beta_D_N_Acetylmannosamine, Catechol, Citric_acid, Citrulline, CMPF, CMPF, D_Glutamine, D_Tryptophan, Decanoic_acid, Deoxycholic_acid, D_Glucose, DL_4_Hydroxyphenyllactic_acid, DL_Arginine, DL_Lactic_Acid, Dodecanedioic_acid, D_Panthenol, D_Pantothenic_acid, D_Threonine, Epinephrine, Erdosteine, Gluconic_acid, Glu_Leu, Glu_Leu_Ser, Glu_Phe, Glu_Pro, Glu_Tyr, Glu_Val, Glycine, Glycochenodeoxycholic_acid, Glycochenodeoxycholic_acid, Glycochenodeoxycholic_acid, Glycocholic_acid, Hippuric_acid, His_His, Hydrocortisone, Hypoxanthine, Cholic_Acid, Ibuprofen_metabolite_B, Ile_Glu, Indole_3_acrylic_acid, Indole_3_lactic_acid, Indole_3_lactic_acid, Inosine, Isocitric_acid, Kynurenic_acid, L_Malic_acid, L_Lactic_acid, L_Ascorbic_acid_2_sulfate, L_Histidine, L_isoleucine, L_Ornithine, LPE_16_0, LPE_18_1, LPE_22_6, L_Tyrosine, Met_Glu, Methyl_4_cyano_3_2_1_cyano_2_ethoxy_2_oxoethylidene_hydrazino_thiophene_2_carboxylate, N4_Acetylcytidine, N6_Succinyladenosine_LC_tDDA_CE20, N_Acetyl_carnosine, N_Acetylalanine, N_Acetyl_L_aspartic_acid, N_Acetyl_L_methionine, N_Acetyl_L_phenylalanine, N_Acetyl_threonine_LC_tDDA_CE10, N_Formylmethionine, Nimesulide, N_Isovalerylglycine, Perfluoro_1_butanesulfonic_acid_PFBS, Phe_Lys_Tyr, Phenol, Phenylacetylglutamine, P_hydroxybenzoic_acid, P_Hydroxyphenylacetic_acid, Pyruvic_acid, Saccharin, Salicyluric_acid, Ser_Glu, Ser_Leu_Tyr, Succinic_acid, Tetradecanedioic_acid, Theophylline, UKOUEEGEHXWHHO_MOFOKWOHSA_N, Undecylenic_acid, Uric_acid, Uridine, Xanthine, Β_Muricholic_acid

#### Variables Starting With Numbers
Some variable names in the dataset start with a number. Since Python variable names cannot start with a number, let's first identify these column names before deciding how to standardize them.

In [164]:
# Find column names that start with a number 
numeric_start_columns = [ col for col in df.columns if col[0].isdigit() ] 
print("Variables starting with a number:") 
print(numeric_start_columns)

Variables starting with a number:
['12_13_diHOME', '13_HODE', '9_HODE', '5_HETE', '14_15_DiHET', '4E_6E_2_7_dimethyl_8_2R_3R_4S_5S_6R_3_4_5_trihydroxy_6_hydroxymethyl_oxan_2_yl_oxyocta_4_6_dienoic_acid', '4E_7E_dodeca_4_7_dienedioic_acid', '1_16_Hexadecanedioic_acid', '1_3_Dimethyluric_acid', '1_7_Dimethyluric_acid', '10_HDA', '16_Hydroxyhexadecanoic_acid', '1_Methyluric_acid', '1_Methylxanthine', '2_4_Hydroxyphenyl_propanoic_acid', '2_ALPHA_D_MANNOPYRANOSYL_L_TRYPTOPHAN', '2_4_Dinitrophenol', '2_5_Dihydroxybenzenesulfonic_Acid', '2_6_Dihydroxybenzoic_acid', '2_Furoic_acid', '2_Furoylglycine', '2_Hydroxyhippuric_acid', '2_Hydroxyisobutyric_acid', '2_Hydroxyisobutyric_acid', '2_Methyl_4_6_dinitrophenol', '3_1_Pyrazolyl_alanine', '3_Allyl_2_hydroxybenzoic_acid', '3_FUROIC_ACID', '3_Hydroxybutyric_acid', '3_Hydroxydecanoic_acid', '3_Indoxyl_sulphate', '3_Indoxyl_sulphate', '3_Methoxysalicylic_acid', '3_Methoxytyrosine', '3_Methyl_2_oxovaleric_acid_calcium_salt', '3_Methylxanthine', '3_Phenyllactic_acid', '4_Acetamidobutanoic_acid', '4_Hydroxy_3_methoxyphenylglycol_sulfate', '4_Hydroxy_3_oxo_4_propan_2_ylcyclohexene_1_carboxylic_acid', '4_Hydroxyhippuric_acid_sulfate', '4_Chlorophenoxyacetic_acid', '4_Methoxymelilotic_acid', '4_Methylphenol', '4_Oxoproline', '4_Phenolsulfonic_acid', '4_Pyridoxic_acid', '5_Aminolevulinic_acid']

#### Since these columns represent metabolites, we can add M_ to the beginning of each metabolite variable while preserving the original metabolite name.
For example:
- 12_13_diHOME → M_12_13_diHOME.
- 5_HETE → M_5_HETE.
- 1_Methyluric_acid → M_1_Methyluric_acid.

In [165]:
# Add "M_" to metabolite variables that start with a number 

df.columns = [ "M_" + col if col[0].isdigit() else col for col in df.columns ] 

# Display all column names for verification 

print(", ".join(df.columns))

Treatment, Participant_ID, Measurement_Time, Gender, Phototype, Age, Alanin, Arginine, Asparagine, Citruline, Fenylalanin, Glutamic_acid, Glutamin, Glycine, Histidin, Isoleucine, Aspartic_Acid, Leucine, Lysin, Methionine, Ornithine, Proline, Pyrrolidone_carboxylic_acid, Serine, Threonine, Tryptofan, Tyrosine, Urea, Valin, NMF, Total_urocanic_acid, Trans_Urocanic_acid, Hydration_forehead, Hydration_cheek, Hydration_forearm, TEWL_forehead, TEWL_Cheek, Sebum_forehead, Sebum_cheek, Wrinkle, Red_Area_forehead, Red_Area_cheek, Pores_Area_forehead, Pores_Area_cheek, GLOSS_forehead, GLOSS_Cheek, GLOSS_DCS_forehead, GLOSS_DCS_cheek, MEXA_Melanin_forehead, MEXA_Melanin_cheek, MEXA_Erythema_forehead, MEXA_Erythema_cheek, ITA_forehead, ITA_cheek, A_value_forehead, A_value_cheek, B_value_forehead, B_value_cheek, Elasticity_R0_forehead, Elasticity_R0_cheek, Elasticity_R1_forehead, Elasticity_R1_cheek, Elasticity_R2_forehead, Elasticity_R2_cheek, Elasticity_R3_forehead, Elasticity_R3_cheek, Elasticity_R4_forehead, Elasticity_R4_cheek, Elasticity_R5_forehead, Elasticity_R5_cheek, Elasticity_R6_forehead, Elasticity_R6_cheek, Elasticity_R7_forehead, Elasticity_R7_cheek, Elasticity_R8_forehead, Elasticity_R8_cheek, Elasticity_R9_forehead, Elasticity_R9_cheek, Elasticity_F0_forehead, Elasticity_F0_cheek, Elasticity_F1_forehead, Elasticity_F1_cheek, Elasticity_R1_R4_forehead, Elasticity_R1_R4_cheek, Elasticity_R3_R9_forehead, Elasticity_R3_R9_cheek, Epidermal_thickness, Dermal_density, CAR_12_0, CAR_12_1, CAR_12_2, CAR_13_0, CAR_14_1, CAR_14_2, CAR_14_3, CAR_16_0, CAR_16_1, CAR_16_2, CAR_16_3, CAR_18_1, CAR_18_2, CAR_18_3, CAR_20_1, CAR_20_2, CAR_22_0, CAR_24_1, CAR_26_0, CE_16_1, CE_17_0, CE_18_1, CE_18_2, CE_18_3, CE_20_3, CE_20_4, CE_20_5, CE_22_6, Cer_34_1_NS_neg, Cer_38_1_2O, Cer_38_1_NS_neg, Cer_40_0_2O, Cer_40_0_2O_neg, Cer_40_1_2O, Cer_40_1_NS_neg, Cer_40_2_2O, Cer_40_2_NS_neg, Cer_41_0_2O, Cer_41_1_2O, Cer_41_1_NS_neg, Cer_41_2_2O, Cer_42_0_2O, Cer_42_0_2O_neg, Cer_42_1_2O_neg, Cer_42_1_2O_1, Cer_42_1_2O_2, Cer_42_2_2O, Cer_42_2_NS_neg, Cer_42_3_2O, Cer_42_3_2O_neg, Cer_43_1_2O, Cer_43_1_2O_neg, Cer_43_2_2O, Cer_44_1_2O_neg, DG_36_2, FA_14_0, FA_14_1, FA_16_0, FA_16_1, FA_16_3, FA_18_1, FA_18_2, FA_18_3, FA_19_1, FA_20_1, FA_20_2, FA_20_3, FA_20_4, FA_20_5, FA_22_1, FA_22_2, FA_22_3, FA_22_4, FA_22_5, FA_22_6, FA_24_1, FA_24_2, FA_24_4, FA_24_5, FA_26_3, FA_34_0, FAHFA_24_3, FAHFA_36_1, FAHFA_38_2, FAHFA_38_4, FAHFA_40_3, FAHFA_40_4, FC, GM3_32_1_2O_neg, GM3_40_1_2O_neg, GM3_42_1_2O_neg, GM3_42_2_2O_neg, Hex2Cer_34_1_2O_neg, Hex3Cer_34_1_2O, Hex3Cer_40_1_2O, HexCer_34_0_3O_2OH_neg, HexCer_34_1_2O_neg, HexCer_36_1_2O_neg, HexCer_38_1_2O_neg, HexCer_40_1_2O, HexCer_40_1_2O_neg, HexCer_40_2_2O_neg, HexCer_41_1_2O_neg, HexCer_41_2_2O_neg, HexCer_42_1_2O, HexCer_42_1_2O_neg, HexCer_42_2_2O_neg, HexCer_42_3_2O_neg, LNAPE_36_4, LPC_12_0, LPC_14_1, LPC_16_1, LPC_16_2, LPC_17_0, LPC_17_1, LPC_18_0, LPC_18_1, LPC_18_2, LPC_19_0, LPC_19_1, LPC_20_0, LPC_20_1, LPC_20_2, LPC_20_3, LPC_20_4, LPC_22_0, LPC_22_1, LPC_22_3, LPC_22_5, LPC_22_6, LPC_24_0, LPC_24_5, LPC_26_1, LPC_O_16_0, LPC_O_16_1, LPC_O_17_0, LPC_O_18_1, LPC_O_20_0, LPC_O_22_1, LPC_O_26_2, LPE_16_0, LPE_18_0, LPE_18_1, LPE_20_3, LPE_20_5, LPE_22_5, LPE_22_6, LPE_O_16_1, LPE_O_18_2, LPI_18_0, LPI_18_2, LPI_20_3, LPI_20_4, PC_24_0, PC_26_0, PC_28_0, PC_28_1, PC_30_0, PC_30_1, PC_31_1, PC_31_2, PC_32_0, PC_32_1, PC_32_2, PC_32_3, PC_33_0, PC_33_1, PC_33_2, PC_33_4, PC_34_2, PC_34_3, PC_34_4, PC_34_5, PC_35_0, PC_35_1, PC_35_2, PC_35_3, PC_35_4, PC_35_5, PC_36_0, PC_36_1, PC_36_2, PC_36_3, PC_36_4, PC_36_5, PC_36_6, PC_36_7, PC_37_2, PC_37_4, PC_37_5, PC_37_6, PC_37_7, PC_38_1, PC_38_2, PC_38_3, PC_38_5, PC_38_6, PC_38_7, PC_38_8, PC_38_9, PC_39_1, PC_39_3, PC_39_5, PC_39_6, PC_39_7, PC_40_1, PC_40_2, PC_40_3, PC_40_4, PC_40_5, PC_40_6, PC_40_7, PC_40_8, PC_40_9, PC_42_10, PC_42_5, PC_42_7, PC_44_4, PC_44_5, PC_O_30_0, PC_O_31_1, PC_O_32_0, PC_O_32_1, PC_O_33_2, PC_O_34_0, PC_O_34_1, PC_O_34_2, PC_O_34_3, PC_O_34_4, PC_O_35_4, PC_O_35_6, PC_O_35_7, PC_O_36_0, PC_O_36_2, PC_O_36_3, PC_O_36_4, PC_O_36_5, PC_O_36_6, PC_O_37_6, PC_O_37_7, PC_O_38_0, PC_O_38_4, PC_O_38_5, PC_O_38_6, PC_O_38_7, PC_O_39_6, PC_O_40_2, PC_O_40_3, PC_O_40_5, PC_O_40_6, PC_O_40_7, PC_O_42_1, PC_O_42_2, PC_O_42_3, PC_O_42_4, PC_O_42_5, PC_O_42_6, PC_O_44_5, PC_O_44_6, PC_O_44_7, PC_O_46_5, PC_O_46_6, PC_O_46_7, PC_O_46_8, PE_32_1, PE_34_1, PE_34_2, PE_34_3, PE_36_1, PE_36_2, PE_36_3, PE_36_4, PE_38_4, PE_38_6, PE_O_34_2, PE_O_34_3, PE_O_36_2, PE_O_36_3, PE_O_36_4, PE_O_36_5, PE_O_36_6, PE_O_36_7, PE_O_37_5, PE_O_37_6, PE_O_38_2, PE_O_38_3, PE_O_38_4, PE_O_38_5, PE_O_38_6, PE_O_38_7, PE_O_39_6, PE_O_39_7, PE_O_40_7, PE_O_40_8, PE_O_40_9, PE_O_42_7, PE_O_42_8, PG_34_2, PG_36_2, PI_32_1, PI_34_1, PI_36_1, PI_36_2, PI_36_4, PI_37_4, PI_38_2, PI_38_3, PI_38_4, PI_40_5, PI_40_6, SM_29_1_2O, SM_30_0_2O, SM_30_1_2O_1, SM_30_1_2O_2, SM_31_1_2O, SM_32_0_2O, SM_32_1_2O, SM_32_2_2O_1, SM_32_2_2O_2, SM_33_1_2O_1, SM_33_1_2O_2, SM_33_2_2O, SM_34_0_2O, SM_34_1_2O_1, SM_34_1_3O_2, SM_34_2_2O_1, SM_34_2_2O_2, SM_34_3_2O, SM_35_1_2O, SM_36_0_2O, SM_36_2_2O, SM_36_3_2O, SM_37_1_2O, SM_38_0_2O, SM_38_1_2O_1, SM_38_1_2O_2, SM_38_2_2O, SM_38_3_2O, SM_38_4_2O, SM_39_0_2O, SM_39_1_2O_1, SM_39_1_2O_2, SM_39_1_2O_3, SM_39_2_2O, SM_40_0_2O, SM_40_1_2O_1, SM_40_1_2O_2, SM_40_2_2O_1, SM_40_2_2O_2, SM_40_3_2O, SM_41_0_2O, SM_41_1_2O_1, SM_41_1_2O_2, SM_41_1_2O_3, SM_41_2_2O_1, SM_41_2_2O_2, SM_42_1_2O_1, SM_42_1_2O_2, SM_42_2_2O_1, SM_42_2_2O_2, SM_42_2_2O_3, SM_42_3_2O, SM_42_4_2O, SM_42_5_2O, SM_43_1_2O_1, SM_43_1_2O_2, SM_43_2_2O_1, SM_43_2_2O_2, SM_43_2_2O_3, SM_43_3_2O, SM_44_1_2O, SM_44_2_2O, SM_44_3_2O, TG_34_0, TG_36_0, TG_40_0, TG_42_0, TG_42_1, TG_42_2_1, TG_42_2_2, TG_44_0, TG_44_1_1, TG_44_1_2, TG_44_2_1, TG_44_2_2, TG_44_3, TG_45_1, TG_45_2, TG_46_0, TG_46_1, TG_46_2, TG_46_3_1, TG_46_3_2, TG_46_3_3, TG_47_1, TG_47_2, TG_47_3, TG_48_1, TG_48_2, TG_48_3_1, TG_48_3_2, TG_48_3_3, TG_48_4, TG_48_5, TG_49_0, TG_49_1, TG_49_2, TG_49_3, TG_49_4, TG_49_5, TG_50_0, TG_50_1, TG_50_1, TG_50_2, TG_50_3, TG_50_4_1, TG_50_4_2, TG_50_5, TG_50_6, TG_51_0, TG_51_1, TG_51_2, TG_51_3, TG_51_4, TG_52_1, TG_52_2, TG_52_3, TG_52_4_1, TG_52_4_2, TG_52_5_1, TG_52_5_2, TG_52_6_1, TG_52_6_2, TG_52_7, TG_53_1, TG_53_2, TG_53_3_1, TG_53_3_2, TG_53_4, TG_53_5, TG_54_1, TG_54_2_1, TG_54_2_2, TG_54_3, TG_54_4, TG_54_5, TG_54_6, TG_54_7, TG_54_8, TG_55_2_1, TG_55_2_2, TG_55_3, TG_55_4, TG_55_6, TG_55_7, TG_56_1_1, TG_56_1_2, TG_56_10, TG_56_2_1, TG_56_2_2, TG_56_3_1, TG_56_3_2, TG_56_4_1, TG_56_4_2, TG_56_5_1, TG_56_5_2, TG_56_6, TG_56_7, TG_56_8, TG_56_9_1, TG_56_9_2, TG_57_11, TG_57_2, TG_57_3, TG_57_4, TG_57_6, TG_57_8, TG_58_1, TG_58_10, TG_58_11, TG_58_12, TG_58_2, TG_58_3, TG_58_4, TG_58_5, TG_58_6, TG_58_7, TG_58_8, TG_58_9_1, TG_58_9_2, TG_59_11, TG_59_12, TG_59_2, TG_59_3, TG_60_1, TG_60_10, TG_60_11, TG_60_12, TG_60_13, TG_60_2, TG_60_3_1, TG_60_3_2, TG_60_4, TG_60_5, TG_60_6, TG_60_7, TG_60_8, TG_60_9, TG_61_1, TG_61_2, TG_61_3, TG_61_4, TG_62_1, TG_62_11, TG_62_12, TG_62_13_1, TG_62_13_2, TG_62_14, TG_62_2, TG_62_3, TG_62_4_1, TG_62_4_2, TG_62_5, TG_63_2, TG_64_1, TG_64_2, TG_64_4, TG_66_3, TG_O_50_1, TG_O_52_1, TG_O_52_2, TG_O_58_3, MDA, M_12_13_diHOME, M_13_HODE, M_9_HODE, M_5_HETE, EPA, DHA, Arachidonic_acid, CRP, Fetuin_A, Adipsin, GLP1_total, Glucagon, TNFa, EGF, FGF2, IFNg, IL1b, IL1RA, IL10, IL17A, C_peptide, IL6, Leptin, MCP1, M_14_15_DiHET, M_4E_6E_2_7_dimethyl_8_2R_3R_4S_5S_6R_3_4_5_trihydroxy_6_hydroxymethyl_oxan_2_yl_oxyocta_4_6_dienoic_acid, M_4E_7E_dodeca_4_7_dienedioic_acid, E_6_hydroxyoctadec_4_enoic_acid, Z_3_hydroxydodec_5_enoic_acid, M_1_16_Hexadecanedioic_acid, M_1_3_Dimethyluric_acid, M_1_7_Dimethyluric_acid, M_10_HDA, M_16_Hydroxyhexadecanoic_acid, M_1_Methyluric_acid, M_1_Methylxanthine, M_2_4_Hydroxyphenyl_propanoic_acid, M_2_ALPHA_D_MANNOPYRANOSYL_L_TRYPTOPHAN, M_2_4_Dinitrophenol, M_2_5_Dihydroxybenzenesulfonic_Acid, M_2_6_Dihydroxybenzoic_acid, M_2_Furoic_acid, M_2_Furoylglycine, M_2_Hydroxyhippuric_acid, M_2_Hydroxyisobutyric_acid, M_2_Hydroxyisobutyric_acid, M_2_Methyl_4_6_dinitrophenol, M_3_1_Pyrazolyl_alanine, M_3_Allyl_2_hydroxybenzoic_acid, M_3_FUROIC_ACID, M_3_Hydroxybutyric_acid, M_3_Hydroxydecanoic_acid, M_3_Indoxyl_sulphate, M_3_Indoxyl_sulphate, M_3_Methoxysalicylic_acid, M_3_Methoxytyrosine, M_3_Methyl_2_oxovaleric_acid_calcium_salt, M_3_Methylxanthine, M_3_Phenyllactic_acid, M_4_Acetamidobutanoic_acid, M_4_Hydroxy_3_methoxyphenylglycol_sulfate, M_4_Hydroxy_3_oxo_4_propan_2_ylcyclohexene_1_carboxylic_acid, M_4_Hydroxyhippuric_acid_sulfate, M_4_Chlorophenoxyacetic_acid, M_4_Methoxymelilotic_acid, M_4_Methylphenol, M_4_Oxoproline, M_4_Phenolsulfonic_acid, M_4_Pyridoxic_acid, M_5_Aminolevulinic_acid, Acetaminophen_glucuronide, Adenosine_3_5_cyclic_monophosphate, Adenosine_5_monophosphate, Beta_D_N_Acetylmannosamine, Catechol, Citric_acid, Citrulline, CMPF, CMPF, D_Glutamine, D_Tryptophan, Decanoic_acid, Deoxycholic_acid, D_Glucose, DL_4_Hydroxyphenyllactic_acid, DL_Arginine, DL_Lactic_Acid, Dodecanedioic_acid, D_Panthenol, D_Pantothenic_acid, D_Threonine, Epinephrine, Erdosteine, Gluconic_acid, Glu_Leu, Glu_Leu_Ser, Glu_Phe, Glu_Pro, Glu_Tyr, Glu_Val, Glycine, Glycochenodeoxycholic_acid, Glycochenodeoxycholic_acid, Glycochenodeoxycholic_acid, Glycocholic_acid, Hippuric_acid, His_His, Hydrocortisone, Hypoxanthine, Cholic_Acid, Ibuprofen_metabolite_B, Ile_Glu, Indole_3_acrylic_acid, Indole_3_lactic_acid, Indole_3_lactic_acid, Inosine, Isocitric_acid, Kynurenic_acid, L_Malic_acid, L_Lactic_acid, L_Ascorbic_acid_2_sulfate, L_Histidine, L_isoleucine, L_Ornithine, LPE_16_0, LPE_18_1, LPE_22_6, L_Tyrosine, Met_Glu, Methyl_4_cyano_3_2_1_cyano_2_ethoxy_2_oxoethylidene_hydrazino_thiophene_2_carboxylate, N4_Acetylcytidine, N6_Succinyladenosine_LC_tDDA_CE20, N_Acetyl_carnosine, N_Acetylalanine, N_Acetyl_L_aspartic_acid, N_Acetyl_L_methionine, N_Acetyl_L_phenylalanine, N_Acetyl_threonine_LC_tDDA_CE10, N_Formylmethionine, Nimesulide, N_Isovalerylglycine, Perfluoro_1_butanesulfonic_acid_PFBS, Phe_Lys_Tyr, Phenol, Phenylacetylglutamine, P_hydroxybenzoic_acid, P_Hydroxyphenylacetic_acid, Pyruvic_acid, Saccharin, Salicyluric_acid, Ser_Glu, Ser_Leu_Tyr, Succinic_acid, Tetradecanedioic_acid, Theophylline, UKOUEEGEHXWHHO_MOFOKWOHSA_N, Undecylenic_acid, Uric_acid, Uridine, Xanthine, Β_Muricholic_acid

## 4. Data Validation

Before starting the statistical analysis, the prepared dataset was validated to ensure that its structure and variables were appropriate for analysis.

The validation included the following checks:

1. **Participant identification**
   - Confirm the number of unique participants.
   - Check that participant IDs are correctly represented.

2. **Treatment groups**
   - Confirm the presence of the three study groups: Placebo, SH60, and SH120.
   - Check the number of records in each group.

3. **Time**
   - Confirm the available study time points.
   - Verify the distribution of records between baseline and Month 3.

4. **Duplicate records**
   - Check for duplicate participant records.
   - Verify that a participant does not have multiple records for the same time point.

5. **Missing values**
   - Assess missing values across the dataset.
   - Missing values will not be automatically removed or replaced.

6. **Data types**
   - Review whether variables have appropriate data types for statistical analysis.
   - Categorical variables will be treated as categorical variables, while quantitative measurements will be treated as numerical variables where appropriate.

7. **Data consistency**

   
   - Review the dataset for unexpected or inconsistent values and potential outliers.

In [166]:
# Check the number of rows and columns
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 296
Number of columns: 782

In [167]:
# Check participant IDs
print("Total records:", len(df))
print("Unique participants:", df["Participant_ID"].nunique())
print("Missing participant IDs:", df["Participant_ID"].isna().sum())

Total records: 296
Unique participants: 148
Missing participant IDs: 0

In [168]:
# Check measurement time points 
print("Measurement time points:") 
print(df["Measurement_Time"].value_counts(dropna=False).sort_index())

Measurement time points:
Measurement_Time
0    148
3    148
Name: count, dtype: int64

In [169]:
# Check exact duplicate rows
print("Exact duplicate rows:", df.duplicated().sum())

# Check duplicate participant-time combinations
print(
    "Duplicate participant-time records:",
    df.duplicated(
        subset=["Participant_ID", "Measurement_Time"]
    ).sum()
)

Exact duplicate rows: 0
Duplicate participant-time records: 0

Let's check the measurement times for each participant to verify that each participant has measurements at both Time 0 and Time 3.

In [171]:
# Show each participant and their measurement times
print(
    df[["Participant_ID", "Measurement_Time"]]
    .assign(Participant_ID=lambda x: x["Participant_ID"].astype(str))
    .sort_values("Participant_ID")
    .to_string(index=False)
)

Participant_ID Measurement_Time
           001                0
           001                3
           002                0
           002                3
           003                0
           003                3
           004                0
           004                3
           005                0
           005                3
           006                0
           006                3
           007                0
           007                3
           008                0
           008                3
           009                0
           009                3
           010                0
           010                3
           011                0
           011                3
           012                0
           012                3
           013                0
           013                3
           014                0
           014                3
           015                0
           015                3
           016                0
           016                3
           017                0
           017                3
           018                0
           018                3
           019                0
           019                3
           020                0
           020                3
           021                0
           021                3
           022                0
           022                3
           023                0
           023                3
           024                0
           024                3
           025                0
           025                3
           026                0
           026                3
           027                0
           027                3
           028                0
           028                3
           029                0
           029                3
           030                0
           030                3
           031                0
           031                3
           032                0
           032                3
           033                0
           033                3
           034                0
           034                3
           035                0
           035                3
           036                0
           036                3
           037                0
           037                3
           038                0
           038                3
           039                0
           039                3
           040                0
           040                3
           041                0
           041                3
           042                0
           042                3
           043                0
           043                3
           044                0
           044                3
           045                0
           045                3
           046                0
           046                3
           047                0
           047                3
           048                0
           048                3
           049                0
           049                3
           050                0
           050                3
           051                0
           051                3
           052                0
           052                3
           053                0
           053                3
           054                0
           054                3
           055                0
           055                3
           056                0
           056                3
           057                0
           057                3
           058                0
           058                3
           059                0
           059                3
           060                0
           060                3
           061                0
           061                3
           062                0
           062                3
           063                0
           063                3
           064                0
           064                3
           065                0
           065                3
           066                0
           066                3
           067                0
           067                3
           068                0
           068                3
           069                0
           069                3
           070                0
           070                3
           071                0
           071                3
           072                0
           072                3
           073                0
           073                3
           074                0
           074                3
           075                0
           075                3
           076                0
           076                3
           077                0
           077                3
           078                0
           078                3
           079                0
           079                3
           080                0
           080                3
           081                0
           081                3
           082                0
           082                3
           083                0
           083                3
           084                0
           084                3
           085                0
           085                3
           086                0
           086                3
           087                0
           087                3
           088                0
           088                3
           089                0
           089                3
           090                0
           090                3
           091                0
           091                3
           092                0
           092                3
           093                0
           093                3
           094                0
           094                3
           095                0
           095                3
           096                0
           096                3
           097                0
           097                3
           098                0
           098                3
           099                0
           099                3
           100                0
           100                3
           101                0
           101                3
           102                0
           102                3
           103                0
           103                3
           104                0
           104                3
           105                0
           105                3
           106                0
           106                3
           107                0
           107                3
           108                0
           108                3
           109                0
           109                3
           110                0
           110                3
           111                0
           111                3
           112                0
           112                3
           113                0
           113                3
           114                0
           114                3
           115                0
           115                3
           116                0
           116                3
           117                0
           117                3
           118                0
           118                3
           119                0
           119                3
           120                0
           120                3
           121                0
           121                3
           122                0
           122                3
           123                0
           123                3
           124                0
           124                3
           125                0
           125                3
           126                0
           126                3
           128                0
           128                3
           129                0
           129                3
           130                0
           130                3
           131                0
           131                3
           132                0
           132                3
           133                0
           133                3
           134                0
           134                3
           135                0
           135                3
           136                0
           136                3
           137                0
           137                3
           138                0
           138                3
           139                0
           139                3
           141                0
           141                3
           142                0
           142                3
           143                0
           143                3
           144                0
           144                3
           145                0
           145                3
           146                0
           146                3
           147                0
           147                3
           148                0
           148                3
           149                0
           149                3
           150                0
           150                3

Now we can see that the data contains participants 001–126, then 128–139, then 141–150.
So the missing participant IDs are:127 and 140
which explains the difference: 150 possible participant IDs − 2 missing IDs = 148 actual participants.
And each of the 148 participants has exactly two measurements: Time 0 and Time 3
So there is no problem with the repeated-measures structure based on this output. The IDs 127 and 140 simply do not appear in the dataset.

In [ ]:
# Check for duplicated column names
duplicate_columns = df.columns[df.columns.duplicated()]

print("Number of duplicated column names:", len(duplicate_columns))
print("Duplicated column names:")
print(duplicate_columns.tolist())

In [172]:
# Count every occurrence of each column name
column_counts = {}

for col in df.columns:
    column_counts[col] = column_counts.get(col, 0) + 1

# Keep only names that occur more than once
duplicate_counts = {
    col: count
    for col, count in column_counts.items()
    if count > 1
}

print(duplicate_counts)

{'Glycine': 2, 'LPE_16_0': 2, 'LPE_18_1': 2, 'LPE_22_6': 2, 'TG_50_1': 2, 'M_2_Hydroxyisobutyric_acid': 2, 'M_3_Indoxyl_sulphate': 2, 'CMPF': 2, 'Glycochenodeoxycholic_acid': 3, 'Indole_3_lactic_acid': 2}

In [173]:
# Display only columns with duplicated names, keeping their original order
duplicate_df = df.loc[:, df.columns.duplicated(keep=False)]

duplicate_df

,Glycine,LPE_16_0,LPE_18_1,LPE_22_6,TG_50_1,TG_50_1,M_2_Hydroxyisobutyric_acid,M_2_Hydroxyisobutyric_acid,M_3_Indoxyl_sulphate,M_3_Indoxyl_sulphate,...,CMPF,Glycine,Glycochenodeoxycholic_acid,Glycochenodeoxycholic_acid,Glycochenodeoxycholic_acid,Indole_3_lactic_acid,Indole_3_lactic_acid,LPE_16_0,LPE_18_1,LPE_22_6
0,487.924908,0.000153,0.000161,0.000132,0.015397,0.000623,11992157.7,226233931.3,12849489.38,272670736.3,...,493064.2822,4604834.453,1716821.38,6173172.559,2132732.318,20734778.78,434817.8721,2791114.628,5123934.489,693742.0321
1,NaN,0.000162,0.000141,0.000123,0.008857,0.000445,16002983.15,175352282,16725141.21,329799588,...,739203.8487,8276117.379,466223.3659,1234978.996,1580375.992,18521822.66,3151552.538,4478026.474,6112722.698,860610.9159
2,745.483216,0.000204,0.000157,0.000143,0.039254,0.001302,20265786.3,360557567.6,10231158.4,245090466.5,...,304406.0782,3486505.078,1015728.261,5067980,3150277.732,29099202.54,2747768.995,3995242.211,4772666.402,803603.0012
3,193.949239,0.000446,0.000361,0.000373,0.015501,0.000938,17293806.92,172911056.8,8507377.088,204723863.2,...,520870.9911,4725040.5,56742766.12,20701762.25,1573194.469,21590088.39,239363.7576,5974337.903,8029934.221,728035.9214
4,882.377623,0.000194,0.000174,0.000115,0.012404,0.000516,15290513.64,167628988.9,8278041.119,202150666.7,...,284478.3373,4289720.039,1208344.369,4852248.234,5481488.155,16262188.65,3197246.479,3230090.748,5022128.99,545964.0845
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,1076.643226,0.000168,0.000148,0.000112,0.016078,0.000829,17818888.34,227421258.8,11825523.97,262835842.9,...,1581463.415,4350400.631,731973.4538,11646921.66,1656136.311,30691471.66,2710774.987,4198715.737,5806323.196,800380.7569
292,983.387411,0.000225,0.000205,0.000073,0.011697,0.000505,15428606.66,183576077,14082236.71,343919797.1,...,572111.1277,3321495.93,11555591.8,19014910.87,5461246.397,23274352.22,2183080.868,6484089.787,10435720.85,744325.0024
293,550.420421,0.000143,0.000213,0.00007,0.007895,0.000483,11953088.42,98785748.87,16498211.69,459041359.2,...,1132741.214,3854500.574,4402977.44,10614428.68,1852478.612,22414289.48,5654812.001,4299640.742,9253863.653,676471.3947
294,1097.427736,0.000238,0.000217,0.000188,0.007434,0.000474,13115456.59,157570887.4,14392613.39,334868096.7,...,866777.8594,4897819.718,2344360.33,7633358.004,12185047.41,26785256.85,3083442.714,4272363.182,5503512.004,739262.651
295,775.53812,0.000323,0.000437,0.000168,0.006816,0.000422,28013430.38,182845361.3,11037489.68,237929990.8,...,542302.3332,5577159.944,6106676.742,14200991.75,3980909.165,25902559.71,3273086.739,6951913.869,14280585.64,988320.1887

Some column names appear more than once in the dataset, while the corresponding columns contain different values. The study reports untargeted metabolomic and lipidomic analyses, but does not explain the repeated column names found in the public dataset. These columns are therefore retained for further analysis.

# Missing Values

Let's check for missing values in each variable to identify incomplete measurements in the dataset.

In [174]:
# Check missing values in each column
missing_values = df.isna().sum()

# Display only columns with missing values
missing_values = missing_values[missing_values > 0]

print("Columns with missing values:")
print(missing_values)

Columns with missing values:
Alanin               8
Arginine             8
Asparagine           8
Citruline            8
Fenylalanin          8
                    ..
Undecylenic_acid     4
Uric_acid            4
Uridine              4
Xanthine             4
Β_Muricholic_acid    4
Length: 776, dtype: int64

In [175]:
# Calculate the number and percentage of missing values in each column
missing_summary = pd.DataFrame({
    "Missing_Count": df.isna().sum(),
    "Missing_Percent": df.isna().mean() * 100
})

# Keep only columns with missing values
missing_summary = missing_summary[missing_summary["Missing_Count"] > 0]

# Display the summary
missing_summary

                   Missing_Count  Missing_Percent
Alanin                         8         2.702703
Arginine                       8         2.702703
Asparagine                     8         2.702703
Citruline                      8         2.702703
Fenylalanin                    8         2.702703
...                          ...              ...
Undecylenic_acid               4         1.351351
Uric_acid                      4         1.351351
Uridine                        4         1.351351
Xanthine                       4         1.351351
Β_Muricholic_acid              4         1.351351

[776 rows x 2 columns]

There are 776 variables with at least one missing value.

In [177]:
# Calculate the percentage of missing values in each column
missing_percent = df.isna().mean() * 100

# Identify columns with at least 50% missing values
high_missing_columns = missing_percent[missing_percent >= 50].sort_values(
    ascending=False
)

print("Number of columns with at least 50% missing values:", len(high_missing_columns))
print("\nColumns with at least 50% missing values:")
print(high_missing_columns)

Number of columns with at least 50% missing values: 4

Columns with at least 50% missing values:
C_peptide    66.891892
IL6          66.891892
Leptin       66.891892
MCP1         66.891892
dtype: float64

In [178]:
# Count non-missing measurements for each treatment group and time point
available_entries = (
    df.groupby(["Treatment", "Measurement_Time"])[high_missing_columns.index]
      .count()
)

available_entries

                            C_peptide  IL6  Leptin  MCP1
Treatment Measurement_Time
Placebo   0                         0    0       0     0
          3                         0    0       0     0
SH120     0                        49   49      49    49
          3                        49   49      49    49
SH60      0                         0    0       0     0
          3                         0    0       0     0

These four variables contain measurements only for the SH120 treatment group (49 observations at both Measurement Time 0 and 3), while no measurements are available for the Placebo or SH60 groups. Therefore, these variables cannot be used for comparisons across all three treatment groups and will be excluded from the statistical analysis.

In [179]:
# Check for variables with data in only one treatment group
# Columns already excluded
excluded_columns = ["C_peptide", "IL6", "Leptin", "MCP1"]

found = 0

for i, col in enumerate(df.columns):

    if col in ["Participant_ID", "Treatment", "Measurement_Time"]:
        continue

    if col in excluded_columns:
        continue

    values = df.iloc[:, i]

    groups_with_data = df.assign(
        _value=values
    ).groupby("Treatment")["_value"].count()

    if (groups_with_data > 0).sum() == 1:
        print(col)
        print(groups_with_data)
        print()
        found += 1

print("Additional columns found:", found)

Additional columns found: 0

In [180]:
# Variables already excluded from statistical analysis
excluded_columns = ["C_peptide", "IL6", "Leptin", "MCP1"]

# Get measurement columns
measurement_columns = [
    col for col in df.columns
    if col not in ["Participant_ID", "Treatment", "Measurement_Time"]
    and col not in excluded_columns
]

print("Number of measurement variables:", len(measurement_columns))

Number of measurement variables: 775

In [181]:
# Variables already excluded from statistical analysis
excluded_columns = ["C_peptide", "IL6", "Leptin", "MCP1"]

# Calculate missing percentage for each variable
missing_by_group = []

for i, col in enumerate(df.columns):

    # Skip metadata columns
    if col in ["Participant_ID", "Treatment", "Measurement_Time"]:
        continue

    # Skip the four variables already excluded
    if col in excluded_columns:
        continue

    # Select the exact column by position
    values = df.iloc[:, i]

    # Calculate overall missing percentage
    overall_missing = values.isna().mean() * 100

    # Keep only variables with at least 30% missing values
    if overall_missing >= 30:

        row = {
            "Variable": col,
            "Overall_Missing_Percent": overall_missing
        }

        # Calculate missing percentage for each treatment × time group
        for treatment in df["Treatment"].unique():
            for time in sorted(df["Measurement_Time"].unique()):

                group = df[
                    (df["Treatment"] == treatment) &
                    (df["Measurement_Time"] == time)
                ]

                row[f"{treatment}_{time}"] = (
                    values.loc[group.index].isna().mean() * 100
                )

        missing_by_group.append(row)

# Create table
missing_by_group = pd.DataFrame(missing_by_group)

# Sort from highest to lowest overall missingness
missing_by_group = (
    missing_by_group
    .sort_values("Overall_Missing_Percent", ascending=False)
    .reset_index(drop=True)
)

missing_by_group

,Variable,Overall_Missing_Percent,Placebo_0,Placebo_3,SH120_0,SH120_3,SH60_0,SH60_3
0,IL1b,38.175676,0.0,0.0,12.0,22.0,100.0,100.0
1,IL1RA,35.810811,0.0,0.0,8.0,12.0,100.0,100.0
2,IL10,35.135135,0.0,0.0,6.0,10.0,100.0,100.0
3,Fetuin_A,33.108108,0.0,0.0,2.0,2.0,100.0,100.0
4,CRP,33.108108,0.0,0.0,2.0,2.0,100.0,100.0
5,Glucagon,33.108108,0.0,0.0,2.0,2.0,100.0,100.0
6,GLP1_total,33.108108,0.0,0.0,2.0,2.0,100.0,100.0
7,Adipsin,33.108108,0.0,0.0,2.0,2.0,100.0,100.0
8,TNFa,33.108108,0.0,0.0,2.0,2.0,100.0,100.0
9,IFNg,33.108108,0.0,0.0,2.0,2.0,100.0,100.0
10,FGF2,33.108108,0.0,0.0,2.0,2.0,100.0,100.0
11,EGF,33.108108,0.0,0.0,2.0,2.0,100.0,100.0
12,IL17A,33.108108,0.0,0.0,2.0,2.0,100.0,100.0

### Variables with ≥30% Missing Values

The variables listed above have >30% overall missing values because no measurements are available for the SH60 treatment group. 
Measurements are available for the Placebo and SH120 groups, although some missing values are also present in SH120. Therefore, these variables will not be excluded entirely. Instead, SH60 will be excluded from analyses involving these variables, while the available Placebo and SH120 measurements will be retained.

### Data Types

Categorical Variables
Let's review the categorical variables to ensure that values are consistently coded and that no unexpected categories are present.

In [182]:
# Validate Treatment categories
print(df["Treatment"].value_counts(dropna=False))

Treatment
Placebo    100
SH120      100
SH60        96
Name: count, dtype: int64

In [183]:
# Validate categorical and identifier variables
for col in ["Treatment", "Gender", "Phototype", "Measurement_Time", "Participant_ID"]:
    print(f"\n{col}:")
    print(df[col].value_counts(dropna=False).to_string())

Treatment:
Treatment
Placebo    100
SH120      100
SH60        96

Gender:
Gender
Female    190
Male      106

Phototype:
Phototype
2    266
1     16
3     14

Measurement_Time:
Measurement_Time
0    148
3    148

Participant_ID:
Participant_ID
101    2
106    2
111    2
112    2
115    2
117    2
126    2
129    2
131    2
136    2
137    2
138    2
142    2
144    2
145    2
146    2
149    2
001    2
002    2
006    2
011    2
013    2
014    2
015    2
017    2
018    2
019    2
021    2
024    2
026    2
027    2
028    2
031    2
032    2
039    2
040    2
043    2
047    2
050    2
052    2
054    2
056    2
070    2
074    2
078    2
088    2
090    2
091    2
099    2
147    2
100    2
102    2
103    2
107    2
109    2
110    2
114    2
118    2
119    2
123    2
124    2
125    2
132    2
133    2
134    2
135    2
141    2
143    2
004    2
005    2
009    2
010    2
020    2
023    2
025    2
033    2
037    2
041    2
042    2
044    2
046    2
048    2
051    2
053    2
055    2
058    2
059    2
062    2
067    2
069    2
073    2
080    2
081    2
082    2
085    2
089    2
093    2
094    2
096    2
097    2
104    2
105    2
108    2
113    2
116    2
120    2
121    2
122    2
128    2
130    2
139    2
148    2
150    2
003    2
007    2
008    2
012    2
016    2
022    2
029    2
030    2
034    2
035    2
036    2
038    2
045    2
049    2
057    2
060    2
061    2
063    2
064    2
065    2
066    2
068    2
071    2
072    2
075    2
076    2
077    2
079    2
083    2
084    2
086    2
087    2
092    2
095    2
098    2

In [184]:
# Check pandas data types of categorical and identifier variables
categorical_variables = [
    "Treatment",
    "Gender",
    "Phototype",
    "Measurement_Time",
    "Participant_ID"
]

df[categorical_variables].dtypes

Treatment              str
Gender              object
Phototype           object
Measurement_Time    object
Participant_ID      object
dtype: object

### Quantitative Variables

Let's review the data types of the quantitative variables to identify measurements that are not stored as numeric values where appropriate.

In [185]:
# Define quantitative variables from the current dataframe
quantitative_variables = [
    col for col in df.columns
    if col not in [
        "Treatment",
        "Gender",
        "Phototype",
        "Measurement_Time",
        "Participant_ID"
    ]
]

print("Total columns:", df.shape[1])
print("Quantitative variables:", len(quantitative_variables))

Total columns: 782
Quantitative variables: 777

In [186]:
# Check pandas data types of quantitative variables
df[quantitative_variables].dtypes

Age                  object
Alanin               object
Arginine             object
Asparagine           object
Citruline            object
                      ...
Undecylenic_acid     object
Uric_acid            object
Uridine              object
Xanthine             object
Β_Muricholic_acid    object
Length: 801, dtype: object

In [187]:
print("Age:")
print(df["Age"].head(10).to_string(index=False))
print("\nAge dtype:", df["Age"].dtype)

print("\nAlanin:")
print(df["Alanin"].head(10).to_string(index=False))
print("\nAlanin dtype:", df["Alanin"].dtype)

Age:
57
57
55
34
55
35
42
25
34
45

Age dtype: object

Alanin:
 294.324357
        NaN
 420.792795
 123.192424
 746.432357
 471.293114
 594.824998
        NaN
 399.289288
 608.707767

Alanin dtype: object

In [ ]:
print("Age convertible to numeric:",
      pd.to_numeric(df["Age"], errors="coerce").notna().sum())

print("Alanin convertible to numeric:",
      pd.to_numeric(df["Alanin"], errors="coerce").notna().sum())

In [188]:
# Scan quantitative columns for non-numeric, non-missing values
non_numeric_values = []

for i, col in enumerate(df.columns):

    # Skip categorical and identifier variables
    if col in [
        "Treatment",
        "Gender",
        "Phototype",
        "Measurement_Time",
        "Participant_ID"
    ]:
        continue

    # Select the physical column by position
    values = df.iloc[:, i]

    # Identify non-missing values that cannot be converted to numeric
    converted = pd.to_numeric(values, errors="coerce")

    invalid = values.notna() & converted.isna()

    # Store every problematic value
    for row_index in df.index[invalid]:
        non_numeric_values.append({
            "Column_Position": i,
            "Variable": col,
            "Row": row_index,
            "Value": values.loc[row_index]
        })

non_numeric_values = pd.DataFrame(non_numeric_values)

print("Number of non-numeric, non-missing values:",
      len(non_numeric_values))

non_numeric_values

Number of non-numeric, non-missing values: 0

Empty DataFrame
Columns: []
Index: []

In [189]:
# Identify quantitative columns by their physical positions
quantitative_positions = [
    i for i, col in enumerate(df.columns)
    if col not in [
        "Treatment",
        "Gender",
        "Phototype",
        "Measurement_Time",
        "Participant_ID"
    ]
]

print("Quantitative columns:", len(quantitative_positions))

Quantitative columns: 777

In [190]:
# Display the data type of each quantitative column
for i in quantitative_positions:
    print(f"{i}: {df.columns[i]} -> {df.iloc[:, i].dtype}")

5: Age -> object
6: Alanin -> object
7: Arginine -> object
8: Asparagine -> object
9: Citruline -> object
10: Fenylalanin -> object
11: Glutamic_acid -> object
12: Glutamin -> object
13: Glycine -> object
14: Histidin -> object
15: Isoleucine -> object
16: Aspartic_Acid -> object
17: Leucine -> object
18: Lysin -> object
19: Methionine -> object
20: Ornithine -> object
21: Proline -> object
22: Pyrrolidone_carboxylic_acid -> object
23: Serine -> object
24: Threonine -> object
25: Tryptofan -> object
26: Tyrosine -> object
27: Urea -> object
28: Valin -> object
29: NMF -> object
30: Total_urocanic_acid -> object
31: Trans_Urocanic_acid -> object
32: Hydration_forehead -> object
33: Hydration_cheek -> object
34: Hydration_forearm -> object
35: TEWL_forehead -> object
36: TEWL_Cheek -> object
37: Sebum_forehead -> object
38: Sebum_cheek -> object
39: Wrinkle -> object
40: Red_Area_forehead -> object
41: Red_Area_cheek -> object
42: Pores_Area_forehead -> object
43: Pores_Area_cheek -> object
44: GLOSS_forehead -> object
45: GLOSS_Cheek -> object
46: GLOSS_DCS_forehead -> object
47: GLOSS_DCS_cheek -> object
48: MEXA_Melanin_forehead -> object
49: MEXA_Melanin_cheek -> object
50: MEXA_Erythema_forehead -> object
51: MEXA_Erythema_cheek -> object
52: ITA_forehead -> object
53: ITA_cheek -> object
54: A_value_forehead -> object
55: A_value_cheek -> object
56: B_value_forehead -> object
57: B_value_cheek -> object
58: Elasticity_R0_forehead -> object
59: Elasticity_R0_cheek -> object
60: Elasticity_R1_forehead -> object
61: Elasticity_R1_cheek -> object
62: Elasticity_R2_forehead -> object
63: Elasticity_R2_cheek -> object
64: Elasticity_R3_forehead -> object
65: Elasticity_R3_cheek -> object
66: Elasticity_R4_forehead -> object
67: Elasticity_R4_cheek -> object
68: Elasticity_R5_forehead -> object
69: Elasticity_R5_cheek -> object
70: Elasticity_R6_forehead -> object
71: Elasticity_R6_cheek -> object
72: Elasticity_R7_forehead -> object
73: Elasticity_R7_cheek -> object
74: Elasticity_R8_forehead -> object
75: Elasticity_R8_cheek -> object
76: Elasticity_R9_forehead -> object
77: Elasticity_R9_cheek -> object
78: Elasticity_F0_forehead -> object
79: Elasticity_F0_cheek -> object
80: Elasticity_F1_forehead -> object
81: Elasticity_F1_cheek -> object
82: Elasticity_R1_R4_forehead -> object
83: Elasticity_R1_R4_cheek -> object
84: Elasticity_R3_R9_forehead -> object
85: Elasticity_R3_R9_cheek -> object
86: Epidermal_thickness -> object
87: Dermal_density -> object
88: CAR_12_0 -> object
89: CAR_12_1 -> object
90: CAR_12_2 -> object
91: CAR_13_0 -> object
92: CAR_14_1 -> object
93: CAR_14_2 -> object
94: CAR_14_3 -> object
95: CAR_16_0 -> object
96: CAR_16_1 -> object
97: CAR_16_2 -> object
98: CAR_16_3 -> object
99: CAR_18_1 -> object
100: CAR_18_2 -> object
101: CAR_18_3 -> object
102: CAR_20_1 -> object
103: CAR_20_2 -> object
104: CAR_22_0 -> object
105: CAR_24_1 -> object
106: CAR_26_0 -> object
107: CE_16_1 -> object
108: CE_17_0 -> object
109: CE_18_1 -> object
110: CE_18_2 -> object
111: CE_18_3 -> object
112: CE_20_3 -> object
113: CE_20_4 -> object
114: CE_20_5 -> object
115: CE_22_6 -> object
116: Cer_34_1_NS_neg -> object
117: Cer_38_1_2O -> object
118: Cer_38_1_NS_neg -> object
119: Cer_40_0_2O -> object
120: Cer_40_0_2O_neg -> object
121: Cer_40_1_2O -> object
122: Cer_40_1_NS_neg -> object
123: Cer_40_2_2O -> object
124: Cer_40_2_NS_neg -> object
125: Cer_41_0_2O -> object
126: Cer_41_1_2O -> object
127: Cer_41_1_NS_neg -> object
128: Cer_41_2_2O -> object
129: Cer_42_0_2O -> object
130: Cer_42_0_2O_neg -> object
131: Cer_42_1_2O_neg -> object
132: Cer_42_1_2O_1 -> object
133: Cer_42_1_2O_2 -> object
134: Cer_42_2_2O -> object
135: Cer_42_2_NS_neg -> object
136: Cer_42_3_2O -> object
137: Cer_42_3_2O_neg -> object
138: Cer_43_1_2O -> object
139: Cer_43_1_2O_neg -> object
140: Cer_43_2_2O -> object
141: Cer_44_1_2O_neg -> object
142: DG_36_2 -> object
143: FA_14_0 -> object
144: FA_14_1 -> object
145: FA_16_0 -> object
146: FA_16_1 -> object
147: FA_16_3 -> object
148: FA_18_1 -> object
149: FA_18_2 -> object
150: FA_18_3 -> object
151: FA_19_1 -> object
152: FA_20_1 -> object
153: FA_20_2 -> object
154: FA_20_3 -> object
155: FA_20_4 -> object
156: FA_20_5 -> object
157: FA_22_1 -> object
158: FA_22_2 -> object
159: FA_22_3 -> object
160: FA_22_4 -> object
161: FA_22_5 -> object
162: FA_22_6 -> object
163: FA_24_1 -> object
164: FA_24_2 -> object
165: FA_24_4 -> object
166: FA_24_5 -> object
167: FA_26_3 -> object
168: FA_34_0 -> object
169: FAHFA_24_3 -> object
170: FAHFA_36_1 -> object
171: FAHFA_38_2 -> object
172: FAHFA_38_4 -> object
173: FAHFA_40_3 -> object
174: FAHFA_40_4 -> object
175: FC -> object
176: GM3_32_1_2O_neg -> object
177: GM3_40_1_2O_neg -> object
178: GM3_42_1_2O_neg -> object
179: GM3_42_2_2O_neg -> object
180: Hex2Cer_34_1_2O_neg -> object
181: Hex3Cer_34_1_2O -> object
182: Hex3Cer_40_1_2O -> object
183: HexCer_34_0_3O_2OH_neg -> object
184: HexCer_34_1_2O_neg -> object
185: HexCer_36_1_2O_neg -> object
186: HexCer_38_1_2O_neg -> object
187: HexCer_40_1_2O -> object
188: HexCer_40_1_2O_neg -> object
189: HexCer_40_2_2O_neg -> object
190: HexCer_41_1_2O_neg -> object
191: HexCer_41_2_2O_neg -> object
192: HexCer_42_1_2O -> object
193: HexCer_42_1_2O_neg -> object
194: HexCer_42_2_2O_neg -> object
195: HexCer_42_3_2O_neg -> object
196: LNAPE_36_4 -> object
197: LPC_12_0 -> object
198: LPC_14_1 -> object
199: LPC_16_1 -> object
200: LPC_16_2 -> object
201: LPC_17_0 -> object
202: LPC_17_1 -> object
203: LPC_18_0 -> object
204: LPC_18_1 -> object
205: LPC_18_2 -> object
206: LPC_19_0 -> object
207: LPC_19_1 -> object
208: LPC_20_0 -> object
209: LPC_20_1 -> object
210: LPC_20_2 -> object
211: LPC_20_3 -> object
212: LPC_20_4 -> object
213: LPC_22_0 -> object
214: LPC_22_1 -> object
215: LPC_22_3 -> object
216: LPC_22_5 -> object
217: LPC_22_6 -> object
218: LPC_24_0 -> object
219: LPC_24_5 -> object
220: LPC_26_1 -> object
221: LPC_O_16_0 -> object
222: LPC_O_16_1 -> object
223: LPC_O_17_0 -> object
224: LPC_O_18_1 -> object
225: LPC_O_20_0 -> object
226: LPC_O_22_1 -> object
227: LPC_O_26_2 -> object
228: LPE_16_0 -> object
229: LPE_18_0 -> object
230: LPE_18_1 -> object
231: LPE_20_3 -> object
232: LPE_20_5 -> object
233: LPE_22_5 -> object
234: LPE_22_6 -> object
235: LPE_O_16_1 -> object
236: LPE_O_18_2 -> object
237: LPI_18_0 -> object
238: LPI_18_2 -> object
239: LPI_20_3 -> object
240: LPI_20_4 -> object
241: PC_24_0 -> object
242: PC_26_0 -> object
243: PC_28_0 -> object
244: PC_28_1 -> object
245: PC_30_0 -> object
246: PC_30_1 -> object
247: PC_31_1 -> object
248: PC_31_2 -> object
249: PC_32_0 -> object
250: PC_32_1 -> object
251: PC_32_2 -> object
252: PC_32_3 -> object
253: PC_33_0 -> object
254: PC_33_1 -> object
255: PC_33_2 -> object
256: PC_33_4 -> object
257: PC_34_2 -> object
258: PC_34_3 -> object
259: PC_34_4 -> object
260: PC_34_5 -> object
261: PC_35_0 -> object
262: PC_35_1 -> object
263: PC_35_2 -> object
264: PC_35_3 -> object
265: PC_35_4 -> object
266: PC_35_5 -> object
267: PC_36_0 -> object
268: PC_36_1 -> object
269: PC_36_2 -> object
270: PC_36_3 -> object
271: PC_36_4 -> object
272: PC_36_5 -> object
273: PC_36_6 -> object
274: PC_36_7 -> object
275: PC_37_2 -> object
276: PC_37_4 -> object
277: PC_37_5 -> object
278: PC_37_6 -> object
279: PC_37_7 -> object
280: PC_38_1 -> object
281: PC_38_2 -> object
282: PC_38_3 -> object
283: PC_38_5 -> object
284: PC_38_6 -> object
285: PC_38_7 -> object
286: PC_38_8 -> object
287: PC_38_9 -> object
288: PC_39_1 -> object
289: PC_39_3 -> object
290: PC_39_5 -> object
291: PC_39_6 -> object
292: PC_39_7 -> object
293: PC_40_1 -> object
294: PC_40_2 -> object
295: PC_40_3 -> object
296: PC_40_4 -> object
297: PC_40_5 -> object
298: PC_40_6 -> object
299: PC_40_7 -> object
300: PC_40_8 -> object
301: PC_40_9 -> object
302: PC_42_10 -> object
303: PC_42_5 -> object
304: PC_42_7 -> object
305: PC_44_4 -> object
306: PC_44_5 -> object
307: PC_O_30_0 -> object
308: PC_O_31_1 -> object
309: PC_O_32_0 -> object
310: PC_O_32_1 -> object
311: PC_O_33_2 -> object
312: PC_O_34_0 -> object
313: PC_O_34_1 -> object
314: PC_O_34_2 -> object
315: PC_O_34_3 -> object
316: PC_O_34_4 -> object
317: PC_O_35_4 -> object
318: PC_O_35_6 -> object
319: PC_O_35_7 -> object
320: PC_O_36_0 -> object
321: PC_O_36_2 -> object
322: PC_O_36_3 -> object
323: PC_O_36_4 -> object
324: PC_O_36_5 -> object
325: PC_O_36_6 -> object
326: PC_O_37_6 -> object
327: PC_O_37_7 -> object
328: PC_O_38_0 -> object
329: PC_O_38_4 -> object
330: PC_O_38_5 -> object
331: PC_O_38_6 -> object
332: PC_O_38_7 -> object
333: PC_O_39_6 -> object
334: PC_O_40_2 -> object
335: PC_O_40_3 -> object
336: PC_O_40_5 -> object
337: PC_O_40_6 -> object
338: PC_O_40_7 -> object
339: PC_O_42_1 -> object
340: PC_O_42_2 -> object
341: PC_O_42_3 -> object
342: PC_O_42_4 -> object
343: PC_O_42_5 -> object
344: PC_O_42_6 -> object
345: PC_O_44_5 -> object
346: PC_O_44_6 -> object
347: PC_O_44_7 -> object
348: PC_O_46_5 -> object
349: PC_O_46_6 -> object
350: PC_O_46_7 -> object
351: PC_O_46_8 -> object
352: PE_32_1 -> object
353: PE_34_1 -> object
354: PE_34_2 -> object
355: PE_34_3 -> object
356: PE_36_1 -> object
357: PE_36_2 -> object
358: PE_36_3 -> object
359: PE_36_4 -> object
360: PE_38_4 -> object
361: PE_38_6 -> object
362: PE_O_34_2 -> object
363: PE_O_34_3 -> object
364: PE_O_36_2 -> object
365: PE_O_36_3 -> object
366: PE_O_36_4 -> object
367: PE_O_36_5 -> object
368: PE_O_36_6 -> object
369: PE_O_36_7 -> object
370: PE_O_37_5 -> object
371: PE_O_37_6 -> object
372: PE_O_38_2 -> object
373: PE_O_38_3 -> object
374: PE_O_38_4 -> object
375: PE_O_38_5 -> object
376: PE_O_38_6 -> object
377: PE_O_38_7 -> object
378: PE_O_39_6 -> object
379: PE_O_39_7 -> object
380: PE_O_40_7 -> object
381: PE_O_40_8 -> object
382: PE_O_40_9 -> object
383: PE_O_42_7 -> object
384: PE_O_42_8 -> object
385: PG_34_2 -> object
386: PG_36_2 -> object
387: PI_32_1 -> object
388: PI_34_1 -> object
389: PI_36_1 -> object
390: PI_36_2 -> object
391: PI_36_4 -> object
392: PI_37_4 -> object
393: PI_38_2 -> object
394: PI_38_3 -> object
395: PI_38_4 -> object
396: PI_40_5 -> object
397: PI_40_6 -> object
398: SM_29_1_2O -> object
399: SM_30_0_2O -> object
400: SM_30_1_2O_1 -> object
401: SM_30_1_2O_2 -> object
402: SM_31_1_2O -> object
403: SM_32_0_2O -> object
404: SM_32_1_2O -> object
405: SM_32_2_2O_1 -> object
406: SM_32_2_2O_2 -> object
407: SM_33_1_2O_1 -> object
408: SM_33_1_2O_2 -> object
409: SM_33_2_2O -> object
410: SM_34_0_2O -> object
411: SM_34_1_2O_1 -> object
412: SM_34_1_3O_2 -> object
413: SM_34_2_2O_1 -> object
414: SM_34_2_2O_2 -> object
415: SM_34_3_2O -> object
416: SM_35_1_2O -> object
417: SM_36_0_2O -> object
418: SM_36_2_2O -> object
419: SM_36_3_2O -> object
420: SM_37_1_2O -> object
421: SM_38_0_2O -> object
422: SM_38_1_2O_1 -> object
423: SM_38_1_2O_2 -> object
424: SM_38_2_2O -> object
425: SM_38_3_2O -> object
426: SM_38_4_2O -> object
427: SM_39_0_2O -> object
428: SM_39_1_2O_1 -> object
429: SM_39_1_2O_2 -> object
430: SM_39_1_2O_3 -> object
431: SM_39_2_2O -> object
432: SM_40_0_2O -> object
433: SM_40_1_2O_1 -> object
434: SM_40_1_2O_2 -> object
435: SM_40_2_2O_1 -> object
436: SM_40_2_2O_2 -> object
437: SM_40_3_2O -> object
438: SM_41_0_2O -> object
439: SM_41_1_2O_1 -> object
440: SM_41_1_2O_2 -> object
441: SM_41_1_2O_3 -> object
442: SM_41_2_2O_1 -> object
443: SM_41_2_2O_2 -> object
444: SM_42_1_2O_1 -> object
445: SM_42_1_2O_2 -> object
446: SM_42_2_2O_1 -> object
447: SM_42_2_2O_2 -> object
448: SM_42_2_2O_3 -> object
449: SM_42_3_2O -> object
450: SM_42_4_2O -> object
451: SM_42_5_2O -> object
452: SM_43_1_2O_1 -> object
453: SM_43_1_2O_2 -> object
454: SM_43_2_2O_1 -> object
455: SM_43_2_2O_2 -> object
456: SM_43_2_2O_3 -> object
457: SM_43_3_2O -> object
458: SM_44_1_2O -> object
459: SM_44_2_2O -> object
460: SM_44_3_2O -> object
461: TG_34_0 -> object
462: TG_36_0 -> object
463: TG_40_0 -> object
464: TG_42_0 -> object
465: TG_42_1 -> object
466: TG_42_2_1 -> object
467: TG_42_2_2 -> object
468: TG_44_0 -> object
469: TG_44_1_1 -> object
470: TG_44_1_2 -> object
471: TG_44_2_1 -> object
472: TG_44_2_2 -> object
473: TG_44_3 -> object
474: TG_45_1 -> object
475: TG_45_2 -> object
476: TG_46_0 -> object
477: TG_46_1 -> object
478: TG_46_2 -> object
479: TG_46_3_1 -> object
480: TG_46_3_2 -> object
481: TG_46_3_3 -> object
482: TG_47_1 -> object
483: TG_47_2 -> object
484: TG_47_3 -> object
485: TG_48_1 -> object
486: TG_48_2 -> object
487: TG_48_3_1 -> object
488: TG_48_3_2 -> object
489: TG_48_3_3 -> object
490: TG_48_4 -> object
491: TG_48_5 -> object
492: TG_49_0 -> object
493: TG_49_1 -> object
494: TG_49_2 -> object
495: TG_49_3 -> object
496: TG_49_4 -> object
497: TG_49_5 -> object
498: TG_50_0 -> object
499: TG_50_1 -> object
500: TG_50_1 -> object
501: TG_50_2 -> object
502: TG_50_3 -> object
503: TG_50_4_1 -> object
504: TG_50_4_2 -> object
505: TG_50_5 -> object
506: TG_50_6 -> object
507: TG_51_0 -> object
508: TG_51_1 -> object
509: TG_51_2 -> object
510: TG_51_3 -> object
511: TG_51_4 -> object
512: TG_52_1 -> object
513: TG_52_2 -> object
514: TG_52_3 -> object
515: TG_52_4_1 -> object
516: TG_52_4_2 -> object
517: TG_52_5_1 -> object
518: TG_52_5_2 -> object
519: TG_52_6_1 -> object
520: TG_52_6_2 -> object
521: TG_52_7 -> object
522: TG_53_1 -> object
523: TG_53_2 -> object
524: TG_53_3_1 -> object
525: TG_53_3_2 -> object
526: TG_53_4 -> object
527: TG_53_5 -> object
528: TG_54_1 -> object
529: TG_54_2_1 -> object
530: TG_54_2_2 -> object
531: TG_54_3 -> object
532: TG_54_4 -> object
533: TG_54_5 -> object
534: TG_54_6 -> object
535: TG_54_7 -> object
536: TG_54_8 -> object
537: TG_55_2_1 -> object
538: TG_55_2_2 -> object
539: TG_55_3 -> object
540: TG_55_4 -> object
541: TG_55_6 -> object
542: TG_55_7 -> object
543: TG_56_1_1 -> object
544: TG_56_1_2 -> object
545: TG_56_10 -> object
546: TG_56_2_1 -> object
547: TG_56_2_2 -> object
548: TG_56_3_1 -> object
549: TG_56_3_2 -> object
550: TG_56_4_1 -> object
551: TG_56_4_2 -> object
552: TG_56_5_1 -> object
553: TG_56_5_2 -> object
554: TG_56_6 -> object
555: TG_56_7 -> object
556: TG_56_8 -> object
557: TG_56_9_1 -> object
558: TG_56_9_2 -> object
559: TG_57_11 -> object
560: TG_57_2 -> object
561: TG_57_3 -> object
562: TG_57_4 -> object
563: TG_57_6 -> object
564: TG_57_8 -> object
565: TG_58_1 -> object
566: TG_58_10 -> object
567: TG_58_11 -> object
568: TG_58_12 -> object
569: TG_58_2 -> object
570: TG_58_3 -> object
571: TG_58_4 -> object
572: TG_58_5 -> object
573: TG_58_6 -> object
574: TG_58_7 -> object
575: TG_58_8 -> object
576: TG_58_9_1 -> object
577: TG_58_9_2 -> object
578: TG_59_11 -> object
579: TG_59_12 -> object
580: TG_59_2 -> object
581: TG_59_3 -> object
582: TG_60_1 -> object
583: TG_60_10 -> object
584: TG_60_11 -> object
585: TG_60_12 -> object
586: TG_60_13 -> object
587: TG_60_2 -> object
588: TG_60_3_1 -> object
589: TG_60_3_2 -> object
590: TG_60_4 -> object
591: TG_60_5 -> object
592: TG_60_6 -> object
593: TG_60_7 -> object
594: TG_60_8 -> object
595: TG_60_9 -> object
596: TG_61_1 -> object
597: TG_61_2 -> object
598: TG_61_3 -> object
599: TG_61_4 -> object
600: TG_62_1 -> object
601: TG_62_11 -> object
602: TG_62_12 -> object
603: TG_62_13_1 -> object
604: TG_62_13_2 -> object
605: TG_62_14 -> object
606: TG_62_2 -> object
607: TG_62_3 -> object
608: TG_62_4_1 -> object
609: TG_62_4_2 -> object
610: TG_62_5 -> object
611: TG_63_2 -> object
612: TG_64_1 -> object
613: TG_64_2 -> object
614: TG_64_4 -> object
615: TG_66_3 -> object
616: TG_O_50_1 -> object
617: TG_O_52_1 -> object
618: TG_O_52_2 -> object
619: TG_O_58_3 -> object
620: MDA -> object
621: M_12_13_diHOME -> object
622: M_13_HODE -> object
623: M_9_HODE -> object
624: M_5_HETE -> object
625: EPA -> object
626: DHA -> object
627: Arachidonic_acid -> object
628: CRP -> object
629: Fetuin_A -> object
630: Adipsin -> object
631: GLP1_total -> object
632: Glucagon -> object
633: TNFa -> object
634: EGF -> object
635: FGF2 -> object
636: IFNg -> object
637: IL1b -> object
638: IL1RA -> object
639: IL10 -> object
640: IL17A -> object
641: C_peptide -> object
642: IL6 -> object
643: Leptin -> object
644: MCP1 -> object
645: M_14_15_DiHET -> object
646: M_4E_6E_2_7_dimethyl_8_2R_3R_4S_5S_6R_3_4_5_trihydroxy_6_hydroxymethyl_oxan_2_yl_oxyocta_4_6_dienoic_acid -> object
647: M_4E_7E_dodeca_4_7_dienedioic_acid -> object
648: E_6_hydroxyoctadec_4_enoic_acid -> object
649: Z_3_hydroxydodec_5_enoic_acid -> object
650: M_1_16_Hexadecanedioic_acid -> object
651: M_1_3_Dimethyluric_acid -> object
652: M_1_7_Dimethyluric_acid -> object
653: M_10_HDA -> object
654: M_16_Hydroxyhexadecanoic_acid -> object
655: M_1_Methyluric_acid -> object
656: M_1_Methylxanthine -> object
657: M_2_4_Hydroxyphenyl_propanoic_acid -> object
658: M_2_ALPHA_D_MANNOPYRANOSYL_L_TRYPTOPHAN -> object
659: M_2_4_Dinitrophenol -> object
660: M_2_5_Dihydroxybenzenesulfonic_Acid -> object
661: M_2_6_Dihydroxybenzoic_acid -> object
662: M_2_Furoic_acid -> object
663: M_2_Furoylglycine -> object
664: M_2_Hydroxyhippuric_acid -> object
665: M_2_Hydroxyisobutyric_acid -> object
666: M_2_Hydroxyisobutyric_acid -> object
667: M_2_Methyl_4_6_dinitrophenol -> object
668: M_3_1_Pyrazolyl_alanine -> object
669: M_3_Allyl_2_hydroxybenzoic_acid -> object
670: M_3_FUROIC_ACID -> object
671: M_3_Hydroxybutyric_acid -> object
672: M_3_Hydroxydecanoic_acid -> object
673: M_3_Indoxyl_sulphate -> object
674: M_3_Indoxyl_sulphate -> object
675: M_3_Methoxysalicylic_acid -> object
676: M_3_Methoxytyrosine -> object
677: M_3_Methyl_2_oxovaleric_acid_calcium_salt -> object
678: M_3_Methylxanthine -> object
679: M_3_Phenyllactic_acid -> object
680: M_4_Acetamidobutanoic_acid -> object
681: M_4_Hydroxy_3_methoxyphenylglycol_sulfate -> object
682: M_4_Hydroxy_3_oxo_4_propan_2_ylcyclohexene_1_carboxylic_acid -> object
683: M_4_Hydroxyhippuric_acid_sulfate -> object
684: M_4_Chlorophenoxyacetic_acid -> object
685: M_4_Methoxymelilotic_acid -> object
686: M_4_Methylphenol -> object
687: M_4_Oxoproline -> object
688: M_4_Phenolsulfonic_acid -> object
689: M_4_Pyridoxic_acid -> object
690: M_5_Aminolevulinic_acid -> object
691: Acetaminophen_glucuronide -> object
692: Adenosine_3_5_cyclic_monophosphate -> object
693: Adenosine_5_monophosphate -> object
694: Beta_D_N_Acetylmannosamine -> object
695: Catechol -> object
696: Citric_acid -> object
697: Citrulline -> object
698: CMPF -> object
699: CMPF -> object
700: D_Glutamine -> object
701: D_Tryptophan -> object
702: Decanoic_acid -> object
703: Deoxycholic_acid -> object
704: D_Glucose -> object
705: DL_4_Hydroxyphenyllactic_acid -> object
706: DL_Arginine -> object
707: DL_Lactic_Acid -> object
708: Dodecanedioic_acid -> object
709: D_Panthenol -> object
710: D_Pantothenic_acid -> object
711: D_Threonine -> object
712: Epinephrine -> object
713: Erdosteine -> object
714: Gluconic_acid -> object
715: Glu_Leu -> object
716: Glu_Leu_Ser -> object
717: Glu_Phe -> object
718: Glu_Pro -> object
719: Glu_Tyr -> object
720: Glu_Val -> object
721: Glycine -> object
722: Glycochenodeoxycholic_acid -> object
723: Glycochenodeoxycholic_acid -> object
724: Glycochenodeoxycholic_acid -> object
725: Glycocholic_acid -> object
726: Hippuric_acid -> object
727: His_His -> object
728: Hydrocortisone -> object
729: Hypoxanthine -> object
730: Cholic_Acid -> object
731: Ibuprofen_metabolite_B -> object
732: Ile_Glu -> object
733: Indole_3_acrylic_acid -> object
734: Indole_3_lactic_acid -> object
735: Indole_3_lactic_acid -> object
736: Inosine -> object
737: Isocitric_acid -> object
738: Kynurenic_acid -> object
739: L_Malic_acid -> object
740: L_Lactic_acid -> object
741: L_Ascorbic_acid_2_sulfate -> object
742: L_Histidine -> object
743: L_isoleucine -> object
744: L_Ornithine -> object
745: LPE_16_0 -> object
746: LPE_18_1 -> object
747: LPE_22_6 -> object
748: L_Tyrosine -> object
749: Met_Glu -> object

In [191]:
# Convert quantitative columns to numeric by physical position
for i in quantitative_positions:
    df.iloc[:, i] = pd.to_numeric(
        df.iloc[:, i],
        errors="coerce"
    )

In [192]:
# Verify the data types after conversion
for i in quantitative_positions[:20]:
    print(f"{i}: {df.columns[i]} -> {df.iloc[:, i].dtype}")

5: Age -> object
6: Alanin -> object
7: Arginine -> object
8: Asparagine -> object
9: Citruline -> object
10: Fenylalanin -> object
11: Glutamic_acid -> object
12: Glutamin -> object
13: Glycine -> object
14: Histidin -> object
15: Isoleucine -> object
16: Aspartic_Acid -> object
17: Leucine -> object
18: Lysin -> object
19: Methionine -> object
20: Ornithine -> object
21: Proline -> object
22: Pyrrolidone_carboxylic_acid -> object
23: Serine -> object
24: Threonine -> object

In [193]:
test_age = pd.to_numeric(df.iloc[:, 5], errors="coerce")

print("Original dtype:", df.iloc[:, 5].dtype)
print("Converted dtype:", test_age.dtype)

Original dtype: object
Converted dtype: int64

In [194]:
# Convert all quantitative columns to numeric by position
for i in quantitative_positions:
    df[df.columns[i]] = pd.to_numeric(df.iloc[:, i], errors="coerce")

In [195]:
# Convert quantitative columns by physical position
for i in quantitative_positions:
    df.iloc[:, i] = pd.to_numeric(df.iloc[:, i], errors="coerce")

In [196]:
for i in quantitative_positions:
    converted = pd.to_numeric(df.iloc[:, i], errors="coerce")
    df.iloc[:, i] = converted.to_numpy()

In [197]:
print(df.iloc[:, 5].dtype)

int64

In [198]:
# Summarize data types of all quantitative columns
dtype_summary = {}

for i in quantitative_positions:
    dtype = str(df.iloc[:, i].dtype)
    dtype_summary[dtype] = dtype_summary.get(dtype, 0) + 1

print(dtype_summary)

{'int64': 1, 'float64': 776}

In [199]:
print(df[
    ["Treatment", "Gender", "Phototype",
     "Measurement_Time", "Participant_ID"]
].dtypes)

Treatment              str
Gender              object
Phototype           object
Measurement_Time    object
Participant_ID      object
dtype: object

The data types of the dataset were reviewed and standardized according to the intended role of each variable. The five categorical and identifier variables were retained in their original non-numeric formats, while all 777 quantitative variables were successfully converted to numeric types. One quantitative variable (`Age`) is stored as `int64`, while the remaining 776 quantitative variables are stored as `float64`. No non-missing values were found that could not be interpreted as numeric.

### Data Consistency

Let's review the dataset for unexpected or inconsistent values and identify potential extreme observations. Extreme values will be investigated as possible data-entry errors, measurement errors, or valid observations. No clinical measurements will be changed without a documented methodological reason.

In [200]:
# Identify potential outliers using the IQR rule
potential_outliers = []

for i in quantitative_positions:
    values = df.iloc[:, i]

    q1 = values.quantile(0.25)
    q3 = values.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outlier_count = ((values < lower_bound) | (values > upper_bound)).sum()

    potential_outliers.append({
        "Column_Position": i,
        "Variable": df.columns[i],
        "Lower_Bound": lower_bound,
        "Upper_Bound": upper_bound,
        "Potential_Outliers": outlier_count
    })

potential_outliers = pd.DataFrame(potential_outliers)

potential_outliers

,Column_Position,Variable,Lower_Bound,Upper_Bound,Potential_Outliers
0,5,Age,1.312500e+01,7.412500e+01,0
1,6,Alanin,2.221823e+01,1.210760e+03,5
2,7,Arginine,-1.927401e+02,9.885313e+02,1
3,8,Asparagine,5.957503e+01,2.209687e+02,4
4,9,Citruline,-8.767171e+01,1.366651e+03,6
...,...,...,...,...,...
772,777,Undecylenic_acid,-8.640693e+05,5.438092e+06,8
773,778,Uric_acid,8.315064e+08,1.947367e+09,6
774,779,Uridine,3.636599e+06,1.313769e+07,16
775,780,Xanthine,2.298678e+06,1.029675e+07,21
776,781,Β_Muricholic_acid,-1.827669e+05,4.386542e+05,20

In [201]:
# Show variables with potential outliers
potential_outliers[
    potential_outliers["Potential_Outliers"] > 0
].sort_values(
    "Potential_Outliers",
    ascending=False
)

,Column_Position,Variable,Lower_Bound,Upper_Bound,Potential_Outliers
679,684,M_4_Chlorophenoxyacetic_acid,1.766321e+04,4.466255e+04,53
686,691,Acetaminophen_glucuronide,1.021835e+03,6.675256e+04,50
767,772,Ser_Leu_Tyr,2.824477e+04,4.332755e+04,50
771,776,UKOUEEGEHXWHHO_MOFOKWOHSA_N,7.118825e+05,1.687976e+06,45
725,730,Cholic_Acid,-2.770669e+06,5.753393e+06,42
...,...,...,...,...,...
64,69,Elasticity_R5_cheek,-1.567583e-01,7.999750e-01,1
46,51,MEXA_Erythema_cheek,2.035529e+02,6.629452e+02,1
32,37,Sebum_forehead,-8.500000e+00,2.115000e+02,1
754,759,N_Formylmethionine,8.225520e+05,5.669834e+06,1
2,7,Arginine,-1.927401e+02,9.885313e+02,1

In [202]:
# Check for actual negative values in quantitative variables
negative_values = []

for i in quantitative_positions:
    values = df.iloc[:, i]
    count = (values < 0).sum()

    if count > 0:
        negative_values.append({
            "Variable": df.columns[i],
            "Negative_Count": count
        })

negative_values = pd.DataFrame(negative_values)

print("Variables containing negative values:")
print(negative_values)

Variables containing negative values:
                 Variable  Negative_Count
0               ITA_cheek               3
1     Elasticity_F0_cheek               1
2  Elasticity_F1_forehead               1
3                    TNFa               2
4                    IL1b              32
5                    IL10               4
6                   IL17A              14
7                     IL6              15

In [203]:
# Show the actual negative values
for variable in negative_values["Variable"]:
    values = df.loc[df[variable] < 0, ["Participant_ID", "Treatment", "Measurement_Time", variable]]
    
    print(f"\n{variable}:")
    print(values.to_string(index=False))

ITA_cheek:
Participant_ID Treatment Measurement_Time  ITA_cheek
           048     SH120                0  -6.615385
           121      SH60                0  -1.000000
           148      SH60                0  -5.800000

Elasticity_F0_cheek:
Participant_ID Treatment Measurement_Time  Elasticity_F0_cheek
           014   Placebo                3            -0.000167

Elasticity_F1_forehead:
Participant_ID Treatment Measurement_Time  Elasticity_F1_forehead
           016      SH60                3                 -0.0002

TNFa:
Participant_ID Treatment Measurement_Time      TNFa
           085     SH120                0 -2.715600
           085     SH120                3 -1.709467

IL1b:
Participant_ID Treatment Measurement_Time      IL1b
           115   Placebo                0 -1.401039
           126   Placebo                0 -0.631660
           131   Placebo                0 -1.016349
           136   Placebo                0 -0.246971
           144   Placebo                0 -1.785728
           149   Placebo                0 -3.324485
           002   Placebo                0 -1.401039
           017   Placebo                0 -0.631660
           024   Placebo                0 -1.785728
           028   Placebo                0 -0.439315
           031   Placebo                0 -1.401039
           056   Placebo                0 -0.631660
           070   Placebo                0 -0.054626
           074   Placebo                0 -0.631660
           115   Placebo                3 -1.016349
           126   Placebo                3 -1.016349
           131   Placebo                3 -0.631660
           142   Placebo                3 -1.401039
           144   Placebo                3 -3.324485
           145   Placebo                3 -0.054626
           146   Placebo                3 -1.016349
           149   Placebo                3 -2.170417
           001   Placebo                3 -0.631660
           002   Placebo                3 -1.401039
           024   Placebo                3 -1.785728
           028   Placebo                3 -1.401039
           031   Placebo                3 -1.401039
           039   Placebo                3 -0.631660
           056   Placebo                3 -0.631660
           088   Placebo                3 -0.631660
           090   Placebo                3 -2.170417
           091   Placebo                3 -0.631660

IL10:
Participant_ID Treatment Measurement_Time      IL10
           131   Placebo                3 -0.426226
           091   Placebo                3 -0.426226
           107     SH120                0 -0.286809
           107     SH120                3 -1.523056

IL17A:
Participant_ID Treatment Measurement_Time     IL17A
           136   Placebo                0 -0.352527
           146   Placebo                0 -0.929495
           149   Placebo                0 -0.929495
           002   Placebo                0 -0.352527
           019   Placebo                0 -0.064043
           021   Placebo                0 -0.352527
           031   Placebo                0 -0.929495
           088   Placebo                0 -0.352527
           142   Placebo                3 -0.352527
           144   Placebo                3 -0.929495
           001   Placebo                3 -0.352527
           028   Placebo                3 -0.352527
           031   Placebo                3 -0.641011
           074   Placebo                3 -0.352527

IL6:
Participant_ID Treatment Measurement_Time       IL6
           118     SH120                0 -0.264240
           132     SH120                0 -0.061757
           143     SH120                0 -0.061757
           010     SH120                0 -0.061757
           044     SH120                0 -0.061757
           046     SH120                0 -0.669204
           082     SH120                0 -0.264240
           109     SH120                3 -0.061757
           118     SH120                3 -0.466722
           132     SH120                3 -0.466722
           010     SH120                3 -0.871687
           044     SH120                3 -0.061757
           046     SH120                3 -0.669204
           067     SH120                3 -0.264240
           082     SH120                3 -0.061757

Negative cytokine values may reflect assay-related effects such as low-level measurements or standard-curve calibration. Previous studies have shown that background subtraction in multiplex immunoassays can produce negative assay values, particularly when measured signals are close to or below the background level. These values were therefore retained rather than treated automatically as data-entry errors.

As regards `ITA_cheek`, negative values are expected for this measurement, while the negative values observed for `Elasticity_F0_cheek` and `Elasticity_F1_forehead` are nearly zero and were therefore also retained.

Conclusion: all negative values will be retained for statistical analysis and will not be removed or modified solely because they are negative.

In [204]:
# Identify potential outliers by treatment group
outliers_by_treatment = []

for i in quantitative_positions:
    values = df.iloc[:, i]

    q1 = values.quantile(0.25)
    q3 = values.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outlier_mask = (values < lower_bound) | (values > upper_bound)

    if outlier_mask.sum() > 0:
        for treatment in df["Treatment"].unique():
            count = (
                outlier_mask &
                (df["Treatment"] == treatment)
            ).sum()

            if count > 0:
                outliers_by_treatment.append({
                    "Variable": df.columns[i],
                    "Treatment": treatment,
                    "Potential_Outliers": count
                })

outliers_by_treatment = pd.DataFrame(outliers_by_treatment)

outliers_by_treatment.sort_values(
    "Potential_Outliers",
    ascending=False
)

                                 Variable Treatment  Potential_Outliers
1832         M_4_Chlorophenoxyacetic_acid      SH60                  22
1692                             Fetuin_A   Placebo                  21
1851            Acetaminophen_glucuronide   Placebo                  19
1963                          Cholic_Acid   Placebo                  18
1761  M_2_5_Dihydroxybenzenesulfonic_Acid   Placebo                  18
...                                   ...       ...                 ...
570                              LPE_18_0      SH60                   1
593                              LPI_18_0      SH60                   1
41            Pyrrolidone_carboxylic_acid     SH120                   1
35                              Ornithine   Placebo                   1
32                             Methionine   Placebo                   1

[2111 rows x 3 columns]

In [206]:
# Calculate the percentage of potential outliers for each variable
outlier_frequency = []

for i in quantitative_positions:
    values = df.iloc[:, i]

    q1 = values.quantile(0.25)
    q3 = values.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outlier_mask = (
        (values < lower_bound) |
        (values > upper_bound)
    )

    non_missing = values.notna().sum()
    outlier_count = outlier_mask.sum()

    outlier_percent = (
        outlier_count / non_missing * 100
    )

    outlier_frequency.append({
        "Column_Position": i,
        "Variable": df.columns[i],
        "Non_Missing": non_missing,
        "Potential_Outliers": outlier_count,
        "Outlier_Percent": outlier_percent
    })

outlier_frequency = pd.DataFrame(outlier_frequency)

In [207]:
# Divide variables according to the proportion of potential outliers
outlier_frequency["Outlier_Group"] = pd.cut(
    outlier_frequency["Outlier_Percent"],
    bins=[-np.inf, 20, 40, np.inf],
    labels=["<20%", "20%–40%", ">40%"],
    right=False
)

outlier_frequency["Outlier_Group"].value_counts()

Outlier_Group
<20%       777
20%–40%      0
>40%         0
Name: count, dtype: int64

In [208]:
outlier_frequency["Potential_Outliers"].value_counts().sort_index()

Potential_Outliers
0      5
1     16
2     22
3     28
4     44
5     42
6     38
7     53
8     46
9     42
10    53
11    41
12    41
13    37
14    36
15    30
16    24
17    20
18    19
19    14
20    16
21    11
22    11
23    14
24    12
25     5
26    11
27    11
28     4
29     4
30     5
31     2
32     1
33     3
34     1
35     4
37     2
38     1
40     1
41     2
42     1
45     1
50     2
53     1
Name: count, dtype: int64

In [209]:
# Group variables according to the number of potential outliers
outlier_frequency["Outlier_Group"] = pd.cut(
    outlier_frequency["Potential_Outliers"],
    bins=[-1, 0, 5, 10, 20, np.inf],
    labels=[
        "0",
        "1–5",
        "6–10",
        "11–20",
        ">20"
    ]
)

outlier_frequency["Outlier_Group"].value_counts().sort_index()

Outlier_Group
0          5
1–5      152
6–10     232
11–20    278
>20      110
Name: count, dtype: int64

In [210]:
# Review variables with more than 20 potential outliers
high_outlier_variables = outlier_frequency[
    outlier_frequency["Outlier_Group"] == ">20"
].copy()

high_outlier_variables

,Column_Position,Variable,Non_Missing,Potential_Outliers,Outlier_Percent,Outlier_Group
7,12,Glutamin,288,27,9.375000,>20
25,30,Total_urocanic_acid,288,22,7.638889,>20
35,40,Red_Area_forehead,295,24,8.135593,>20
36,41,Red_Area_cheek,294,35,11.904762,>20
38,43,Pores_Area_cheek,295,22,7.457627,>20
...,...,...,...,...,...,...
766,771,Ser_Glu,292,26,8.904110,>20
767,772,Ser_Leu_Tyr,292,50,17.123288,>20
768,773,Succinic_acid,292,22,7.534247,>20
771,776,UKOUEEGEHXWHHO_MOFOKWOHSA_N,292,45,15.410959,>20
775,780,Xanthine,292,21,7.191781,>20

In [211]:
# Review variables with more than 20 potential outliers
high_outlier_variables = outlier_frequency[
    outlier_frequency["Outlier_Group"] == ">20"
].copy()

# Add outlier counts for each treatment group
for treatment in ["Placebo", "SH60", "SH120"]:
    counts = []

    for _, row in high_outlier_variables.iterrows():
        i = row["Column_Position"]
        values = df.iloc[:, i]

        q1 = values.quantile(0.25)
        q3 = values.quantile(0.75)
        iqr = q3 - q1

        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr

        outlier_mask = (
            (values < lower_bound) |
            (values > upper_bound)
        )

        count = (
            outlier_mask &
            (df["Treatment"] == treatment)
        ).sum()

        counts.append(count)

    high_outlier_variables[treatment] = counts

# Display the complete table
print(high_outlier_variables.to_string(index=False))

 Column_Position                                                                                                  Variable  Non_Missing  Potential_Outliers  Outlier_Percent Outlier_Group  Placebo  SH60  SH120
              12                                                                                                  Glutamin          288                  27         9.375000           >20        8    10      9
              30                                                                                       Total_urocanic_acid          288                  22         7.638889           >20        6     7      9
              40                                                                                         Red_Area_forehead          295                  24         8.135593           >20        6     8     10
              41                                                                                            Red_Area_cheek          294                  35        11.904762           >20        8    12     15
              43                                                                                          Pores_Area_cheek          295                  22         7.457627           >20        9     9      4
              91                                                                                                  CAR_13_0          294                  22         7.482993           >20        4     9      9
             197                                                                                                  LPC_12_0          294                  23         7.823129           >20        6     7     10
             198                                                                                                  LPC_14_1          294                  21         7.142857           >20        7     8      6
             241                                                                                                   PC_24_0          294                  27         9.183673           >20        7    10     10
             250                                                                                                   PC_32_1          294                  26         8.843537           >20        8    10      8
             275                                                                                                   PC_37_2          294                  27         9.183673           >20        8    10      9
             306                                                                                                   PC_44_5          294                  24         8.163265           >20        7     8      9
             352                                                                                                   PE_32_1          294                  21         7.142857           >20        7     7      7
             368                                                                                                 PE_O_36_6          294                  24         8.163265           >20        5    11      8
             385                                                                                                   PG_34_2          294                  22         7.482993           >20        9     6      7
             462                                                                                                   TG_36_0          294                  21         7.142857           >20        6     7      8
             463                                                                                                   TG_40_0          294                  37        12.585034           >20       15    12     10
             464                                                                                                   TG_42_0          294                  40        13.605442           >20       16    13     11
             465                                                                                                   TG_42_1          294                  33        11.224490           >20       13    10     10
             466                                                                                                 TG_42_2_1          294                  31        10.544218           >20       13     9      9
             467                                                                                                 TG_42_2_2          294                  31        10.544218           >20       13     9      9
             468                                                                                                   TG_44_0          294                  30        10.204082           >20       12     9      9
             469                                                                                                 TG_44_1_1          294                  27         9.183673           >20       11     9      7
             470                                                                                                 TG_44_1_2          294                  26         8.843537           >20       11     9      6
             471                                                                                                 TG_44_2_1          294                  27         9.183673           >20       11    11      5
             472                                                                                                 TG_44_2_2          294                  25         8.503401           >20       11     9      5
             473                                                                                                   TG_44_3          294                  30        10.204082           >20       13    10      7
             474                                                                                                   TG_45_1          294                  30        10.204082           >20       11    10      9
             475                                                                                                   TG_45_2          294                  25         8.503401           >20        8    10      7
             476                                                                                                   TG_46_0          294                  23         7.823129           >20        8     8      7
             477                                                                                                   TG_46_1          294                  23         7.823129           >20       11     7      5
             478                                                                                                   TG_46_2          294                  24         8.163265           >20       11     8      5
             480                                                                                                 TG_46_3_2          294                  28         9.523810           >20       13    10      5
             481                                                                                                 TG_46_3_3          294                  21         7.142857           >20       10     7      4
             482                                                                                                   TG_47_1          294                  22         7.482993           >20       10     8      4
             483                                                                                                   TG_47_2          294                  23         7.823129           >20       10     9      4
             491                                                                                                   TG_48_5          294                  23         7.823129           >20        7     6     10
             543                                                                                                 TG_56_1_1          294                  21         7.142857           >20        5    10      6
             544                                                                                                 TG_56_1_2          294                  24         8.163265           >20        7    11      6
             545                                                                                                  TG_56_10          294                  27         9.183673           >20        9     9      9
             546                                                                                                 TG_56_2_1          294                  23         7.823129           >20        7     9      7
             547                                                                                                 TG_56_2_2          294                  22         7.482993           >20        6     9      7
             549                                                                                                 TG_56_3_2          294                  24         8.163265           >20        8     9      7
             560                                                                                                   TG_57_2          294                  22         7.482993           >20        6     9      7
             565                                                                                                   TG_58_1          294                  24         8.163265           >20        6    12      6
             567                                                                                                  TG_58_11          294                  21         7.142857           >20        7     8      6
             568                                                                                                  TG_58_12          294                  27         9.183673           >20        8     7     12
             569                                                                                                   TG_58_2          294                  33        11.224490           >20       13    13      7
             570                                                                                                   TG_58_3          294                  27         9.183673           >20       10     9      8
             571                                                                                                   TG_58_4          294                  25         8.503401           >20        6    11      8
             580                                                                                                   TG_59_2          294                  23         7.823129           >20        6    10      7
             581                                                                                                   TG_59_3          294                  24         8.163265           >20       10     8      6
             582                                                                                                   TG_60_1          294                  27         9.183673           >20        9    12      6
             587                                                                                                   TG_60_2          294                  29         9.863946           >20       11    11      7
             588                                                                                                 TG_60_3_1          294                  28         9.523810           >20       10    11      7
             589                                                                                                 TG_60_3_2          294                  25         8.503401           >20       10     7      8
             590                                                                                                   TG_60_4          294                  26         8.843537           >20       10     9      7
             591                                                                                                   TG_60_5          294                  23         7.823129           >20        6    10      7
             592                                                                                                   TG_60_6          294                  24         8.163265           >20        7    11      6
             597                                                                                                   TG_61_2          294                  22         7.482993           >20        6    11      5
             598                                                                                                   TG_61_3          294                  32        10.884354           >20       13    12      7
             599                                                                                                   TG_61_4          294                  24         8.163265           >20        8    10      6
             606                                                                                                   TG_62_2          294                  26         8.843537           >20        8    12      6
             607                                                                                                   TG_62_3          294                  29         9.863946           >20        9    12      8
             608                                                                                                 TG_62_4_1          294                  34        11.564626           >20       11    14      9
             609                                                                                                 TG_62_4_2          294                  30        10.204082           >20       11    11      8
             611                                                                                                   TG_63_2          294                  21         7.142857           >20        6     9      6
             612                                                                                                   TG_64_1          294                  29         9.863946           >20        9    14      6
             613                                                                                                   TG_64_2          294                  26         8.843537           >20        7    13      6
             614                                                                                                   TG_64_4          294                  23         7.823129           >20        5    10      8
             615                                                                                                   TG_66_3          294                  26         8.843537           >20       11    10      5
             617                                                                                                 TG_O_52_1          294                  21         7.142857           >20       13     5      3
             629                                                                                                  Fetuin_A          198                  38        19.191919           >20       21     0     17
             637                                                                                                      IL1b          183                  23        12.568306           >20       14     0      9
             638                                                                                                     IL1RA          190                  22        11.578947           >20        9     0     13
             639                                                                                                      IL10          192                  26        13.541667           >20       15     0     11
             645                                                                                             M_14_15_DiHET          292                  35        11.986301           >20       10    14     11
             646 M_4E_6E_2_7_dimethyl_8_2R_3R_4S_5S_6R_3_4_5_trihydroxy_6_hydroxymethyl_oxan_2_yl_oxyocta_4_6_dienoic_acid          292                  27         9.246575           >20       13     5      9
             653                                                                                                  M_10_HDA          292                  26         8.904110           >20        8     9      9
             660                                                                       M_2_5_Dihydroxybenzenesulfonic_Acid          292                  41        14.041096           >20       18    14      9
             663                                                                                         M_2_Furoylglycine          292                  35        11.986301           >20       11    11     13
             668                                                                                   M_3_1_Pyrazolyl_alanine          292                  37        12.671233           >20       15     9     13
             669                                                                           M_3_Allyl_2_hydroxybenzoic_acid          292                  30        10.273973           >20       12     6     12
             681                                                                 M_4_Hydroxy_3_methoxyphenylglycol_sulfate          292                  21         7.191781           >20        6     4     11
             683                                                                          M_4_Hydroxyhippuric_acid_sulfate          292                  26         8.904110           >20        4    10     12
             684                                                                              M_4_Chlorophenoxyacetic_acid          292                  53        18.150685           >20       18    22     13
             685                                                                                 M_4_Methoxymelilotic_acid          292                  41        14.041096           >20       12    12     17
             688                                                                                   M_4_Phenolsulfonic_acid          292                  28         9.589041           >20       17     3      8
             689                                                                                        M_4_Pyridoxic_acid          292                  35        11.986301           >20        9    10     16
             691                                                                                 Acetaminophen_glucuronide          292                  50        17.123288           >20       19    17     14
             703                                                                                          Deoxycholic_acid          292                  21         7.191781           >20       10     5      6
             708                                                                                        Dodecanedioic_acid          292                  22         7.534247           >20        9     9      4
             709                                                                                               D_Panthenol          292                  24         8.219178           >20        9     6      9
             718                                                                                                   Glu_Pro          292                  33        11.301370           >20        7    14     12

The variables with more than 20 potential outliers were reviewed according to treatment group. For most variables, observations were distributed across Placebo, SH60, and SH120 rather than restricted to a single treatment group. This pattern does not provide evidence that the observations are data-entry errors. They were therefore considered potential extreme observations and retained for statistical analysis.

In [212]:
# Review variables with 11–20 potential outliers
medium_outlier_variables = outlier_frequency[
    outlier_frequency["Outlier_Group"] == "11–20"
].copy()

# Add potential outlier counts by treatment group
for treatment in ["Placebo", "SH60", "SH120"]:
    counts = []

    for _, row in medium_outlier_variables.iterrows():
        i = row["Column_Position"]
        values = df.iloc[:, i]

        q1 = values.quantile(0.25)
        q3 = values.quantile(0.75)
        iqr = q3 - q1

        lower_bound = q1 - 1.5 * iqr
        upper_bound = q3 + 1.5 * iqr

        outlier_mask = (
            (values < lower_bound) |
            (values > upper_bound)
        )

        count = (
            outlier_mask &
            (df["Treatment"] == treatment)
        ).sum()

        counts.append(count)

    medium_outlier_variables[treatment] = counts

print(medium_outlier_variables.to_string(index=False))

 Column_Position                           Variable  Non_Missing  Potential_Outliers  Outlier_Percent Outlier_Group  Placebo  SH60  SH120
              11                      Glutamic_acid          288                  11         3.819444         11–20        1     7      3
              17                            Leucine          288                  14         4.861111         11–20        3     8      3
              18                              Lysin          288                  12         4.166667         11–20        2     5      5
              27                               Urea          288                  13         4.513889         11–20        3     8      2
              28                              Valin          288                  12         4.166667         11–20        3     6      3
              36                         TEWL_Cheek          295                  15         5.084746         11–20        4     5      6
              48              MEXA_Melanin_forehead          295                  14         4.745763         11–20        6     5      3
              58             Elasticity_R0_forehead          295                  14         4.745763         11–20        5     5      4
              59                Elasticity_R0_cheek          295                  12         4.067797         11–20        2     4      6
              60             Elasticity_R1_forehead          295                  16         5.423729         11–20        6     8      2
              61                Elasticity_R1_cheek          295                  12         4.067797         11–20        6     2      4
              64             Elasticity_R3_forehead          295                  11         3.728814         11–20        3     5      3
              67                Elasticity_R4_cheek          295                  13         4.406780         11–20        6     2      5
              74             Elasticity_R8_forehead          295                  16         5.423729         11–20        4     5      7
              75                Elasticity_R8_cheek          295                  12         4.067797         11–20        3     4      5
              78             Elasticity_F0_forehead          295                  13         4.406780         11–20        3     6      4
              80             Elasticity_F1_forehead          295                  13         4.406780         11–20        4     4      5
              81                Elasticity_F1_cheek          295                  11         3.728814         11–20        3     3      5
              84          Elasticity_R3_R9_forehead          295                  20         6.779661         11–20       10     4      6
              85             Elasticity_R3_R9_cheek          295                  15         5.084746         11–20        9     2      4
              88                           CAR_12_0          294                  16         5.442177         11–20        6     9      1
              89                           CAR_12_1          294                  11         3.741497         11–20        4     6      1
              90                           CAR_12_2          294                  13         4.421769         11–20        3     8      2
              93                           CAR_14_2          294                  12         4.081633         11–20        3     8      1
              94                           CAR_14_3          294                  14         4.761905         11–20        3     6      5
             101                           CAR_18_3          294                  16         5.442177         11–20        4     8      4
             103                           CAR_20_2          294                  15         5.102041         11–20        6     6      3
             104                           CAR_22_0          294                  16         5.442177         11–20        3     6      7
             105                           CAR_24_1          294                  16         5.442177         11–20        3     5      8
             107                            CE_16_1          294                  19         6.462585         11–20        8     5      6
             113                            CE_20_4          294                  11         3.741497         11–20        7     2      2
             114                            CE_20_5          294                  17         5.782313         11–20        8     4      5
             117                        Cer_38_1_2O          294                  11         3.741497         11–20        5     3      3
             118                    Cer_38_1_NS_neg          294                  13         4.421769         11–20        2     5      6
             119                        Cer_40_0_2O          294                  12         4.081633         11–20        4     5      3
             120                    Cer_40_0_2O_neg          294                  12         4.081633         11–20        2     6      4
             123                        Cer_40_2_2O          294                  11         3.741497         11–20        3     5      3
             124                    Cer_40_2_NS_neg          294                  12         4.081633         11–20        4     4      4
             125                        Cer_41_0_2O          294                  12         4.081633         11–20        4     4      4
             129                        Cer_42_0_2O          294                  15         5.102041         11–20        3     9      3
             130                    Cer_42_0_2O_neg          294                  17         5.782313         11–20        3     9      5
             131                    Cer_42_1_2O_neg          294                  13         4.421769         11–20        3     4      6
             133                      Cer_42_1_2O_2          294                  11         3.741497         11–20        3     5      3
             134                        Cer_42_2_2O          294                  12         4.081633         11–20        3     6      3
             136                        Cer_42_3_2O          294                  15         5.102041         11–20        7     4      4
             137                    Cer_42_3_2O_neg          294                  15         5.102041         11–20        7     4      4
             139                    Cer_43_1_2O_neg          294                  11         3.741497         11–20        2     5      4
             142                            DG_36_2          294                  15         5.102041         11–20        2     6      7
             146                            FA_16_1          294                  13         4.421769         11–20        2     4      7
             150                            FA_18_3          294                  15         5.102041         11–20        1     8      6
             152                            FA_20_1          294                  13         4.421769         11–20        2     4      7
             156                            FA_20_5          294                  13         4.421769         11–20        3     4      6
             157                            FA_22_1          294                  18         6.122449         11–20        4     4     10
             166                            FA_24_5          294                  18         6.122449         11–20        4     7      7
             167                            FA_26_3          294                  13         4.421769         11–20        5     4      4
             168                            FA_34_0          294                  17         5.782313         11–20        8     3      6
             171                         FAHFA_38_2          294                  11         3.741497         11–20        1     5      5
             175                                 FC          292                  19         6.506849         11–20        4     7      8
             176                    GM3_32_1_2O_neg          294                  11         3.741497         11–20        5     5      1
             189                 HexCer_40_2_2O_neg          294                  12         4.081633         11–20        4     3      5
             190                 HexCer_41_1_2O_neg          294                  13         4.421769         11–20        5     4      4
             191                 HexCer_41_2_2O_neg          294                  16         5.442177         11–20        5     6      5
             196                         LNAPE_36_4          294                  12         4.081633         11–20        4     3      5
             199                           LPC_16_1          294                  13         4.421769         11–20        2     3      8
             200                           LPC_16_2          294                  11         3.741497         11–20        3     4      4
             205                           LPC_18_2          294                  14         4.761905         11–20        6     2      6
             212                           LPC_20_4          294                  14         4.761905         11–20        4     4      6
             214                           LPC_22_1          294                  18         6.122449         11–20        3     5     10
             215                           LPC_22_3          294                  13         4.421769         11–20        5     2      6
             216                           LPC_22_5          294                  11         3.741497         11–20        4     1      6
             217                           LPC_22_6          294                  11         3.741497         11–20        4     2      5
             219                           LPC_24_5          294                  18         6.122449         11–20        4     5      9
             227                         LPC_O_26_2          294                  13         4.421769         11–20        5     3      5
             230                           LPE_18_1          294                  13         4.421769         11–20        4     3      6
             232                           LPE_20_5          294                  12         4.081633         11–20        3     3      6
             234                           LPE_22_6          294                  12         4.081633         11–20        3     2      7
             235                         LPE_O_16_1          294                  11         3.741497         11–20        5     2      4
             236                         LPE_O_18_2          294                  13         4.421769         11–20        5     5      3
             238                           LPI_18_2          294                  15         5.102041         11–20        3     6      6
             240                           LPI_20_4          294                  18         6.122449         11–20        4     6      8
             242                            PC_26_0          294                  18         6.122449         11–20        7     5      6
             243                            PC_28_0          294                  13         4.421769         11–20        6     6      1
             244                            PC_28_1          294                  15         5.102041         11–20        7     3      5
             246                            PC_30_1          294                  12         4.081633         11–20        6     3      3
             256                            PC_33_4          294                  17         5.782313         11–20        5     5      7
             257                            PC_34_2          294                  12         4.081633         11–20        3     6      3
             258                            PC_34_3          294                  14         4.761905         11–20        5     8      1
             262                            PC_35_1          294                  14         4.761905         11–20        7     1      6
             266                            PC_35_5          294                  13         4.421769         11–20        4     4      5
             269                            PC_36_2          294                  17         5.782313         11–20        4     3     10
             270                            PC_36_3          294                  17         5.782313         11–20        6     5      6
             271                            PC_36_4          294                  14         4.761905         11–20        6     5      3
             280                            PC_38_1          294                  15         5.102041         11–20        2     4      9
             283                            PC_38_5          294                  11         3.741497         11–20        3     3      5
             285                            PC_38_7          294                  18         6.122449         11–20        6     6      6
             288                            PC_39_1          294                  12         4.081633         11–20        3     7      2
             292                            PC_39_7          294                  11         3.741497         11–20        5     3      3
             293                            PC_40_1          294                  16         5.442177         11–20        2     7      7
             294                            PC_40_2          294                  18         6.122449         11–20        5     6      7
             295                            PC_40_3          294                  13         4.421769         11–20        2     3      8
             299                            PC_40_7          294                  11         3.741497         11–20        6     2      3
             303                            PC_42_5          294                  14         4.761905         11–20        3     4      7
             304                            PC_42_7          294                  13         4.421769         11–20        4     3      6
             309                          PC_O_32_0          294                  12         4.081633         11–20        4     4      4
             311                          PC_O_33_2          294                  14         4.761905         11–20        8     4      2
             313                          PC_O_34_1          294                  18         6.122449         11–20        8     4      6
             317                          PC_O_35_4          294                  13         4.421769         11–20        3     6      4
             318                          PC_O_35_6          294                  13         4.421769         11–20        4     7      2
             319                          PC_O_35_7          294                  14         4.761905         11–20        5     4      5
             325                          PC_O_36_6          294                  13         4.421769         11–20        4     5      4
             328                          PC_O_38_0          294                  14         4.761905         11–20        1     7      6
             353                            PE_34_1          294                  13         4.421769         11–20        4     3      6
             354                            PE_34_2          294                  13         4.421769         11–20        7     2      4
             355                            PE_34_3          294                  18         6.122449         11–20        8     3      7
             356                            PE_36_1          294                  16         5.442177         11–20        3     6      7
             360                            PE_38_4          294                  11         3.741497         11–20        2     3      6
             361                            PE_38_6          294                  19         6.462585         11–20        7     5      7
             369                          PE_O_36_7          294                  17         5.782313         11–20        4     5      8
             372                          PE_O_38_2          294                  15         5.102041         11–20        6     4      5
             377                          PE_O_38_7          294                  17         5.782313         11–20        3     6      8
             380                          PE_O_40_7          294                  11         3.741497         11–20        5     3      3
             382                          PE_O_40_9          294                  14         4.761905         11–20        4     4      6
             386                            PG_36_2          294                  11         3.741497         11–20        2     5      4
             387                            PI_32_1          294                  14         4.761905         11–20        6     4      4
             388                            PI_34_1          294                  12         4.081633         11–20        6     3      3
             410                         SM_34_0_2O          294                  11         3.741497         11–20        3     5      3
             414                       SM_34_2_2O_2          294                  12         4.081633         11–20        3     3      6
             417                         SM_36_0_2O          294                  18         6.122449         11–20        2     7      9
             422                       SM_38_1_2O_1          294                  11         3.741497         11–20        1     3      7
             424                         SM_38_2_2O          294                  15         5.102041         11–20        5     3      7
             425                         SM_38_3_2O          294                  18         6.122449         11–20        5     6      7
             431                         SM_39_2_2O          294                  12         4.081633         11–20        1     8      3
             432                         SM_40_0_2O          294                  11         3.741497         11–20        3     7      1
             446                       SM_42_2_2O_1          294                  12         4.081633         11–20        4     5      3
             448                       SM_42_2_2O_3          294                  15         5.102041         11–20        7     4      4
             450                         SM_42_4_2O          294                  13         4.421769         11–20        6     3      4
             451                         SM_42_5_2O          294                  15         5.102041         11–20        8     2      5
             452                       SM_43_1_2O_1          294                  11         3.741497         11–20        2     7      2
             455                       SM_43_2_2O_2          294                  12         4.081633         11–20        3     6      3
             458                         SM_44_1_2O          294                  11         3.741497         11–20        2     6      3
             460                         SM_44_3_2O          294                  12         4.081633         11–20        3     2      7
             461                            TG_34_0          294                  17         5.782313         11–20        5     5      7
             479                          TG_46_3_1          294                  19         6.462585         11–20        9     7      3

For this group. Although some variables showed differences in the number of outlier observations between treatment groups, this pattern alone does not provide evidence of data entry or measurement errors.

In [213]:
outliers_6_10 = outlier_frequency[
    outlier_frequency["Outlier_Group"] == "6–10"
].copy()

outliers_6_10.shape

(232, 6)

In [214]:
outliers_6_10 = outlier_frequency[
    outlier_frequency["Outlier_Group"] == "6–10"
].copy()

for treatment in df["Treatment"].unique():
    outliers_6_10[treatment] = 0

for i in outliers_6_10.index:
    position = outliers_6_10.loc[i, "Column_Position"]
    values = df.iloc[:, position]

    q1 = values.quantile(0.25)
    q3 = values.quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outlier_mask = (values < lower_bound) | (values > upper_bound)

    for treatment in df["Treatment"].unique():
        outliers_6_10.loc[i, treatment] = (
            outlier_mask & (df["Treatment"] == treatment)
        ).sum()

outliers_6_10 = outliers_6_10[
    [
        "Variable",
        "Non_Missing",
        "Potential_Outliers",
        "Outlier_Percent",
        "Placebo",
        "SH60",
        "SH120"
    ]
]

print(outliers_6_10.to_string(index=False))

                                 Variable  Non_Missing  Potential_Outliers  Outlier_Percent  Placebo  SH60  SH120
                                Citruline          288                   6         2.083333        0     2      4
                              Fenylalanin          288                  10         3.472222        0     6      4
                               Isoleucine          288                   7         2.430556        1     4      2
                            Aspartic_Acid          288                   7         2.430556        2     4      1
                               Methionine          288                   7         2.430556        1     4      2
                                Ornithine          288                  10         3.472222        1     5      4
                                  Proline          288                  10         3.472222        2     5      3
              Pyrrolidone_carboxylic_acid          288                   6         2.083333        0     5      1
                                Threonine          288                   9         3.125000        4     4      1
                                 Tyrosine          288                   7         2.430556        0     4      3
                              Sebum_cheek          295                   9         3.050847        2     1      6
                                  Wrinkle          295                  10         3.389831        5     3      2
                      Pores_Area_forehead          291                   9         3.092784        5     2      2
                              GLOSS_Cheek          295                   6         2.033898        2     2      2
                             ITA_forehead          295                   9         3.050847        1     4      4
                      Elasticity_R3_cheek          295                   7         2.372881        1     3      3
                   Elasticity_R4_forehead          295                  10         3.389831        2     6      2
                   Elasticity_R9_forehead          295                   8         2.711864        1     3      4
                      Elasticity_R9_cheek          295                   6         2.033898        0     1      5
                      Epidermal_thickness          295                   6         2.033898        3     2      1
                                 CAR_14_1          294                  10         3.401361        4     6      0
                                 CAR_16_1          294                   8         2.721088        4     3      1
                                 CAR_16_2          294                   9         3.061224        2     5      2
                                 CAR_16_3          294                   7         2.380952        2     5      0
                                 CAR_18_2          294                   8         2.721088        3     3      2
                                 CAR_20_1          294                   8         2.721088        3     1      4
                                 CAR_26_0          294                  10         3.401361        1     4      5
                                  CE_17_0          294                  10         3.401361        4     0      6
                                  CE_18_1          294                  10         3.401361        5     4      1
                                  CE_18_3          294                   6         2.040816        2     3      1
                                  CE_20_3          294                   7         2.380952        3     3      1
                                  CE_22_6          294                  10         3.401361        3     1      6
                          Cer_34_1_NS_neg          294                   6         2.040816        4     1      1
                              Cer_40_1_2O          294                   8         2.721088        2     4      2
                          Cer_40_1_NS_neg          294                   8         2.721088        2     3      3
                              Cer_41_1_2O          294                   8         2.721088        3     5      0
                          Cer_41_1_NS_neg          294                   8         2.721088        1     2      5
                              Cer_41_2_2O          294                   7         2.380952        3     4      0
                            Cer_42_1_2O_1          294                  10         3.401361        4     5      1
                          Cer_42_2_NS_neg          294                   7         2.380952        0     2      5
                              Cer_43_1_2O          294                   7         2.380952        2     3      2
                              Cer_43_2_2O          294                   9         3.061224        3     4      2
                          Cer_44_1_2O_neg          294                   8         2.721088        1     3      4
                                  FA_14_0          294                  10         3.401361        1     6      3
                                  FA_14_1          294                   9         3.061224        1     4      4
                                  FA_16_0          294                   7         2.380952        1     3      3
                                  FA_16_3          294                   8         2.721088        0     5      3
                                  FA_18_2          294                   9         3.061224        0     5      4
                                  FA_19_1          294                   9         3.061224        0     2      7
                                  FA_20_2          294                  10         3.401361        1     2      7
                                  FA_22_2          294                   7         2.380952        2     1      4
                                  FA_22_3          294                  10         3.401361        2     3      5
                                  FA_22_5          294                   7         2.380952        1     3      3
                                  FA_22_6          294                   6         2.040816        2     2      2
                                  FA_24_1          294                   9         3.061224        1     4      4
                               FAHFA_36_1          294                   7         2.380952        0     2      5
                          GM3_42_1_2O_neg          294                   8         2.721088        3     1      4
                          GM3_42_2_2O_neg          294                   7         2.380952        4     1      2
                          Hex3Cer_34_1_2O          294                   7         2.380952        3     3      1
                          Hex3Cer_40_1_2O          294                   9         3.061224        4     4      1
                           HexCer_40_1_2O          294                  10         3.401361        4     5      1
                           HexCer_42_1_2O          294                   8         2.721088        2     4      2
                       HexCer_42_1_2O_neg          294                   7         2.380952        4     1      2
                       HexCer_42_2_2O_neg          294                   8         2.721088        3     4      1
                                 LPC_17_0          294                   7         2.380952        0     5      2
                                 LPC_20_0          294                   9         3.061224        3     1      5
                                 LPC_20_1          294                   7         2.380952        1     1      5
                                 LPC_20_2          294                   9         3.061224        3     3      3
                                 LPC_20_3          294                  10         3.401361        3     2      5
                                 LPC_22_0          294                   7         2.380952        2     2      3
                                 LPC_24_0          294                   8         2.721088        2     2      4
                               LPC_O_16_0          294                   8         2.721088        4     3      1
                                 LPE_16_0          294                   6         2.040816        3     1      2
                                 LPE_20_3          294                   9         3.061224        3     3      3
                                 LPE_22_5          294                   9         3.061224        4     1      4
                                 LPI_20_3          294                  10         3.401361        3     4      3
                                  PC_31_2          294                   9         3.061224        4     2      3
                                  PC_32_0          294                   8         2.721088        2     5      1
                                  PC_32_2          294                   9         3.061224        5     4      0
                                  PC_32_3          294                   8         2.721088        2     3      3
                                  PC_33_0          294                   7         2.380952        4     2      1
                                  PC_35_0          294                   9         3.061224        2     4      3
                                  PC_36_0          294                   8         2.721088        2     3      3
                                  PC_36_1          294                   7         2.380952        2     1      4
                                  PC_36_5          294                   8         2.721088        1     3      4
                                  PC_37_5          294                   7         2.380952        2     2      3
                                  PC_37_7          294                   7         2.380952        3     2      2
                                  PC_38_2          294                   8         2.721088        4     0      4
                                  PC_38_3          294                   7         2.380952        3     2      2
                                  PC_38_8          294                   8         2.721088        2     2      4
                                  PC_38_9          294                  10         3.401361        5     4      1
                                  PC_39_5          294                  10         3.401361        3     2      5
                                  PC_39_6          294                   6         2.040816        2     3      1
                                  PC_40_4          294                   7         2.380952        2     2      3
                                  PC_40_5          294                   8         2.721088        2     3      3
                                  PC_40_6          294                   7         2.380952        3     2      2
                                  PC_40_8          294                  10         3.401361        4     2      4
                                  PC_40_9          294                  10         3.401361        6     2      2
                                  PC_44_4          294                  10         3.401361        2     5      3
                                PC_O_31_1          294                   8         2.721088        2     4      2
                                PC_O_34_0          294                   8         2.721088        3     3      2
                                PC_O_34_4          294                  10         3.401361        3     3      4
                                PC_O_36_0          294                   9         3.061224        2     4      3
                                PC_O_36_2          294                  10         3.401361        6     0      4
                                PC_O_37_6          294                   7         2.380952        4     2      1
                                PC_O_37_7          294                   8         2.721088        3     3      2
                                PC_O_38_6          294                   8         2.721088        3     4      1
                                PC_O_38_7          294                   9         3.061224        1     4      4
                                PC_O_39_6          294                   9         3.061224        4     4      1
                                PC_O_40_2          294                   6         2.040816        2     2      2
                                PC_O_40_3          294                   8         2.721088        5     1      2
                                PC_O_42_1          294                   6         2.040816        2     3      1
                                PC_O_42_2          294                   9         3.061224        6     1      2
                                PC_O_42_3          294                   8         2.721088        6     0      2
                                PC_O_44_5          294                   7         2.380952        4     1      2
                                PC_O_44_6          294                   7         2.380952        4     0      3
                                PC_O_44_7          294                   7         2.380952        4     1      2
                                PC_O_46_5          294                   6         2.040816        4     1      1
                                PC_O_46_7          294                   6         2.040816        2     0      4
                                  PE_36_2          294                   7         2.380952        2     2      3
                                  PE_36_3          294                  10         3.401361        5     1      4
                                  PE_36_4          294                   9         3.061224        4     2      3
                                PE_O_34_2          294                   9         3.061224        3     5      1
                                PE_O_34_3          294                   9         3.061224        3     5      1
                                PE_O_36_2          294                   7         2.380952        2     3      2
                                PE_O_36_3          294                   8         2.721088        4     2      2
                                PE_O_36_4          294                   6         2.040816        2     4      0
                                PE_O_36_5          294                   8         2.721088        5     3      0
                                PE_O_37_5          294                   8         2.721088        1     2      5
                                PE_O_37_6          294                   9         3.061224        2     1      6
                                PE_O_38_4          294                   9         3.061224        3     5      1
                                PE_O_38_5          294                   6         2.040816        2     4      0
                                PE_O_38_6          294                   8         2.721088        3     5      0
                                PE_O_39_6          294                   6         2.040816        1     3      2
                                PE_O_39_7          294                   9         3.061224        2     1      6
                                PE_O_40_8          294                   7         2.380952        1     4      2
                                PE_O_42_7          294                   9         3.061224        5     2      2
                                PE_O_42_8          294                   7         2.380952        3     2      2
                                  PI_36_2          294                   6         2.040816        2     2      2
                                  PI_36_4          294                   6         2.040816        3     0      3
                                  PI_37_4          294                   7         2.380952        3     2      2
                                  PI_40_5          294                   7         2.380952        1     2      4
                                  PI_40_6          294                  10         3.401361        2     5      3
                               SM_29_1_2O          294                   7         2.380952        2     3      2
                               SM_30_0_2O          294                   9         3.061224        0     6      3
                               SM_32_1_2O          294                   6         2.040816        1     1      4
                             SM_32_2_2O_2          294                   7         2.380952        2     3      2
                             SM_33_1_2O_1          294                   6         2.040816        2     2      2
                             SM_33_1_2O_2          294                   6         2.040816        1     4      1
                               SM_33_2_2O          294                   6         2.040816        1     3      2
                             SM_34_1_3O_2          294                   6         2.040816        3     0      3
                             SM_34_2_2O_1          294                   9         3.061224        3     0      6
                               SM_36_2_2O          294                  10         3.401361        4     2      4
                               SM_36_3_2O          294                   6         2.040816        2     1      3
                               SM_38_0_2O          294                   7         2.380952        0     4      3
                               SM_38_4_2O          294                  10         3.401361        2     3      5
                             SM_39_1_2O_3          294                   6         2.040816        1     3      2
                             SM_40_1_2O_1          294                   9         3.061224        4     3      2
                             SM_40_1_2O_2          294                   8         2.721088        4     0      4
                             SM_40_2_2O_2          294                  10         3.401361        5     2      3
                               SM_41_0_2O          294                   6         2.040816        1     2      3
                             SM_41_2_2O_1          294                   9         3.061224        4     1      4
                             SM_41_2_2O_2          294                   6         2.040816        1     3      2
                             SM_42_2_2O_2          294                   9         3.061224        3     3      3
                             SM_43_2_2O_1          294                   7         2.380952        1     4      2
                             SM_43_2_2O_3          294                   7         2.380952        1     4      2
                               SM_44_2_2O          294                   6         2.040816        0     3      3
                                TG_50_4_1          294                   9         3.061224        2     4      3
                                  TG_52_3          294                   7         2.380952        1     4      2
                                TG_52_4_2          294                   7         2.380952        0     4      3
                                TG_52_5_1          294                   7         2.380952        0     4      3
                                TG_52_5_2          294                  10         3.401361        2     4      4
                                  TG_53_4          294                  10         3.401361        3     5      2
                                  TG_53_5          294                   7         2.380952        2     3      2

Some variables showed differences in the number of observations between treatment groups, but this pattern again does not provide evidence of data entry or measurement errors.

## Conclusion

The clinical trial dataset was successfully cleaned and validated in preparation for statistical analysis. The process included standardizing the Excel structure and variable names, removing redundant information, checking data types, assessing missing values and duplicates, and validating participant and measurement-time records. Potential outliers were also investigated without automatically removing observations solely because they were extreme.

Overall, the cleaning and validation process provided a more consistent and structured dataset suitable for the next stage of the project. The resulting cleaned dataset will be used for statistical analysis of the clinical trial data.